### ISSUE TITLE
rich parameters: user environment variable input

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5981] opened 2023-02-02 16:13 UTC
I'm sure we can probably think of a better name but would be nice to have some type of parameter that lets users enter the environment variables for their workspace for example. 

Open questions:
- is there a way to hide these from the UI?

**Comment by mtojek** [comment] 2023-02-03 11:28
Is it related to https://github.com/coder/coder/issues/5980? I have a feeling that it overlaps a bit.

**Comment by bpmct** [comment] 2023-02-03 12:29
Yeah, I think it's related but wanted a separate issue for workspace-scoped env vars. (I was assuming this would be a parameter type like `bool`, `string`: but `key_value`) where the other one was Terraform variables.

**Comment by mtojek** [comment] 2023-02-03 12:32
Ok, I see :) I assumed that every variable would have a type and format too, even if they are strict Terraform variables, which could be a string type without format restrictions.

**Comment by zifeo** [comment] 2023-06-05 20:11
@mtojek Using the terraform variable, we could easily set secrets at template push time. I understand this is now deprecated, and that there is no alternative. Is this similar to this ticket or is there another tracking one?

**Comment by mtojek** [comment] 2023-06-06 08:05
> I understand this is now deprecated, and that there is no alternative. 

Incorrect. You can still use Terraform variables, but with [feature_use_managed_variables](https://coder.com/docs/v2/latest/templates/parameters#managed-terraform-variables) provider flag.

If you set `sensitive = true`, you can use the variable to pass secrets.

**Comment by zifeo** [comment] 2023-06-06 08:11
@mtojek I have tried and tried, the coder cli does not take into account the `TF_VAR_X` anymore with managed variables. Neither was I able to get a similar behaviour using `coder_parameter` data source. Is there a doc on what is expected to work with env var?

**Comment by mtojek** [comment] 2023-06-06 08:37
You can try to use `values.yml` file:

```
region: us-east-1
secret_field: magic
cpu: 1
```

then:
```
coder templates push my-awesome-template -d my-template-directory --variables-file values.yml
```

**Comment by zifeo** [comment] 2023-06-06 08:43
@mtojek we use [Lade](https://github.com/zifeo/lade) to inject secret as temporary environment variables. Mounting a file is more cumbersome, therefore my comment about the ability to load secrets via env vars.

**Comment by zifeo** [comment] 2023-06-12 08:23
@mtojek I saw that coder 0.24.x was released with all legacy parameters removed. Do you have an idea when loading parameter through env var will be back on the roadmap?

**Comment by mtojek** [comment] 2023-06-12 09:03
> I have tried and tried, the coder cli does not take into account the TF_VAR_X anymore with managed variables. Neither was I able to get a similar behaviour using coder_parameter data source. 
> we use [Lade](https://github.com/zifeo/lade) to inject secret as temporary environment variables. Mounting a file is more cumbersome, therefore my comment about the ability to load secrets via env vars.

I can confirm that it is not on the roadmap now, and we don't plan to work on it in the nearest future. I understand that using a config file is unfortunate for your case.

**Comment by zifeo** [comment] 2023-06-12 22:36
@mtojek I have given a try, and it seems there is still different than previous way to load env vars. The values.yml I am using is following your guidance. Yet during the template push, I get:
<img width="705" alt="image" src="https://github.com/coder/coder/assets/9053709/e4887461-7a02-4973-a32d-fced2cbd7593">

Looks like the variables may not be present during that step of the build? Also reading the doc again, it seems that template user may see those values (or afaik). Is that correct?

**Comment by mtojek** [comment] 2023-06-13 07:22
> Looks like the variables may not be present during that step of the build? Also reading the doc again, it seems that template user may see those values (or afaik). Is that correct?

Yes, unless you mark them as sensitive. 

BTW It would be easier to guide you if you share your template and the command you're calling.

**Comment by matifali** [comment] 2023-11-13 12:43
@mtojek and @bpmct, I think this issue is no longer relevant.

**Closed** 2023-11-13 12:57 UTC
Labels: parameters
