### ISSUE TITLE
`code-server` integrated terminal does not re-open when `code-server` is re-opened

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4096] opened 2022-09-16 23:14 UTC
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

As a developer, it is a pain to do multiple keyboard clicks to open the integrated terminal in `code-server`

In Coder OSS, if I re-open `code-server` a previous opened terminal does not show, but once I re-open terminal, you see the previous shell sessions.

Reproduced in `4.6.1` and `4.7.0` `code-server`

**Comment by jsjoeio** [comment] 2022-10-13 20:15
Sorry this one slipped through the cracks! 

Here's what I'm doing:
**Steps to Reproduce**
1. Navigate to my deployment: dev.coder.com
2. Start workspace based off [`coder` template](https://dev.coder.com/templates/coder)
3. Open `code-server` in new browser tab (i.e. https://dev.coder.com/@jsjoeio/joe-coder.dev/apps/code-server/?folder=/home/coder/test-egghead)
4. Open Integrated Terminal
5. Close tab
6. Open `code-server` again in new browser tab

**Expected**
`code-server` should load with the Integrated Terminal still open.

**Actual**
`code-server` loads with the Integrated Terminal still open.

**Video Demo**

https://user-images.githubusercontent.com/3806031/195700147-f1b7ce22-a37e-4b74-b7b3-29841a993b79.mov

browser: Chromium
code-server: 4.7.1
coder: [Coder v0.9.10-devel+459ee4e6](https://github.com/coder/coder/commit/459ee4e66a734566641506f525350848cf535801)

@sharkymark let me know if you're still experiencing this and what steps I can take to reproduce it.

**Comment by bpmct** [comment] 2022-10-16 01:54
I'm also not able to reproduce this :/

https://user-images.githubusercontent.com/22407953/196014202-482e2cfa-f5f4-4029-8d63-542a385a62c6.mov

**Comment by jsjoeio** [comment] 2022-11-01 16:33
Since we couldn't reproduce this and haven't had any reports, I'm going to close this. If it happens again, let me know!

**Comment by sharkymark** [comment] 2022-11-01 18:59
https://www.loom.com/share/ad3caa3d0ad04cef8fd5b0b23129a79b

@bpmct @jsjoeio maybe my chrome? watch me reproduce it.

**Comment by jsjoeio** [comment] 2022-11-01 20:46
One thing I'm seeing different between @bpmct and your deployment is the URL when you access code-server.

Ben's is on `/apps/code-server` and yours is `/apps/VS%20Code` 🤔 But I guess that's not super important. I'm really unsure. @code-asher any ideas?

**Comment by bpmct** [comment] 2022-11-01 21:37
This is super odd. The [dogfood](https://github.com/coder/coder/blob/main/dogfood/main.tf) template persists the template, but the [gcp-linux](https://github.com/coder/coder/blob/main/examples/templates/gcp-linux/main.tf) template does not. I originally thought this was the app URL includes `?folder=/home/coder` but this doesn't seem to be it. 


https://user-images.githubusercontent.com/22407953/199346318-4f5084df-0956-4c09-9fdf-76ec0b983978.mov

**Comment by jsjoeio** [comment] 2022-11-01 22:21
Ahhh! I think I know what it is.

Check out the url for code-server here:

https://github.com/coder/coder/blob/main/dogfood/main.tf#L44

vs. here:

https://github.com/coder/coder/blob/main/examples/templates/gcp-linux/main.tf#L67

The `gcp-linux` hardcodes a folder which I believe is causing the issue. I'm guessing it's either clearing browser storage or treating it as a "fresh start" aka the terminal open/closed not persisting.

**Comment by bpmct** [comment] 2022-11-01 22:30
I thought that was the case but tested and didn't see that behavior.

**Comment by jsjoeio** [comment] 2022-11-01 23:01
Darn, hoping that was it. Well I guess we'll have to continue investigating then. I'll play around with the `gcp-linux` and see if I notice any other weird behaviors.

**Comment by kylecarbs** [comment] 2022-12-14 16:01
@jsjoeio any info/ideas?

**Comment by jsjoeio** [comment] 2022-12-14 16:16
I did learn that the terminal state is stored on the client side. [Reference](https://github.com/coder/code-server/discussions/5812#discussioncomment-4323692) 

Don't know if that's exactly what we're talking about it here but worth sharing.

I will assign myself and try reproducing again.

**Comment by jsjoeio** [comment] 2022-12-15 20:20
I'm going to test in plain old code-server, the latest version - 4.9.1-rc.1

**Comment by jsjoeio** [comment] 2022-12-15 20:29
Here's what I'm doing:
**Steps to Reproduce**
1. Run `code-server`
2. Open as PWA
3. Open Integrated Terminal
4. Quit PWA
5. Reopen PWA

**Expected**
`code-server` should load with the Integrated Terminal still open.

**Actual**
`code-server` loads with the Integrated Terminal still open.

**Video Demo**

https://youtu.be/LeNDrbeTuuw

browser: Chromium
code-server: 4.9.1-rc.1

**Notes**
That Loom video @sharkymark originally posted is gone. Maybe this is no longer an issue with the latest code-server version?

I'm going to close this for now. If it comes up again, let me know!

**Closed by jsjoeio** 2022-12-15 20:29 UTC
Labels: bug
