### ISSUE TITLE
Bug: I chose ☁️ as my template emoji but it does not show up

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3769] opened 2022-08-30 23:45 UTC
Version: [`v0.8.10+01a06e1`](https://github.com/coder/coder/commit/01a06e1213ef5e0c3a705d27a19551f138d275de)

This is what I see - for an emoji-ed template but it should be this. ☁️ I've seen this with other emojis but not all. 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2022166/187562631-7b2c0423-ac7e-46da-9e1d-d0a865b62af7.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/2022166/187562758-b8266409-d1c0-4cfd-90bd-a03b269afe8a.png">

**Comment by kylecarbs** [comment] 2022-08-30 23:47
Duplicate of #3689. I'll make sure this gets fixed!

**Closed by kylecarbs** 2022-08-30 23:47 UTC
Labels: bug, site
