### ISSUE TITLE
clicking "Create Workspace" with a name that already exists wipes the inputs with no error

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10268] opened 2023-10-14 19:18 UTC
i have a workspace named `code-server` and when I attempt to create another workspace with the same name, the UI does not return a `Name already exists` error and the all of the form inputs are wiped. experienced on 2.3.0 using both Chrome & Firefox.

https://www.loom.com/share/aecd94435f914fbf834cd28f6193de95?sid=cd813183-07e3-4bc0-a034-1ddc5cd77a4e

**Comment by Parkreiner** [comment] 2023-10-14 22:06
I have a pretty good idea what the source of the issue is, especially since you said *all* inputs got wiped. The form manager for that page has a setting flipped on that says "if the default values fed into the form change during a UI update, treat that as an error, and wipe the entire form with the new defaults, just to avoid things getting out of sync."

The quickest solution would be to flip it off (and that only requires changing one line of code), but I feel that if the default values are changing somehow, the "simple" approach could end up "swallowing" bigger issues down the line

Either way, I can look into the issue this upcoming week

**Comment by BrunoQuaresma** [comment] 2023-10-16 13:13
I have time this week to work on a few bugs.

**Comment by BrunoQuaresma** [comment] 2023-10-16 15:31
I had a different experience when trying to create a workspace with a duplicated name.

**Comment by BrunoQuaresma** [comment] 2023-10-16 15:36
I was able to reproduce this using Eric's deployment.

**Comment by BrunoQuaresma** [comment] 2023-10-16 15:39
I can confirm this issue is already fixed on main 👍

**Closed by BrunoQuaresma** 2023-10-16 15:39 UTC
Labels: site, s2, bug
