### ISSUE TITLE
Improve error message when SSH connection drops

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#1369] opened 2022-05-10 18:11 UTC
## Problem Summary
On a spotty network that resulted in a dropped connection between client and v2-provisioned EC2 instance, the error returned was: `wait: remote command exited without exit status or exit signal`

this message is a bit confusing and does not clearly explain that the connection was dropped.

## Definition of Done

Check for this error and translate this to  "Lost connection to agent."
Test for lost connection produces this error

**Comment by ketang** [comment] 2022-06-07 19:42
For reference in case it helps:
https://go.googlesource.com/crypto/+/master/ssh/session.go#476

**Comment by dwahler** [comment] 2022-07-22 19:10
I did some investigation into how the `golang.org/x/crypto/ssh` package handles unexpectedly dropped connections:

* The library's example code (using a direct TCP connection) returns the same `remote command exited without exit status or exit signal` message, which as @ketang pointed out is the string representation of an `ssh.ExitMissingError`. It's possible to retrieve the underlying I/O error (e.g. a timeout) by calling `client.Close(); client.Wait()`.
* With our WebRTC backend, `client.Wait()` returns an `io.EOF` error regardless of whether the connection was closed cleanly or uncleanly. I haven't figured out yet what's causing this difference in behavior.
* With our Wireguard backend, I couldn't reproduce the issue. Even disabling the physical network interface doesn't seem to drop the SSH connection -- it just hangs and comes back when the connection is available again.

So in the case of WebRTC, I don't see a way to do much better than just replacing the error message with a better one (#3131).

I think the Wireguard behavior of keeping the connection alive is better overall. But it might still be worth trying to give some indication (maybe a desktop notification?) while it's interrupted, especially if we can determine that the problem is with the user's internet connection rather than the remote end.

**Comment by ketang** [comment] 2022-07-31 23:43
I suspect the desktop notification could easily become a pest in certain conditions.  I think we should kick that one down the road until we get into the system tray business.

**Comment by bpmct** [comment] 2022-08-01 15:43
Once #2779 is merged, will we likely see a different behavior / error pattern?

**Comment by bpmct** [comment] 2022-08-08 19:14
@dwahler is this fixed by #3131?

**Comment by dwahler** [comment] 2022-08-09 15:16
Depends on your interpretation. If the goal of this ticket is to improve that one specific error message, then yes. If the goal is to *reliably* give a useful message when an SSH connection drops, then it's not really done, because #3131 only affects the behavior with WebRTC, so it'll become moot when #2779 lands and we switch to Tailscale for client connections.

I figured it made sense to keep this ticket open in order to not split the discussion, but I don't mind closing it if others feel differently.

**Comment by tjcran** [comment] 2022-08-10 15:44
> Depends on your interpretation. If the goal of this ticket is to improve that one specific error message, then yes. If the goal is to _reliably_ give a useful message when an SSH connection drops, then it's not really done, because #3131 only affects the behavior with WebRTC, so it'll become moot when #2779 lands and we switch to Tailscale for client connections.
> 
> I figured it made sense to keep this ticket open in order to not split the discussion, but I don't mind closing it if others feel differently.

I would suggest that we close this ticket as the original requirements of this ticket are met by improving that specific error message. 

But we should also have an epic or something to track the general improvements to SSH drop messages.

**Closed by tjcran** 2022-08-10 15:44 UTC
Labels: backend, cli
