### ISSUE TITLE
Feature: Deprecate templates

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#6534] opened 2023-03-09 17:51 UTC
The user should be able to deprecate a template. When a template is deprecated Coder will:
- Show a warning to the users on the workspace page
- Show a deprecated badge in the workspaces page - item table item row
- Don’t show the template in the templates table
- Don’t let users create a new workspace with a deprecated template

**Comment by sharkymark** [comment] 2023-06-16 11:52
I know of at least one v1 enterprise customer who requires this.

**Comment by ericpaulsen** [comment] 2023-09-12 15:58
@sharkymark @BrunoQuaresma we have another customer asking for this.

**Comment by ammario** [comment] 2023-11-08 03:22
Duplicate of https://github.com/coder/coder/issues/6355

**Closed by ammario** 2023-11-08 03:22 UTC
