### ISSUE TITLE
Bug in v0.7.6 a494489: inconsistency of code-server terminal loading.

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2845] opened 2022-07-07 13:21 UTC
Sometimes the integrated terminal in code-server loads, sometimes it does not.

This is a critical problem since I need to use the terminal to stay in flow, along with the editor.  2 other users have seen similar things including @bpmct and Phorcys (Discord handle)

I've tried clearing the browser cache, and it sometimes resolves. But it came back an hour later.

## Expected Behavior

If I open a terminal in code-server, I should see a prompt.

## Current Behavior

When I start a terminal, the sub-window appears, but just black and no prompt.

See DevTools errors.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/2022166/177783272-c6277b6d-7f13-4dbd-9ca9-ec608fd22693.png">

**Comment by hfwang2020** [comment] 2022-07-07 15:57
I have a similar problem

**Comment by mark-theshark** [comment] 2022-07-07 16:13
@hfwang2020 It is so weird. Today, for 30 minutes, I was able to see terminals across my workspaces. I am using caddy as a reverse proxy in front of GCP VM running Coder as a systemd service. But now it's back to no terminal.

I am using the web terminal in the meantime, and if I have a JetBrains IDE in the same workspace, their terminal works fine.

**Comment by hfwang2020** [comment] 2022-07-08 00:10
i also deploy the service in the vps and use nginx as reverse proxy.  
and when i run the Command 'Terminal: Create New Terminal' 
![image](https://user-images.githubusercontent.com/72919822/177891048-d6baaba3-e0aa-4476-b472-af7a8279f568.png)

i have tryed to reinstall it. but this proplem still exist. maybe i should deploy it in docker at the beginning...

**Comment by kconley-sq** [comment] 2022-07-13 00:08
In versions prior to 0.7.6 I was able to eventually get the integrated terminal in code-server to appear (I think by refreshing the webpage a few times), but in 0.7.6 that workaround doesn't seem to work anymore, I can't get the terminal to ever appear.

When I check the JS console I saw a few errors that looked relevant:
```
Uncaught SyntaxError: Unexpected token '<' (at xterm.js:1:1)
main.js:1 Uncaught SyntaxError: Unexpected token '<' (at main.js:1:1)
main.js:1 Uncaught SyntaxError: Unexpected token '<' (at main.js:1:1)
```

Maybe in my case this is due to how we're always installing the latest version of `code-server` in our agent startup script (following [this example](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#example-usage)), and it seems like [there may be an issue with the integrated terminal in the latest 4.5.0 version of Coder](https://github.com/coder/code-server/issues/5321) which I confirmed is what we're using:
```
$ code-server --version
4.5.0 02b9d7ee856e31d9008d1ff24a175ff03b49010e with Code 1.68.1
```

I'll try using an older version of `code-server` and see if that gets us back to being able to open the terminal if we refresh the webpage enough times.

**Comment by kylecarbs** [comment] 2022-07-13 00:13
The issue you linked in `code-server` is the real issue. We're on it!

**Comment by jsjoeio** [comment] 2022-07-14 16:34
Update: we identified the issue in code-server and have [merged a fix](https://github.com/coder/code-server/pull/5332#issuecomment-1184644551). We need to fix a few other things but hope to cut a release by [next Friday](https://github.com/coder/code-server/milestone/43). Then coder/coder can update the version of code-server and close this.

**Comment by jsjoeio** [comment] 2022-07-21 17:17
We released [code-server 4.5.1](https://github.com/coder/code-server/releases/tag/v4.5.1) a couple days ago with the fix.

Can someone confirm if this is still an issue?

**Comment by kylecarbs** [comment] 2022-07-21 18:39
This has been fixed! Update your code-server version y'all!

**Closed by kylecarbs** 2022-07-21 18:39 UTC
Labels: bug, needs grooming

**Comment by jsjoeio** [comment] 2022-08-09 18:29
Hey all!

Just wanted to follow up and let you know we've added a new e2e suite that runs code-server's tests (including one for the terminal) against a reverse proxy to prevent this kind of bug from happening again. See https://github.com/coder/code-server/pull/5348

**Comment by Wolfy0615** [comment] 2022-08-28 06:39
It appears that I am having this bug yet again.

**Comment by bpmct** [comment] 2022-08-29 14:18
Hi @Wolfy0615 - I am able to reproduce this as well. We are working on #2779 which should resolve these (now networking-related) issues in Coder.
