### ISSUE TITLE
Cannot create template using a previously-deleted template's name

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2390] opened 2022-06-15 20:24 UTC
Minimal steps to reproduce

1. Create a template without specifying a non-default name
2. Delete template
3. Attempt to create again without specifying a non-default name

```sh
POST http://127.0.0.1:3000/api/v2/organizations/1816835b-12a1-4eb6-8de9-85cabe5785b5/templates: unexpected status code 500: Internal error inserting template.
        Error: execute transaction: insert template: pq: duplicate key value violates unique constraint "templates_organization_id_name_key"                          
Run 'coder templates create --help' for usage. 
```

**Comment by deansheather** [comment] 2022-06-15 20:30
Duplicate of #2152

**Closed by deansheather** 2022-06-15 20:30 UTC
