### ISSUE TITLE
After submitting workspace create, give an indication of status/progress

### ISSUE THREAD

**Issue by ketang** [coder/coder#2020] opened 2022-06-03 14:30 UTC
## Problem Statement
Currently after you initiate build of a workspace, you are taken to the `/workspaces/<uuid>` view.    On the former, there's no indication that anything is happening other than a tiny status indicator.

## Why do you want this feature?
Less effort to see what's going on.

## Are there any workarounds to get this functionality today?
Laboriously clicking on the row in the timeline corresponding to my current build.

## Definition of Done
~Two alternatives (maybe more)~

~- You should instead be taken to the `/builds/<uuid>` view.~
~- Some kind of progress or status indicator (that works) to show the user progress is happening~

As per discussion below:
Implement the following design:
![Screen Shot 2022-07-22 at 2 51 39 PM](https://user-images.githubusercontent.com/19142439/180504846-817b9977-1021-406c-852d-1d8e9230c99b.png)

## AC
- When clicked in the action button like "Start" the button should go into a loading state.
- During the loading state, we should display a cancel button, which is an icon with a tooltip.
- For accessibility, this cancel button should be aria-labeled.
 - During the canceling state, we should display the loading state for it without the cancel button.
 - Try to refactor our loading button to achieve this new design
 - Use existing tooltip component
 - Use existing loading spinner

**Comment by presleyp** [comment] 2022-06-03 15:00
I think this needs discussion about whether this is desired (it takes you away from the page with the links you'll use when the build is done) so I'm adding the needs-decision label.

**Comment by ketang** [comment] 2022-06-03 15:12
It doesn't have to be the build log page, but it's confusing to me that you initiate an action and are then just...?  How about a progress bar or the build log in a modal then?

**Comment by ketang** [comment] 2022-06-04 20:10
Or maybe a tiny build log that just shows the last n lines of the build log in the timeline view (where n is small).  Maybe it's open by default for any still-active jobs and closed for any completed jobs.  In both cases it could still take you to the complete log with a click.

**Comment by misskniss** [comment] 2022-06-07 19:13
Am I correct that if we abstract out the prescriptive approach here that we want: 

A visual indication in the UI of what is happening with the build for the workspace being created. 

This may not need to be a full page redirect. We should discuss further.

**Comment by ketang** [comment] 2022-06-07 20:11
Yeah, I think the most important thing is to show things are happening and progressing.  The actual view and level of detail are less important as long as they successfully communicate that.

**Comment by Kira-Pilot** [comment] 2022-07-20 20:57
@ketang @misskniss is this a duplicate of #2020?

**Comment by ketang** [comment] 2022-07-20 21:00
erm... this IS #2020, so... yes and no?

**Comment by Kira-Pilot** [comment] 2022-07-20 21:00
Sorry, I'm tired! Is this a duplicate of #3025?

**Comment by ketang** [comment] 2022-07-20 21:31
I don't think it's quite the same.  My intention here was not to indicate what the workplace status was but to let the user know that a change to the workspace is happening and progressing.  Showing a "Starting" or similar label helps a little bit, but doesn't communicate that progress is being made as opposed to something being stuck or broken.

**Comment by BrunoQuaresma** [comment] 2022-07-21 13:50
IMO what looks best:
- When clicked in the action button like "Start" the button should go into a loading state. 
- During the loading state, we should display a cancel button. To keep it visually clean, I think an icon button + tooltip is enough but I'm not against having a label too.
- During the canceling state, we should display the loading state for it without the cancel button. 
<img width="352" alt="Screen Shot 2022-07-21 at 10 48 37" src="https://user-images.githubusercontent.com/3165839/180229851-a00be94a-1a5a-42fd-b1a9-a32f389912bc.png">

Implementation considerations:
- The regular loading button only shows the spinner but I think in this case, the text would be very helpful as well. So we may need a new component or refactor the one we have.
- The tooltip style is just a mock thing, we should use the existing one. The same for the spinner and colors.

**Comment by Kira-Pilot** [comment] 2022-07-21 14:00
@BrunoQuaresma wow, thanks for looking at that so quickly! I would be fine with using just an icon without a label given this is a compound button. I can make sure we aria-label appropriately.

@ketang What do you think? Would implementation of the above design resolve this ticket?

**Comment by ketang** [comment] 2022-07-22 15:00
I think this will work well for indicating business more visibly.  In the happiest world, the state of the progress indicator would be derived from the actual progress of the job, but that's a very first world kind of improvement, and I don't think that level of fanciness is justified right now.

@BrunoQuaresma what have you thought about with respect to using color?

**Closed** 2022-07-25 22:13 UTC
Labels: feature, needs decision, frontend, needs grooming
