### ISSUE TITLE
Coder crash after deleting the certificate

### ISSUE THREAD

**Issue by atnomoverflow** [coder/coder#7868] opened 2023-06-06 07:08 UTC
hi i get an error about replication even thought i dont  use replication here's the log (the same log get's repeated many time).
```
 coderd: run replica update loop ...
    error= update replica:
               github.com/coder/coder/enterprise/replicasync.(*Manager).syncReplicas
                   /home/runner/work/coder/coder/enterprise/replicasync/replicasync.go:303
             - sql: no rows in result set
```
the error started after i deleted the trial certificate (before the 30 days) my team did not seem to need any enterprise feature at the time might need it when i start scaling but for now i dont think i need it .

**Comment by ericpaulsen** [comment] 2023-06-06 12:27
hi @atnomoverflow thank you for submitting this issue - can you provide your Coder environment variable values?

**Comment by atnomoverflow** [comment] 2023-06-06 16:02
coder:
  env:
    - name: CODER_ACCESS_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: access_url
    - name: CODER_OIDC_ISSUER_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: OIDC_issuer_url
    - name: CODER_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: OIDC_client_id
    - name: CODER_OIDC_IGNORE_EMAIL_VERIFIED
      value: "true"
    - name: CODER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: OIDC_secret
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: db_url
    - name: CODER_GITAUTH_0_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_CLIENT_ID
    - name: CODER_GITAUTH_0_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_CLIENT_SECRET
    - name: CODER_GITAUTH_0_ID
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_ID
    - name: CODER_GITAUTH_0_TYPE
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_TYPE
    - name: CODER_GITAUTH_0_AUTH_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_AUTH_URL
    - name: CODER_GITAUTH_0_TOKEN_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_TOKEN_URL
    - name: CODER_GITAUTH_0_VALIDATE_URL
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_VALIDATE_URL
    - name: CODER_GITAUTH_0_SCOPES
      valueFrom:
        secretKeyRef:
          name: coder-secret
          key: GITAUTH_SCOPES
  ingress:
    enable: true
    # host: coder.datiumsass-coder.cloudns.ph
    annotations: 
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/scheme: internet-facing
      #alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: "coder"
    # tls:
    #   enable: true
    #   secretName: coder-datium-tls-secret
  service:
      type: NodePort
      sessionAffinity: None

**Comment by Emyrk** [comment] 2023-06-08 15:56
@atnomoverflow is this still happening? I am having an issue reproducing this. 

If you could provide an order of events to help me, that would be great.

---

For any readers. The primary coderd is a "replica", even if the feature is disabled.

A. When we start coderd, it will insert itself into the replica's table.

B. At a given cadence (default 5s), it will update it's row with a new timestamp.

C. Every 30s, all replicas that have not updated themselves within the last 15s are deleted.

So this error means the replica failed to update itself (B) because it's row does not exist? From C I imagine?

A possible fix is if there is an update error from a sql.ErrNoRows, we can reinsert ourselves. Just feels strange this error has happened in the first place :thinking:

**Comment by Emyrk** [comment] 2023-06-08 15:58
@atnomoverflow If you have the server logs still, is this message anywhere in the logs?
`create http request for relay probe` ?
https://github.com/coder/coder/blob/356dc3a7cd94a7b14e374f37d1243db6a40f4844/enterprise/replicasync/replicasync.go#L261-L265

**Comment by atnomoverflow** [comment] 2023-06-08 17:21
@Emyrk  no it's not.

**Comment by Emyrk** [comment] 2023-06-08 18:12
I am going to close this issue then. I believe it was an edge case that triggered that failure, but the failure is correct.

The solution to this would be to restart coderd.

Thanks!

**Closed by Emyrk** 2023-06-08 18:12 UTC
Labels: bug
