### ISSUE TITLE
audit: IP is often unavailable 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5536] opened 2023-01-02 15:06 UTC
I noticed this in our dogfood deployment as well as my personal deployment (under a Caddy reverse proxy). 

<img width="1049" alt="Screen Shot 2023-01-02 at 7 04 52 AM" src="https://user-images.githubusercontent.com/22407953/210248991-042ac948-53bd-4ee1-abc2-23b3949705b5.png">

**Comment by Kira-Pilot** [comment] 2023-01-03 16:59
Closing as a duplicate of #5268; will make sure that issue is labeled high-priority.

**Closed by Kira-Pilot** 2023-01-03 16:59 UTC
Labels: bug
