### ISSUE TITLE
Interface on iPad (Safari) is zoomed

### ISSUE THREAD

**Issue by joscdk** [coder/coder#3012] opened 2022-07-17 20:09 UTC
I decided to test coder (Just the free version) in my on the go dev lab today, and so far it works really great.

Only thing is the interface is “zoomed” in the browser, both the coder site and the terminal. However the vs-code works fine

See the attached screenshots 

Version: v0.7.12+6f34cbf

![IMG_0032](https://user-images.githubusercontent.com/2535140/179423072-4abd2b24-cb31-4df5-8b4a-bb97ffa29bf6.png)
![IMG_0033](https://user-images.githubusercontent.com/2535140/179423077-2fa8bde5-8a86-47aa-ac63-d55a1dbcc1d3.png)
![IMG_0034](https://user-images.githubusercontent.com/2535140/179423107-8f56dd4f-2e81-4b33-b13e-a066bb1f7075.png)

**Comment by ammario** [comment] 2022-07-18 14:41
Thanks for the bug report @joscdk 

@BrunoQuaresma — could you look into this?

**Comment by BrunoQuaresma** [comment] 2022-07-20 16:27
Unfortunately, I don't have an IPad to test that and I'm not able to reproduce using my MacBook. But, I think we can improve the layout a bit to be more responsive. What do you think?

**Comment by BrunoQuaresma** [comment] 2022-07-25 16:46
Closing in favor of #3185

**Closed by BrunoQuaresma** 2022-07-25 16:46 UTC
Labels: duplicate
