### ISSUE TITLE
During auto shutdown, Coder submits old variables which can break the ability to shutdown

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#7073] opened 2023-04-10 22:30 UTC
I believe the repro is this:

- Create a template with an input variable <X> 
- Create a workspace and set the input variable <X> to "foo"
- Update the template (but not the workspace) to delete the input variable <X>
- Wait for auto-shutdown to happen

I believe you'll get an error that looks like the following:

```Error: Value for undeclared variable
A variable named "<X>" was assigned on the command line, but the root module does not declare a variable of that name. To use this value, add a "variable" block to the configuration.```

This ends up failing the terraform plan for the shutdown, and thus the workspace is not offline.

**Comment by kylecarbs** [comment] 2023-04-11 01:50
We shall fix this!

cc @mtojek

**Comment by mtojek** [comment] 2023-04-11 10:14
Taking a look

**Comment by mtojek** [comment] 2023-04-11 12:08
I reproduced a bit different issue, but I believe that the root cause is the same.

What I did is:
1. Create a new template. It doesn't need to use variables for now.
2. Create a workspace using the above template.
3. Set the autostop TTL=300s using API.
4. Push a new template revision with the new required variable (no default):

```
variable "region2" {
  description = "This is region."
  type        = string
}
```

5. Wait for the autostop to kick-off:

<img width="1024" alt="Screenshot 2023-04-11 at 14 02 21" src="https://user-images.githubusercontent.com/14044910/231156942-9eec1113-c1bd-4dad-85bb-0893690b3644.png">

**Comment by mtojek** [comment] 2023-04-11 12:09
Root cause: it seems to be related to the template version that is used. For some reason (a bug?), autostop uses the latest template version instead of the one that is assigned before the autostop event.

**Comment by johnstcn** [comment] 2023-04-11 12:17
Context: https://github.com/coder/coder/issues/6049 modified the autostart behaviour to automatically update the workspace to the latest template version. Previously, it would use the template version of the last successful build.

**Comment by mtojek** [comment] 2023-04-11 12:36
@bpmct It seems that we have conflicting assumptions. Do you think that we should revert the auto-update? Otherwise, it will be either confusing for users ("did it update or not") or it will keep failing.

**Comment by bpmct** [comment] 2023-04-11 12:59
I see. Why are we updating the version on stop instead of the next start?

I guess we can disable the "auto-update" behavior for now, but I know some users are hoping to use Coder to ensure developers all stay on the same version. The behavior I would (eventually) expect is:

- Coder auto stops workspace with existing version
- During auto start, Coder attempts to use new version 
- If there are new parameters, a developer will be notified when they SSH, visit via VS Code, or on the dashboard that they need to set new values for the workspace to start. 
- A template admin can disable auto-updating and also allow developers to switch to any version of a template they'd like.

Seems like this would require significant rework though, so let's revert the auto-update for now.

**Comment by mtojek** [comment] 2023-04-17 08:27
I guess that I can close it now.

**Closed by mtojek** 2023-04-17 08:27 UTC
