### ISSUE TITLE
git authentications needs refresh of create workspace page

### ISSUE THREAD

**Issue by z3ky** [coder/coder#9423] opened 2023-08-30 09:29 UTC
After a successful git authentication I have to reload the "New Workspace" page to get the authentication recognized. Without a reload, I still get the message "You must authenticate to create a workspace!".

Coder version 2.1.4

**Comment by matifali** [comment] 2023-08-30 09:40
It looks like a duplicate of #8895. Closing as duplicate. Please leave your comment on the attached issue. Feel free to request reopening if you think it is a new issue.

**Closed by matifali** 2023-08-30 09:40 UTC
Labels: bug
