### ISSUE TITLE
`coder dotfiles` leaves a `.git` folder in home

### ISSUE THREAD

**Issue by ammario** [coder/coder#8012] opened 2023-06-13 18:37 UTC
Relaying a bug complaint from Slack.

A user reported that executing `coder dotfiles` (no flags, in home directory) installs correctly, but leaves a `.git` folder.

**Comment by bpmct** [comment] 2023-08-25 03:43
Closing as duplicate of #8306.

**Closed by bpmct** 2023-08-25 03:43 UTC
Labels: s2, bug
