### ISSUE TITLE
bug(cli): CLI throws an error when using `coder login` without an URL

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#11003] opened 2023-12-02 18:58 UTC
When running `coder login` a not-so-friendly error is thrown to the user.
It would be nice if it said something like "Please provide a valid URL" or something similar, or even a prompt.

Otherwise, I also think the CLI could remember the last instance URL and prompt you asking if you want to use it again or not.

---

```ps
PS C:\Users\Phorcys> coder login
build info: Get "https:///api/v2/buildinfo": http: no Host in request URL
Encountered an error running "coder login"
Failed to check server "https:" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user: Get "https:///api/v2/users/first": http: no Host in request URLx
```

---

`Coder v2.4.0+d19a762`

---

cc: @matifali

**Comment by matifali** [comment] 2023-12-03 04:57
Closing as a duplicate of #10925

**Closed** 2023-12-08 19:44 UTC
Labels: s3, bug
