### ISSUE TITLE
All Terminals Disconnect On Single Close

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#8772] opened 2023-07-27 16:25 UTC
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

# Problems

1. When you have multiple terminals open for a given workspace (and/or `coder_app`s that run a command) and you close one of them, they all show the disconnected screen (photos below)
2. The disconnect screen says "Press any key to retry" but the only valid keys (at least on macOS) seem to be `control`, `option`, `command`, `space bar`, and `shift`.

# Example

Various terminals open
![Screenshot 2023-07-27 at 9 18 01 AM](https://github.com/coder/coder/assets/52972357/2b0cd44d-0b1a-49ac-89d8-3950226a7bd5)

After closing one terminal
![Screenshot 2023-07-27 at 9 21 59 AM](https://github.com/coder/coder/assets/52972357/8083125f-1c9b-4416-91a7-b7cad917abf1)

**Comment by kylecarbs** [comment] 2023-07-27 18:47
Oof, this is a weird bug. We'll definitely fix it.

**Comment by spettinichi** [comment] 2023-08-01 18:35
Came here to mention the "any key" confuses people, we had to start telling people to hit space, so thank you for identifying more keys which work! This also explains some weirdness we've seen with terminals timing out seemingly too quickly.

**Comment by spettinichi** [comment] 2023-08-01 19:18
Spoke with someone else and same issues on Windows. The working keys seem to be space, shift, alt, ctrl, and the windows key.

**Comment by matifali** [comment] 2023-08-02 06:08
@spettinichi you are right I can reproduce it on Windows. Part 2 of the OP is a duplicate of #8547

**Comment by kconley-sq** [comment] 2023-08-02 23:40
I encountered into this issue too on v0.27.3 and noticed that in addition to affecting other web terminals, if you close a web terminal while having some other workspace application open then it also seems to interfere with that application.

For example, the window for Android Studio via JetBrains Projector shows the following for a few seconds after you close a web terminal window:

<img width="658" alt="image" src="https://github.com/coder/coder/assets/93007527/6063c872-d3fb-4b75-b2a2-8b4bf898c0fa">

After a few seconds, the workspace application stops showing that connection message and goes back to normal.

**Comment by bpmct** [comment] 2023-08-04 15:41
We're able to reproduce this consistently on some of our clients and are investigating!

**Closed** 2023-08-04 22:54 UTC
Labels: p1, bug
