### ISSUE TITLE
Default onboarding flow navigates user to a failure scenario

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3869] opened 2022-09-05 05:44 UTC
# overview

I've installed the CLI and running it displays the following:

>   - Get started by creating a template from an example:                         
>
>      $ coder templates init 

Which I did and selected the `docker-with-dotfiles` template.

When the template was created it displayed the following:

> Extracting  docker-with-dotfiles  to ./docker-with-dotfiles...
> Create your template by running:
>                                                            
>   cd ./docker-with-dotfiles && coder templates create      

Which I then executed as follows:

```
ghuntley /home/demo (main) $ cd docker-with-dotfiles/

ghuntley /home/demo/docker-with-dotfiles (main) $ ls
main.tf  README.md

```

Which then failed because I'm not logged in

```
ghuntley /home/demo/docker-with-dotfiles (main) $ coder templates create
You are not logged in. Try logging in using 'coder login <url>'.
Run 'coder templates create --help' for usage.                  

ghuntley /home/demo/docker-with-dotfiles (main) $ coder login
accepts 1 arg(s), received 0       
Run 'coder login --help' for usage.

ghuntley /home/demo/docker-with-dotfiles (main) $ coder login --help
Authenticate with a Coder deployment

Usage:
  coder login <url> [flags]

Flags:
  -e, --email string      Specifies an email address to authenticate with.
                          Consumes $CODER_EMAIL
  -h, --help              help for login
  -p, --password string   Specifies a password to authenticate with.
                          Consumes $CODER_PASSWORD
  -u, --username string   Specifies a username to authenticate with.
                          Consumes $CODER_USERNAME

Global Flags:
      --global-config coder   Specify the path to the global coder config directory.
                              Consumes $CODER_CONFIG_DIR (default "/home/ghuntley/.config/coderv2")
      --no-feature-warning    Suppress warnings about unlicensed features.
                              Consumes $CODER_NO_FEATURE_WARNING
      --no-version-warning    Suppress warning when client and server versions do not match.
                              Consumes $CODER_NO_VERSION_WARNING
      --token string          Specify an authentication token. For security reasons setting
                              CODER_SESSION_TOKEN is preferred.
                              Consumes $CODER_SESSION_TOKEN
      --url string            Specify the URL to your deployment.
  -v, --verbose               Enable verbose output.
                              Consumes $CODER_VERBOSE
```

# thoughts

The instructions at this step could be specialised depending if the user is logged in or not.

> Create your template by running:
>                                                            
>   cd ./docker-with-dotfiles && coder templates create

**Comment by bpmct** [comment] 2022-10-25 17:27
Closing as duplicate of #4201

**Closed by bpmct** 2022-10-25 17:27 UTC
