### ISSUE TITLE
Automatically log me in to my Coder instance from my workspace

### ISSUE THREAD

**Issue by ketang** [coder/coder#2787] opened 2022-07-01 18:48 UTC
If the first command I run in a new workspace is `coder templates list`, it should Just Work.  I shouldn't have to log in to the Coder instance; we already know I'm logged in, and we know to which Coder instance.

**Comment by bpmct** [comment] 2022-07-22 13:03
Closing as duplicate of #2840. While posted later, that issue has more engagement and is in the roadmap.

**Closed by bpmct** 2022-07-22 13:03 UTC
