### ISSUE TITLE
test flake: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY

### ISSUE THREAD

**Issue by matifali** [coder/coder#9422] opened 2023-08-30 09:24 UTC
Seen in https://github.com/coder/coder/actions/runs/6006900082/job/16292158168#step:5:674

**Comment by sreya** [comment] 2023-09-19 21:26
I'm pretty sure this was fixed by https://github.com/coder/coder/pull/9765 I can't reproduce it on main anymore. Tried running `go test -v -failfast -timeout=30m -count=10000 -race -run TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY/OK`

**Closed by sreya** 2023-09-19 21:26 UTC
Labels: flake, bug, s4
