### ISSUE TITLE
Ports fall off the edge of the screen

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#8679] opened 2023-07-23 19:44 UTC
Noticed a formatting bug that makes it difficult to view the port forward screen.

![Screenshot 2023-07-23 at 1 32 46 PM](https://github.com/coder/coder/assets/126726750/686652a4-c5dd-4802-b590-89559989da8a)

Notice that after 6162 it goes "5..." and we don't know what it is.

**Comment by matifali** [comment] 2023-07-24 04:29
closing as a duplicate of #8281

**Closed by matifali** 2023-07-24 04:29 UTC
Labels: bug
