### ISSUE TITLE
Issue Deleting Abandoned Workspaces

### ISSUE THREAD

**Issue by baxters-ctc** [coder/coder#7872] opened 2023-06-06 14:06 UTC
In the process of moving from local users to OIDC, I ended up deleting and recreating a user.  There were still workspaces attached to the user and I can't find a way to delete them.

When I access the workspace from the main Workspaces section in the UI I get this message - 
"user" must be an existing uuid or username.

None of the typical UI items are visible including the delete button.

I tried recreating the username as a local user and now when I try to load the workspace it just redirects me back to the main Workspaces tab.  

Is there any way to force delete these workspaces without going through the UI?

**Comment by MrPeacockNLB** [comment] 2023-06-06 15:38
Did you try **coder delete**?

```bash
coder delete --orphan true -y WORKSPACE
```

**Comment by baxters-ctc** [comment] 2023-06-06 18:37
@MrPeacockNLB Sorry I didn't catch that in the docs earlier.  I tried running this and got an unexpected output - 

```
coder delete --orphan true -y 2nd-test
wanted 1 args but got 2 [true 2nd-test]
```

```
coder delete --orphan true -y test-afs
wanted 1 args but got 2 [true test-afs]
```

If I run without the workspace arg it prompts but doesn't tell me what it's going to delete - 
```
coder delete --orphan true 
> Confirm delete workspace? (yes/no) no
```

Any suggestions on how to proceed?

**Comment by ammario** [comment] 2023-06-06 22:02
@baxters-ctc

`--orphan` by itself is all you need, so `coder delete --orphan test-afs`. The CLI doesn't know whether `true` is for the boolean flag or the name of the workspace.

**Comment by baxters-ctc** [comment] 2023-06-06 23:44
@ammario Thanks for clarifying.  I'm now running into a slightly different error .  If I use just the workspace name, I get a "Resource not found or you do not have access to this resource - 

```
coder delete --orphan -y 2nd-test
Resource not found or you do not have access to this resource
```

I'm a full admin on the coder instance so I expect I would have access.  When I try to give the fully qualified username/workspace I get a different error that seems similar to what's shown the UI - 

```
coder delete --orphan -y admin-somayira/2nd-test
"user" must be an existing uuid or username.
```

I was able to delete another workspace from that user's new OIDC account using the same fully qualified username/password format.

coder delete --orphan aldensomayire/terraform-upload
> Confirm delete workspace? (yes/no) yes
✔ Queued [564ms]
✔ Setting up [28ms]
✔ Planning infrastructure [21ms]
⧗  Destroying workspace 
  The terraform state does not exist, there is nothing to do
✔ Destroying workspace [48ms]
✔ Cleaning Up [38ms]

The terraform-upload workspace has been deleted at Jun  6 23:43:06!

Any ideas why it doesn't work for the orphan case?

**Comment by ammario** [comment] 2023-06-09 17:00
Since this issues appears related to auth perhaps @Emyrk can assist.

**Comment by Emyrk** [comment] 2023-06-12 23:28
Looks like it :thinking: 

Looking into it

**Comment by Emyrk** [comment] 2023-06-13 00:14
# Solution

@atnomoverflow I think this solution will work for you.

```
coder delete --orphan -y <deleted_user_id>2nd-test
```

## Explanation

When you run `coder delete --orphan -y 2nd-test`, the cli assumes you own the workspace and tries `<your_username>/2nd-test`. 

To delete the correct workspace, you need to specify it with:
- `<deleted_user_id>/2nd-test`

You **must use the deleted user's ID** and not their **username**. This is because when a user is deleted, we no longer guarantee their username to be unique. So it can conflict with an active or other deleted users.

-----

Below this line is just an explanation for any future readers or those who are curious.

# The abandoned workspace state

Being able to delete a user who has workspaces **should not be allowed**. We have a check to prevent deleting a user if the user has workspaces: https://github.com/coder/coder/blob/f13632cea86b4af2fd60a135186ae1f96baee680/coderd/users.go#L433-L438

So there might be a bug or avenue that allowed this to happen.

# How to reproduce

I can force this state in a [unit test](https://github.com/coder/coder/blob/14b2d35834c261e7f3d73c5660051a579c957147/cli/delete_test.go#L75-L122) by bypassing the check. I get the same error when trying to delete the deleted user's workspace:

```
unexpected status code 400: \"user\" must be an existing uuid or username."
```

I am running from an admin authenticated cli
```
coder delete <deleted_username>/<workspace_name> -y --orphan
```

To make the test pass, you must do:

```
coder delete <deleted_user_id>/<workspace_name> -y --orphan
```

# What is happening

What is happening is that this line in the cli that fetches the workspace:

https://github.com/coder/coder/blob/ac605bad3d30377a4120c8128a5b1f713e683104/cli/delete.go#L34-L34

Hits this route: https://github.com/coder/coder/blob/ac605bad3d30377a4120c8128a5b1f713e683104/coderd/workspaces.go#L216-L216

Which uses this middleware: 

https://github.com/coder/coder/blob/ac605bad3d30377a4120c8128a5b1f713e683104/coderd/httpmw/userparam.go#L38-L38

We currently **do not allow** this middleware to return deleted users by **username**. This is because a deleted user does not guarantee a unique username. So the username could refer to any number of deleted users, or conflict with an active user.

**Comment by baxters-ctc** [comment] 2023-06-13 22:27
@Emyrk Is there a way for me to find out what that value of "deleted_user_id" is?

**Comment by Emyrk** [comment] 2023-06-14 14:26
> @Emyrk Is there a way for me to find out what that value of "deleted_user_id" is?

Great question. Right now the `/users` endpoint excludes deleted users: https://github.com/coder/coder/blob/ba42c1787b45b29a3346ea2c7e57aba232369764/coderd/database/queries/users.sql#L139-L139

We might want to make that an option :thinking:. I don't think there is a way to get the user_id except from maybe audit logs.

@bpmct Is there any reason to prevent being able to query for deleted users?

**Comment by matifali** [comment] 2023-06-15 13:16
Should we add a new category to the user state?
We currently have `active` and `suspended`; we can add `deleted` and show their user-id instead of username.
This should be listed then in the "Users" tab when filtered with the `deleted` filter

**Comment by Emyrk** [comment] 2023-06-15 16:16
@matifali that does prevent adding a new knob

**Comment by Emyrk** [comment] 2023-06-21 15:53
After doing some work on this, I think we should leave the code how it is and not add any functionality regarding this issue.

First: This edge case should not happen, so it should be rare.

Second: It can be resolved, as mentioned above (https://github.com/coder/coder/issues/7872#issuecomment-1588279340)

Third: Deleted user IDs can be found via database directly, audit logs, or through the resource itself (https://github.com/coder/coder/issues/7872#issuecomment-1601091455)

----

The code solution to this would be to add the ability to list deleted users. However I think listing deleted users gets into privacy/security questions around who should be able to see all deleted users. 

Since there exists work arounds for this edge case, I am going to close this issue.

If the problem still exists, or the mentioned workarounds do not work, **anyone** can feel free to reopen this PR with additional information.

**Closed by Emyrk** 2023-06-21 15:53 UTC
Labels: p2, bug
