### ISSUE TITLE
Sharing a workspace between developers

### ISSUE THREAD

**Issue by arel** [coder/coder#12696] opened 2024-03-20 20:25 UTC
I need a streamlined method to allow other developers access to specific workspaces. As an "Owner," I have full access to all workspaces in our organization, including the ability to log in. I'm seeking a way to extend similar access to non-owner members.

Potential solutions I'm considering:

* Introduce a "Workspace Admin" role that grants access to all workspaces without "Owner" or "Template Admin" privileges.
* Implement a workspace-sharing feature that allows specifying users or groups for access.
* Create an option for workspaces to be accessible over SSH to all users.

I am looking for guidance or existing solutions to achieve this.

**Comment by matifali** [comment] 2024-03-20 22:52
Duplicate of #2425

**Comment by matifali** [comment] 2024-03-20 22:55
Upvote the attached issue and leave your feedback there. Thank you!

**Closed by matifali** 2024-03-20 22:55 UTC
Labels: feature
