### ISSUE TITLE
Jupyterlab's responses "400 Bad Request" in version 2.6.0

### ISSUE THREAD

**Issue by madhosoi** [coder/coder#11672] opened 2024-01-17 16:56 UTC
After upgrade of Coder OSS to version 2.6.0, we are experiencing these errors accessing to any feature related to websockets (I suppose) of jupyterlab instantiated in a given template running on Kubernetes:

![image](https://github.com/coder/coder/assets/5636474/bdadfcbd-8cc8-41d6-a938-214129bdeac0)

With previous version, it is running as expected.

I have this setup:
```
/opt/miniconda/bin/python3.11 /opt/miniconda/bin/jupyter-lab --no-browser --ServerApp.password= 
--ServerApp.token= --JupyterApp.config_file=~/.jupyter/jupyter_notebook_config.py 
--ServerApp.port=8888 --ServerApp.base_url=@<user>/<workspace>.main/apps/jupyter --ip='*'
```

```
# jupyter
resource "coder_app" "jupyter" {
  count        = local.jupyter-count
  agent_id     = coder_agent.main.id
  display_name = "Jupyter Lab"
  slug         = "jupyter"
  icon         = "/icon/jupyter.svg"
  url          = "http://localhost:8888/@${lower(data.coder_workspace.me.owner)}/${lower(data.coder_workspace.me.name)}.main/apps/jupyter/"
  subdomain    = false
  share        = "owner"
}
```
I cannot see any clue in the logs of coder, of the proper workspace's container neither in the jupyterlab logs (running it manually to get them).

Could you help me to understand the error?
If you need more info, just ask me.
Thanks 

Miguel

**Comment by ericpaulsen** [comment] 2024-01-17 19:32
thank you for reporting @madhosoi - here is another issue that is likely related: https://github.com/coder/coder/issues/11406

we have a fixed merged against this issue: https://github.com/coder/coder/pull/11656

**Comment by madhosoi** [comment] 2024-01-17 20:06
Thanks for letting me know.
Do you know when it will be released to test it?

**Comment by matifali** [comment] 2024-01-17 22:22
@madhosoi we plan to cut a release by end of week. 
Closing this as duplicate of #11406 
Please request to reopen if it's not solved with the new release.

**Closed by matifali** 2024-01-17 22:22 UTC
Labels: bug, need-help

**Comment by madhosoi** [comment] 2024-01-18 09:24
Thanks for confirming @ericpaulsen & @matifali !

**Comment by madhosoi** [comment] 2024-01-20 07:35
Hi,
After upgrade to version 2.7.0 (also tested with coder-preview:latest), this error is fixed.
But, now, when I have 2 workspaces that has jupyterlab, it seems the traffic of services is not redirecting properly, e.g:
![image](https://github.com/coder/coder/assets/5636474/2ead0d39-b910-474b-8d3b-51618f9fdd21)

The behaviour is weird, the first jupyter I open, is open perfectly. The second is opeing the content of the first one:
![image](https://github.com/coder/coder/assets/5636474/7e2a599c-e2c6-43f8-9a36-29fdf9543f4c)

If you need me to open a new one, of course I can do it.

Thanks!

**Comment by matifali** [comment] 2024-01-20 07:41
Yes please move it to a new issue.
