### ISSUE TITLE
No way to disable auto start schedule in UI

### ISSUE THREAD

**Issue by ammario** [coder/coder#2960] opened 2022-07-13 01:22 UTC
## Problem

As title says... I tried deselecting all the days but it didn't work. I've heard of some method to disable it from the UI but it's obviously not clear and the UI makes it seem as though it's impossible to disable. 

You have to uncheck all the schedule items to make this schedule manual. At one point we were also seeing errors in the backend when disabling this. 

This seems like a serious bug for cost control @tjcran 

## Definition of Done
A user should be able to quickly and obviously disable auto-start in the UI otherwise they may end up incurring infrastructure costs unintentionally.

**Comment by ammario** [comment] 2022-07-13 01:23
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/7416144/178628285-e3443025-26f0-44ff-99ab-322b6af25fb0.png">

I can't even set it to one day a week for some reason.

**Comment by ammario** [comment] 2022-07-13 01:24
<img width="1855" alt="Screen Shot 2022-07-12 at 8 23 38 PM" src="https://user-images.githubusercontent.com/7416144/178628370-4a063836-1809-4b5a-9856-24ac16571410.png">

Actually any edit to this workspaces' (on the `coder` template) schedule fails. 🤦🏽‍♂️

**Comment by ammario** [comment] 2022-07-13 01:27
Note that the schedule disable bug applies to all workspaces, but the schedule edit bug just applies to our `coder` template. They're likely related.

**Comment by spikecurtis** [comment] 2022-07-21 21:34
Related:
#3051 
#2792

**Comment by misskniss** [comment] 2022-07-26 15:25
Closing this for this issue: https://github.com/coder/coder/issues/3051

**Comment by johnstcn** [comment] 2022-07-26 15:25
Root cause: the workspace template has a `max_ttl` of `12h` set.
We do not allow setting the workspace TTL higher than the template TTL. 
The problem is, the error message from the backend is not being surfaced properly in the UI.
The workspace schedule form should have a validation on the template max_ttl value.

**Closed** 2022-07-26 15:25 UTC
Labels: bug, frontend

**Comment by johnstcn** [comment] 2022-07-26 15:34
Opened https://github.com/coder/coder/issues/3216 for the validation issue.
