### ISSUE TITLE
Consistent ordering of parameters in Create/Update workspace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6671] opened 2023-03-20 12:26 UTC
Version: [`v0.19.2+7eb2c2f`](https://github.com/coder/coder/commit/7eb2c2ff6d229619f88f41e9b2b185714a967619)

Coder's ideal customer profile deploy Coder at scale (100s-1000s of developers).

Training and procedures are documented and need to be consistent at every encounter and use of the Coder product.

Today, creation or update of a workspace displays parameters in arbitrary order (or at least not the order in the template main.tf)

Add a sort order or something consistent.

I think there is a duplicate of this issue but wanted to file it separately so it is not lost.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2022166/226338396-73301c1e-28bb-45bc-a2ca-15af71532bba.png">

**Comment by bpmct** [comment] 2023-03-20 19:06
Closing as duplicate of #6362. Marcin is working on it this week :)

**Closed by bpmct** 2023-03-20 19:06 UTC
