### ISSUE TITLE
Workspace with 32 characters fails in route setup

### ISSUE THREAD

**Issue by pi3ch** [coder/coder#9332] opened 2023-08-25 09:44 UTC
Using wildcard URL, if a workspace name is 32 characters (the maximum allowed), access to code-server is 404.

There seems to be a routing problem when maximum allowed chars are used.

Steps to reproduce:
. Make sure wildcard URL is used
. Create a workspace with 32 characters, e.g. 3584193c95d7022aafcdd2fca8811f0d
. Try to open code-server.
. Observe 404

**Comment by matifali** [comment] 2023-08-25 10:07
Closing as a duplicate of #8145
Please leave your comments there.

**Closed by matifali** 2023-08-25 10:07 UTC
Labels: bug
