### ISSUE TITLE
parameter value must be equal or greater than previous value

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#8123] opened 2023-06-21 11:32 UTC
Coder ~v0.20.0~ v0.24.0

I have a template with this parameter:

```
data "coder_parameter" "home_disk_size" {
  name                 = "Home Volume Size (Gb)"
  type                 = "number"
  description          = "How large would you like your home volume to be (in GB)?"
  mutable              = true
  default              = "64"
  legacy_variable_name = "home_disk_size"
  legacy_variable      = var.home_disk_size
  validation {
    min       = 64
    max       = 2048
    monotonic = "increasing"
  }
}
```

When I try to update a workspace that was using 64 previously and set it to a higher value I get an unexpected error.

```
> coder update dev --always-prompt

  This template has customizable parameters. Values can be
  changed after create, but may have unintended side effects
  (like data loss).

Container Image
  Which container image would you like to use?

  >  Ubuntu 20
Dotfiles
  Do you have a Gitlab repository with an install script?

> Enter a value (default: "git@gitlab.com:me/coder-dotfiles.git"):
Home Volume Size (Gb)
  How large would you like your home volume to be (in GB)?

> Enter a value (default: "64"): 1024
Workspace Profile
  The type of workspace to create. Note that you can change this later, but only to a profile that gets created in the same Kubenetes cluster.

  >  GPU

Planning workspace...
✔ Queued [911ms]
✔ Running [30ms]
✔ Setting up [9421ms]
✔ Detecting persistent resources [6573ms]
✔ Cleaning Up [140ms]
┌───────────────────────────────────────────────────────────────────────┐
│ Workspace Preview                                                     │
├───────────────────────────────────────────────────────────────────────┤
│ RESOURCE                                 ACCESS                       │
├───────────────────────────────────────────────────────────────────────┤
│ kubernetes_persistent_volume_claim.home                               │
├───────────────────────────────────────────────────────────────────────┤
│ kubernetes_pod.main                                                   │
├───────────────────────────────────────────────────────────────────────┤
│ kubernetes_secret.main                                                │
│ └─ main (linux, amd64)                    coder ssh dev               │
├───────────────────────────────────────────────────────────────────────┤
│ time_rotating.token_expiry                                            │
├───────────────────────────────────────────────────────────────────────┤
│ time_static.current                                                   │
└───────────────────────────────────────────────────────────────────────┘
parameter value must be equal or greater than previous value: 64
```

Clearly 1024 is greater than 64 though.

**Comment by mtojek** [comment] 2023-06-21 11:46
What I can see here is that your deployment is pretty old (v0.20.0). I checked against the latest main branch and it works correctly:

```tf
data "coder_parameter" "compute_instances" {
  name        = "Compute instances"
  icon        = "/icon/rubymine.svg"
  type        = "number"
  description = "Let's set the expected number of instances."
  default     = "3"
  mutable     = true
  validation {
    min       = 2
    max       = 5
    monotonic = "increasing"
  }
}
```

I'm using coder provider v0.8.2. Maybe you're using the older version too?

BTW. As far as I can see that you're in the middle of migration (`legacy_variable` and `legacy_variable_name`). Why are you trying to change workspace parameter values at that time? It is recommended to migrate templates first - here is the [guide](https://coder.com/docs/v2/latest/templates/parameters#steps). I suggest you jump to v0.23.7, then finish migrating templates, and upgrade to v0.24.1.

**Comment by NiklasRosenstein** [comment] 2023-06-21 12:40
Sorry, I mistyped the version number. 🙈 We're actually on 0.24.0 (latest minor version). And the Coder provider it's using is 0.8.2 as well.

The same error occurs in the UI by the way, and is then not surfaced properly to the user so they're left wondering if the update did anything (especially unexperienced users who don't know what should be happening after an update).

> BTW. As far as I can see that you're in the middle of migration (legacy_variable and legacy_variable_name). Why are you trying to change workspace parameter values at that time? It is recommended to migrate templates first - here is the [guide](https://coder.com/docs/v2/latest/templates/parameters#steps). I suggest you jump to v0.23.7, then finish migrating templates, and upgrade to v0.24.1.

The workspace I'm using doesn't have any legacy parameters any more, it was already updated once to use the template that uses Rich parameter values.

> It is recommended to migrate templates first

Do you mean to say it is recommended to upgrade Workspaces to a template that has the migration logic in it first, and tell users not to update any parameters until there's _another_ template version that doesn't have the migration logic in it? 😕

**Comment by mtojek** [comment] 2023-06-21 14:06
> Sorry, I mistyped the version number. 🙈 We're actually on 0.24.0 (latest minor version). And the Coder provider it's using is 0.8.2 as well.

I checked one more time v0.24.1 + v0.8.2, and couldn't reproduce it. Could you try to create a new template without reference to legacy variables and see if the issue happens there too? Legacy variables are not supported in v0.24.0+ anymore.

> The same error occurs in the UI by the way, and is then not surfaced properly to the user so they're left wondering if the update did anything (especially unexperienced users who don't know what should be happening after an update).

https://github.com/coder/coder/issues/8124

> As in like this?

Yes

>  there's no previous state on the legacy variable values, so the coder_parameters will behave as if there is nothing to migrate

In theory, they should be fine, but the assumption is to use "Migration Template" only for migration purposes. Nothing stops you from pushing the "New Template" right after, so new workspaces are not tainted with legacy parameters. This flow assumes that DevOps or template admins can help users migrate out from the "Old template".

Anyway, with v0.24.0 you should not have any templates using `legacy_variable`s, as users will not be able to migrate them smoothly. The migration flow is supported until v0.24.0 as stated [here](https://coder.com/docs/v2/latest/templates/parameters#migration).

**Comment by sthdev** [comment] 2023-07-12 18:09
Hi,

I have also encountered this problem with Coder 0.26.0. It never happens when the parameter value is changed for the first time, but it happens eventually when the parameter value is increased multiple times (i.e. increase parameter value, rebuild workspace, increase parameter value, rebuild workspace, etc.). Sometimes it happens already when the parameter is increased for third time, sometimes it takes seven or more times. I am using the web UI to change the parameter and the parameter controls the workspace volume's size.

The Coder backend does not log any useful information apart from the fact that it returned HTTP 400. The browser console shows the following stack trace:
```
POST https://coder.domain.com/api/v2/workspaces/69c97ccd-de26-4ab4-8075-0140dd91e5e9/builds 400
(anonymous)	@	index-db410224.js:95
xhr	@	index-db410224.js:95
Ck	@	index-db410224.js:95
request	@	index-db410224.js:95
(anonymous)	@	index-db410224.js:95
(anonymous)	@	index-db410224.js:93
Gd	@	index-db410224.js:95
mutationFn	@	WorkspaceParametersPage-fd9daf77.js:1
fn	@	index-db410224.js:77
m	@	index-db410224.js:77
q4	@	index-db410224.js:77
t	@	index-db410224.js:77
execute	@	index-db410224.js:77
await in execute (async)		
mutate	@	index-db410224.js:77
(anonymous)	@	index-db410224.js:85
(anonymous)	@	index-db410224.js:296
(anonymous)	@	index-db410224.js:296
(anonymous)	@	index-db410224.js:296
Promise.then (async)		
(anonymous)	@	index-db410224.js:296
(anonymous)	@	index-db410224.js:296
(anonymous)	@	index-db410224.js:296
(anonymous)	@	index-db410224.js:296
BM	@	index-db410224.js:53
VM	@	index-db410224.js:53
HM	@	index-db410224.js:53
eE	@	index-db410224.js:53
Kj	@	index-db410224.js:53
(anonymous)	@	index-db410224.js:53
jb	@	index-db410224.js:56
yj	@	index-db410224.js:53
Mv	@	index-db410224.js:53
ib	@	index-db410224.js:53
aD	@	index-db410224.js:53
```

I have restarted the Coder and the PostgresQL pods to rule out caching problems but the error persists. Stopping and restarting the workspace, or deploying a new version of the workspace also does not help. I have not found a workaround so far apart from deleting the workspace and creating a new one.

I am using Coder 0.26.0 with the Bitnami PostgresQL (docker.io/bitnami/postgresql:15.3.0-debian-11-r7).

By the way, I have only encountered this problem with a parameter that has the `monotonic` property. Changing the values of  parameters with only `min` and `max` works as often as I tested it (at least ten times).

**Comment by mtojek** [comment] 2023-07-12 18:18
This issue could be fixed with the recent PR: https://github.com/coder/coder/pull/8436

**Comment by sthdev** [comment] 2023-07-12 18:21
I just noticed that Coder 0.26.1 was released some moments ago. I'm testing it right now.

**Comment by sthdev** [comment] 2023-07-12 18:25
Yes, the issue is fixed. Thank you!

**Closed** 2023-07-12 18:26 UTC
Labels: waiting-for-info, bug
