### ISSUE TITLE
Git auth to create a workspace forces page refresh losing all fields

### ISSUE THREAD

**Issue by Shocktrooper** [coder/coder#9536] opened 2023-09-05 18:44 UTC
Problem:
- When a user is creating a workspace with a template that requires git auth to some external provider a user is forced to refresh the page for the auth to take effect which removes all entries in other fields when creating the workspace.  This is a problem because it is not apparent that all fields will be reset leading to end user frustration. 

Solutions:
1. (Preferred) Turn git auth buttons and settings into a websocket or something that is updated dynamically as soon as the end user completes the git auth which will negate the need for a full page refresh.
2. Enforce git auth on a separate page or first before other fields are filled which negates the removal of selections and filled fields
3. More I didn't list

**Comment by BrunoQuaresma** [comment] 2023-09-05 19:24
@Shocktrooper thanks for letting us know and suggesting possible solutions.

I think we could save them in local storage and clear them when the form is submitted.

**Comment by matifali** [comment] 2023-09-05 21:42
This is a duplicate of #9423 and

**Comment by Emyrk** [comment] 2023-09-06 13:45
@BrunoQuaresma as a stop gap, could we just put a "refresh" button on the "Authenticate with Github" button?

At present, clicking the button opens a new page for auth, and there is no easy way to push that info to the original page that the user is now authenticated.

Maybe clicking the button should start some poll loop :thinking:

**Comment by BrunoQuaresma** [comment] 2023-09-06 14:22
@Emyrk I think this is more complex than just saving the current form state in the local storage

**Comment by BrunoQuaresma** [comment] 2023-09-06 14:31
Ahhh ok, I see. I was confused... I thought the redirect was happening on the same page and not on a different tab. In this case, we may need something like you said.

**Comment by Emyrk** [comment] 2023-09-06 14:34
No, the user gets opened a new window, does the auth flow. Then they have to manually go to the old window where the same "Authenticate" button is still clickable. 

They refresh their form, and it works.

I think it would be easy to just poll for say 5min after they click the :"authenticate" button or something to wait until they finish the flow on the other page.

**Closed** 2023-09-26 17:39 UTC
Labels: site, s2, bug, good-first-issue
