### ISSUE TITLE
Autostop keeps refreshing even though workspace is not used

### ISSUE THREAD

**Issue by GilQedma** [coder/coder#12012] opened 2024-02-05 10:44 UTC
Hey, using coder v2.7.2+a82a8c7 on EKS.

My workspace keeps bumping `autostop` (it always stays around 57-60 minutes to shutdown)
<img width="618" alt="image" src="https://github.com/coder/coder/assets/110019385/ee15aeaf-d4b2-4398-9a18-8a0bdee12c42">
1. I checked the admin toolbar, to consult the "Active Connections" - it says zero connections.
2. I talked with the owner of the Workspace, and it is indeed was not used during these times (when used, he usually uses VSCode extension)

What could be the cause for that?

**Comment by stirby** [comment] 2024-02-05 18:44
I'm going to work on reproducing this. What is the Autostop configuration on the workspace?

**Comment by GilQedma** [comment] 2024-02-12 09:21
Thanks! Here it is -
<img width="1069" alt="image" src="https://github.com/coder/coder/assets/110019385/99df2920-e220-45d5-b2f6-47760903dd5f">

**Comment by johnstcn** [comment] 2024-02-23 21:04
I noticed this just now on my own workspace. I have autostop enabled with an aggressive TTL of 1 hour. From checking coderd logs matching `msg:"read stats report" workspace_id:<workspace_id>` I noticed that opening or loading the workspace page appears to trigger something that causes workspace stats to be posted with a non-zero connection count. I'm not sure exactly what is causing it yet, my best guess so far is the "Open Ports" indicator but it's not a given just yet.

**Comment by johnstcn** [comment] 2024-02-26 15:23
@GilQedma is it possible the developer had done one of the following:
* Left a port-forward open to the workspace
* Left a persistent connection open to an application running inside the workspace besides VSCode?

Both of these actions will be counted as 'active usage' and will trigger the activity bump, but won't show up in the admin toolbar.

**Comment by GilQedma** [comment] 2024-03-03 09:01
@johnstcn could certainly be! I'll check it out.
The developer uses VSCode terminal, and also tmux, so could be.

**Comment by GilQedma** [comment] 2024-03-07 15:05
I talked to the developer @johnstcn, he isn't aware of any port-forward left open, or a persistent connection as such.
This actually happened while he wasn't working on his laptop.

However, he said that the auto-refresh issue didn't happen to him for some time now (still v2.7.2)... so perhaps we should put this on hold until it happens again. Thanks for the help!

**Comment by stirby** [comment] 2024-04-26 14:42
@f0ssel closing for now since the issue seems to be resolved. I'm sure fixes will be cemented in the upcoming workspace activity changes.

**Closed by stirby** 2024-04-26 14:42 UTC
Labels: waiting-for-info, s2, bug
