### ISSUE TITLE
Add enterprise badge to dashboard

### ISSUE THREAD

**Issue by stirby** [coder/coder#11730] opened 2024-01-21 19:12 UTC
Our docs have an "Enterprise" badge for features blocked behind a license. Would be good to mark these the same way in the product.

From the [docs](https://coder.com/docs/v2/latest/workspaces#autostop-requirement-enterprise):

<img width="351" alt="Screenshot 2024-01-21 at 1 07 13 PM" src="https://github.com/coder/coder/assets/58410745/a9c6ce97-460d-49c1-9045-18efe4c4dea7">

**Comment by stirby** [comment] 2024-01-23 21:43
Specifically looking for these on template/workspace settings where `deprecated` and `alpha` exist.

**Comment by matifali** [comment] 2024-01-23 23:59
Duplicate of #9439

**Closed** 2024-02-01 19:32 UTC
Labels: feature, site
