### ISSUE TITLE
Stop failed Coder workspace automatically

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#11670] opened 2024-01-17 14:24 UTC
We deploy a Kubernetes Pod as a Coder workspace. If the Pod fails to be scheduled, it stays in Pending state in Kubernetes while the Coder workspace eventually times out waiting for the Pod to be scheduled. Eventually the Pod gets assigned and uses resources but is not usable because the workspace is in a failed state.

If the Coder workspace would automatically stop after entering the "Failed" state, the stop plan would remove the Pod again. This would be immensely useful to avoid zombie Pods using resources.

**Comment by matifali** [comment] 2024-01-17 20:20
We do have this here: https://coder.com/docs/v2/latest/templates/schedule#allow-users-scheduling

It will be available in next release as an enterprise feature.

**Comment by matifali** [comment] 2024-01-17 20:35
Closing as a duplicate of #5815

**Closed by matifali** 2024-01-17 20:35 UTC
Labels: feature
