### ISSUE TITLE
Updating `Full Name` requires User Admin permission

### ISSUE THREAD

**Issue by wSedlacek** [coder/coder#13694] opened 2024-06-27 18:06 UTC
Coder Version: `2.12.1`
Login Type: GitHub

The `Full Name` field is locked when a user does not have User Admin permissions preventing them from changing their Full Name.
There doesn't appear to be a place for admins to change other user's Full Names after creation. (In a recent PR it seems like there was an option added set a Full Name when creating an account, but existing accounts seem to not have an option)

**Comment by matifali** [comment] 2024-06-27 18:13
Duplicate of #13672 and #13454.

cc: @stirby

**Comment by stirby** [comment] 2024-06-27 20:24
I guess this wasn't resolved by https://github.com/coder/coder/pull/13493? Assuming it was opening permissions to the username, not the full name field. Can we rinse and repeat @BrunoQuaresma?

**Comment by stirby** [comment] 2024-06-27 20:30
This has been fixed and will not occur in v2.13.0 which we'll release next Tuesday (07/02). Thank you for reporting!

**Closed by stirby** 2024-06-27 20:30 UTC
Labels: site, s3, bug
