### ISSUE TITLE
Determine whether a build job will ever complete (is there a matching provisioner)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8247] opened 2023-06-28 13:19 UTC
A workspace may be stuck in a "pending" state in a queue forever in the following cases:

- There are no provisioners
- There are no provisioners that match the tags required for the job (e.g. local provisioner or tagged provisioner)

Let's surface this to the user via the dashboard and CLI. Right now, the user will just see that their workspace is pending or in a queue, but it will never progress.

**Comment by Emyrk** [comment] 2023-08-30 14:06
@sreya Should this be blocked by the provisioner refactor? I ask because currently we store provisioners in the DB, so this should not be tricky to implement. However there was a PR opened to maybe remove it from the DB as a precursor to refactoring the provisioner stuff.

I just do not want to implement ontop of something that will be removed.

**Comment by bpmct** [comment] 2023-08-30 17:32
Fairly sure this is blocked by the provisioner refactor

**Comment by Emyrk** [comment] 2023-08-31 13:49
Removed from the sprint until unblocked

**Comment by matifali** [comment] 2024-02-28 09:05
Related and possible duplicate of #12331. At least we should have a way to delete such workspaces from the coder database. It could be similar to the orphan resources option for failed workspaces.

**Comment by johnstcn** [comment] 2024-03-11 15:19
Needs RFC

**Closed** 2024-03-27 09:19 UTC
Labels: needs-rfc
