### ISSUE TITLE
Can't expand directories in the template editor's file browser

### ISSUE THREAD

**Issue by marcpaq** [coder/coder#11315] opened 2023-12-21 19:59 UTC
Coder version:  v2.5.1+e6e65fd running on Debian Linux. 
Browser: Firefox 121.0

https://github.com/coder/coder/assets/22124737/eccd6caa-1411-4540-8df4-f72bc9659733

**Steps to reproduce:**

1. In Templates, choose a template.
2. Click Source Code tab, look at files in the template.
3. From the drop-down menu, choose Edit files.
4. In the editor's file browser, select a subdirectory to expand it.

**What should happen:** the file browser shows the files in the subdirectory so you can select one of them to edit.

**What happens instead:** the file browser doesn't expand the subdirectory, preventing you from editing files in it.

**Comment by matifali** [comment] 2023-12-21 20:29
This has been fixed in #11260 and is a duplicate of #11252.

**Closed by matifali** 2023-12-21 20:29 UTC
Labels: bug
