### ISSUE TITLE
New workspace UI says `pending` but it is `building`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7028] opened 2023-04-06 12:31 UTC
Version: [`v0.21.3+95e578b`](https://github.com/coder/coder/commit/95e578ba10d4e5fb5eccfb9d0e63d88cc0efea1f)

Sometimes when I create a new workspace in the UI, it redirects to the workspace screen and says `pending` but `kubectl` shows the `container creating` and it is building.

Then the UI updates to be completed and I see the health check for my `codoer_app` which is normal.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/2022166/230379397-3c15c639-7a2a-4081-b971-764ddd3a4995.png">

**Comment by BrunoQuaresma** [comment] 2023-04-17 14:33
I think the BE is returning pending because the provisioner job didn't start yet so it is in a "pending" state, but I agree to show the "building" label would be better but not sure what is the best way.

**Comment by bpmct** [comment] 2023-08-25 03:51
I found a clear way to reproduce this. If you refresh the home page then build a workspace, the first one will be stuck in pending. If you create future workspaces (without refreshing the page in your browser), the pending bug doesn't occur

https://github.com/coder/coder/assets/22407953/f981fa9e-6217-4736-aac1-9b9d7e079a73

**Comment by BrunoQuaresma** [comment] 2023-08-25 12:58
@bpmct in your video, I didn't see it getting stuck on pending 🤔

**Comment by bpmct** [comment] 2023-08-25 16:01
Ugh I probably sent the wrong video, now I can't reproduce 🤦🏼

**Comment by BrunoQuaresma** [comment] 2023-08-28 17:28
Closing in favor of #8566

**Closed by BrunoQuaresma** 2023-08-28 17:28 UTC
Labels: s3, bug
