### ISSUE TITLE
workspace proxies are returned as 'unknown' in the audit logs

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#8833] opened 2023-08-01 13:56 UTC
<img width="1588" alt="Screenshot 2023-08-01 at 9 54 16 AM" src="https://github.com/coder/coder/assets/9683576/8d6f65ce-37e1-43e6-8f09-b6e1e56af340">

**Comment by sharkymark** [comment] 2023-08-01 15:02
@bpmct @ericpaulsen this is a duplicate of the one I entered 2 weeks ago. https://github.com/coder/coder/issues/8531

**Closed** 2023-08-21 15:53 UTC
Labels: s2, must-do, bug
