### ISSUE TITLE
Service Banner doesn't show up until you refresh

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5593] opened 2023-01-05 16:44 UTC
Bug: Until you do your first refresh, the service banner doesn't show up.

Repro:

-Open up an incognito browser and log into a Coder cluster that has a service banner enabled
-The banner won't appear, and if you click around, it won't load
-Do a cmd-R, and the banner will pop up.

**Comment by ammario** [comment] 2023-01-05 21:20
Hmm, I can't replicate this on master.

**Comment by matifali** [comment] 2023-01-06 07:53
It's a duplicate of #5511 and #5504. 
And most probably fixed by #5594

**Closed** 2023-01-10 18:42 UTC
Labels: bug
