### ISSUE TITLE
`Member`-roled user getting server error logging in

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8638] opened 2023-07-20 20:24 UTC
Version: [`v0.26.1+a0fedeb`](https://github.com/coder/coder/commit/a0fedebd624e8ba3b03052c3301876f220d851ef)

I was updating licenses to a Kubernetes deployment, and wanted to  test `Member` users and what they see in the UI when an expiring license.

Not sure if related, but I was able to log in once as this Member, but then failed the next time.

These are the `coderd` logs which I followed with `kubectl` as it occurred.

```
2023-07-20 20:19:24.240 [erro]  coderd.userauth: unable to fetch authorization user roles  request_id=ee3b1ee5-ddbe-4ee4-84e5-b415231ed9fd  error={"Err":{}}
2023-07-20 20:19:24.244 [info]  coderd: audit_log  ID=3bfedce8-f8cd-4296-9916-0fbcb3f26b0c  Time="2023-07-20T20:19:24.241037Z"  UserID=02c65d65-9b75-47b0-9671-b55de8aca56b  OrganizationID=00000000-0000-0000-0000-000000000000  Ip=10.244.0.1/32  UserAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"  ResourceType=api_key  ResourceID=00000000-0000-0000-0000-000000000000  ResourceTarget=""  Action=login  Diff="{}"  StatusCode=500  AdditionalFields="{}"  RequestID=ee3b1ee5-ddbe-4ee4-84e5-b415231ed9fd  ResourceIcon=""
2023-07-20 20:19:24.244 [warn]  coderd: POST  host=example.com  path=/api/v2/users/login  proto=HTTP/1.1  remote_addr=10.244.0.1  took=81.397788ms  status_code=500  latency_ms=81  response_body="{\"message\":\"Internal error.\"}\n"  request_id=ee3b1ee5-ddbe-4ee4-84e5-b415231ed9fd
```

I was then able to log in successfully with the `Owner` role

**Comment by sharkymark** [comment] 2023-07-20 20:26
This just scrolled in logs when I was doing nothing as the owner role

![image](https://github.com/coder/coder/assets/2022166/30b4348c-e232-44f8-9413-652266a5aac1)

**Comment by bpmct** [comment] 2023-08-25 03:31
Thanks for sharing these logs! @Emyrk - any idea why this would happen?

**Comment by Emyrk** [comment] 2023-08-25 16:18
Will take a look

**Comment by Emyrk** [comment] 2023-08-25 16:20
The strange thing is that the error is empty :thinking:

**Comment by Emyrk** [comment] 2023-08-25 20:31
Im am unable to reproduce.

What I tried:

- Made a license that expires in 24 hours.
- Log in as a member with password auth, log out, log in
- Log in as a member with OIDC auth, log out, log in
- Make a new password member user
- Log in, log out, log in as the new user

I never encountered any issues.



----

The log line that is the issue is this one:
```
2023-07-20 20:19:24.240 [erro]  coderd.userauth: unable to fetch authorization user roles  request_id=ee3b1ee5-ddbe-4ee4-84e5-b415231ed9fd  error={"Err":{}}
```

The problem is the `Err` field is empty. Which is strange, as if we are returning an empty error somewhere.

My guess is the top level error struct is [dbauthz.NotAuthorizedError](https://github.com/coder/coder/blob/1de1e3b98ad18f652ee76c4444b2bc423285ed19/coderd/database/dbauthz/dbauthz.go#L34-L34). The inner error is likely [rbac.UnauthorizedError](https://github.com/coder/coder/blob/1de1e3b98ad18f652ee76c4444b2bc423285ed19/coderd/rbac/error.go#L22-L22).

If so, there should be a log that has the message `unauthorized`: https://github.com/coder/coder/blob/1de1e3b98ad18f652ee76c4444b2bc423285ed19/coderd/database/dbauthz/dbauthz.go#L71-L71

Without this log line, it is a bit hard to figure out what is going on. I do not believe it is an rbac error because the `dbauthz.AsSystemRestricted(ctx)` is used, so permission wise we should never get a failure.

It isn't a `context.Cancelled` error as the dbauthz package returns those as `context.Cancelled` error. So it is _probably_ a database error? 

@sharkymark 

The other log lines indicate the same thing is going on. Do we still have this instance up? Is there any way we can verify the database is acting correctly? If it has the proper migrations, if it's reachable, etc?

**Comment by Emyrk** [comment] 2023-08-29 18:30
@sharkymark are you able to reproduce?

**Comment by Emyrk** [comment] 2023-09-05 16:17
I am going to close this. Without supporting logs or the ability to reproduce, there is no more action to be taken.

We can reopen if it resurfaces.

**Closed by Emyrk** 2023-09-05 16:17 UTC
Labels: s2, bug
