### ISSUE TITLE
bug: --build-options matches against human name and not Terraform name

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#10292] opened 2023-10-16 14:48 UTC
Build options in the CLI specified with `--build-options` match against the "Human" name and not the "Terraform" name of the parameter.

For example, let's say you have a template with a parameter:

```
data "coder_parameter" "verbose" {
  type        = "bool"
  name        = "Run Verbosely"
  default     = false
  description = "Show debug output."
}
```

Let's say you try to start a workspace that uses this template, and set `verbose=true`:

```
coder start myworkspace --build-options --build-option 'verbose=true'
```

What you'd expect to happen:

```
# workspace starts with verbose=true
```

What actually happens:

```
Encountered an error running "coder start"
parameter "verbose" is not present in the template
```

`ParameterResolver` checks against the rich parameter "name" and not the Terraform "name".
What you need to do instead is:

```
coder start myworkspace --build-options --build-option 'Run Verbosely=true'
```

This tripped me up for a good while and I didn't find a big warning in the docs about how this works. So this could be treated either as a CLI bug or a documentation bug.

**Comment by mafredri** [comment] 2023-10-16 14:52
I would definitely be in favor of using the non-human readable parameter name. It's much more robust whereas the human readable one may break a lot of automation just because a typo was fixed. The parameter name change requires much more obtrusive changes in a terraform template, which makes it a better candidate.

**Comment by bpmct** [comment] 2023-10-16 15:06
Great find. I think we should break this to fix, let's just flag it and I will call out the change at the top of our changelog

**Comment by matifali** [comment] 2023-10-16 15:17
Actually `name` is not human name. It's a fallback if there is no [`display_name`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#display_name) given.

**Comment by johnstcn** [comment] 2023-10-16 15:29
One non-breaking 'solution' perhaps could be to:
1) List all valid parameters along with the message `parameter %q is not present in the template`
2) (Optional, fancy): As above, but also check with Levenshtein edit distance of up to 3 and display this as a hint e.g. `tip: did you mean: %q ?`

**Comment by mtojek** [comment] 2023-10-17 07:21
> Actually name is not human name. It's a fallback if there is no [display_name](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#display_name) given.
So it's expected behavior. You have to use the name.

Atif is right, it works as intended but might be cumbersome. I believe this is the result of introducing `name` in the initial design for rich parameters instead of depending on the resource name. Later we decided to support `display_name`.

It might be tricky to implement the non-breaking way without rewriting parameters. For example, if we add a regexp for `coder_parameter` name to block spaces, we need to be sure that already pushed templates won't be affected by the new validation.

> (Optional, fancy): As above, but also check with Levenshtein edit distance of up to 3 and display this as a hint e.g. tip: did you mean: %q ?

This is a good idea no matter which solution we will pick up!

**Comment by johnstcn** [comment] 2023-11-06 16:27
Rough consensus from standup: we don't want to get too restrictive on what folks name their parameters.

I just merged https://github.com/coder/coder/pull/10350 which should make this less annoying. @bpmct are you happy to call this "done"?

**Comment by mtojek** [comment] 2023-11-09 16:22
@johnstcn let's close this one, in the worst case we can iterate on this 👍 .

**Closed** 2023-11-09 16:26 UTC
Labels: cli, s3, parameters, bug
