### ISSUE TITLE
Let `startup_script` results be visible when workspace is stopped

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8784] opened 2023-07-28 03:18 UTC
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

If I mess up my `startup_script`, I can only see what happened when it is running or failed.  The previous `startup_scrip` results including `logstream` should be visible in the previous build logs.

**Comment by bpmct** [comment] 2023-09-03 21:02
closing as duplicate of #7576

**Closed by bpmct** 2023-09-03 21:02 UTC
Labels: feature
