### ISSUE TITLE
coderd does not pick up certs mounted into the helm chart

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7194] opened 2023-04-18 19:36 UTC
coder is currently written to read a cert bundle instead of individual certs. since our Helm chart uploads certs individually, coder fails to pick them up. need coder to read non-bundled certs.

line of code in question, from @deansheather: https://github.com/coder/coder/blob/fa5387ce07be97710c3c893be0633c5e01edbb24/cli/server.go#L1594

v1 equivalent, which handles this properly: https://github.com/coder/v1/blob/0607de7d32785dad6c83411b83399f799582d5ef/lib/go/xhttp/certs.go#L17

**Comment by code-asher** [comment] 2023-06-08 23:08
Just to make sure I am on the right page: the Helm chart puts each CA bundle in `/etc/ssl/certs/{bundle-name}.crt` and someone might add multiple bundles so we need the ability to read more than one?

In which case the solution I think is to make `--tls-client-ca-file` take multiple files.

Or do people usually only have one bundle and we just need to set `--tls-client-ca-file` automatically?

Or alternatively can we just run `update-ca-certificates` as part of the Helm chart to automatically bundle everything in `/etc/ssl/certs` into `/usr/local/share/ca-certificates` (at least I think it does that)?

**Comment by deansheather** [comment] 2023-06-09 13:59
`--tls-client-ca-file` is for client certificate authentication so it doesn't seem relevant for this issue since we're trying to trust CAs.

We can't run `update-ca-certificates` because we don't have root.

We should just copy this code from v1 (ideally with a lot less logging than we had in v1): https://github.com/coder/v1/blob/dfbcbe786f66a1e65b105ae77daa04732b23b181/lib/go/xhttp/client.go#L137

**Comment by deansheather** [comment] 2023-06-09 13:59
@code-asher ping ^

**Comment by code-asher** [comment] 2023-06-09 18:35
> We can't run update-ca-certificates because we don't have root.

Ah unfortunate but that makes sense, thanks!

> --tls-client-ca-file is for client certificate authentication so it doesn't seem relevant for this issue since we're trying to trust CAs.

Ahhhhh that makes way more sense, I had it very backwards.  So in Go's TLS config `ClientCAs` is for the server to verify client certs (and is set via `--tls-client-ca-file`) but what we need is to set `RootCAs` which is for clients to verify server certs and for that we want to read the entire `/etc/ssl/certs` directory.

**Comment by code-asher** [comment] 2023-06-09 18:54
Is it a mistake that we call `configureCAPool` (which sets `ClientCAs` from `--tls-client-ca-file`) when creating the client?  Seems like we only need that for the server?

https://github.com/coder/coder/blob/175561bf3685d247dd901acfd69bbca901be62c1/cli/server.go#L1636-L1639

**Comment by code-asher** [comment] 2023-06-27 19:05
So, I added something to read all the certificates in `/etc/ssl/certs` but when I went to test the behavior before/after with `--oidc-issuer-url` pointing to a domain with a self-signed certificate I discovered it worked even without my change...

As far as I can tell reading from this directory (among others) is default behavior in Go when `RootCAs` is `nil`.  Is there a different reproduction I should be looking at?  

And am I doing something stupid?  Because it seems unlikely we would have gone through all the effort of loading certs in v1 if it already works by default, unless we were already setting `RootCAs` which was causing it to circumvent the default behavior.

Could the issue be that Coder is started before the certificates are mounted?

**Comment by code-asher** [comment] 2023-07-27 18:09
I talked to Eric and the issue was with Coder querying the Terraform registry.  The error was:

```
curl: (35) OpenSSL/3.0.8: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

I think this is a separate issue, at least it does not appear to me that it relates to loading certificates.

To test, I pointed a provider to a localhost address with a self-signed certificate.  I got this (some parts omitted for brevity):

```
$ coder template push --directory ./examples/templates/docker
2023-07-27 17:47:14.934Z "https://localhost:8081/.well-known/terraform.json": tls: failed to verify
2023-07-27 17:47:14.934Z certificate: x509: certificate signed by unknown authority
$ sudo cp ~/.local/share/caddy/ca.crt /etc/ssl/certs
$ coder template push --directory ./examples/templates/docker
2023-07-27 17:55:52.779Z localhost:8081/coder/coder: could not connect to localhost:8081: discovery
2023-07-27 17:55:52.779Z URL returned an unsupported Content-Type "text/html"
```

So it seems to work, at least in terms of TLS (I am not running an actual registry thus the second error).

Let me know if I got something wrong, if not I will close the issue and we can open another for the renegotiation issue, although I am not sure if it something that can be fixed in Coder.

**Comment by code-asher** [comment] 2023-07-31 22:02
Closing for now as it seems the certificates are being readr but if we need to reopen let me know.

As for `unsafe legacy renegotiation disabled` my current understanding is that this means the server needs to be updated or legacy renegotiation needs to be allowed on our end but I do not see any options for that in Go.  Happy to talk about this more if we need to.

**Closed by code-asher** 2023-07-31 22:02 UTC
Labels: p1, bug
