### ISSUE TITLE
workspace not inheriting new image tag defined in coder parameter

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7442] opened 2023-05-05 20:23 UTC
we have customers who do not overwrite image tags, but instead push new tags to an existing image. when updating an image/tag value via coder parameters, the workspace does not inherit the change.

### 1. initial template with image tag & k8s pod

```terraform
data "coder_parameter" "image" {
  name    = "image"
  type    = "string"
  mutable = "true"
  option {
    value = "ericpaulsen/code-server:v1"
    name  = "code-server"
  }
}

resource "kubernetes_pod" "main" {
  spec {
    container {
      image             = "docker.io/${data.coder_parameter.image.value}"
      image_pull_policy = "Always"
    }
  }
}
```

### 2. push new version of the template with new tag

```terraform
data "coder_parameter" "image" {
  name    = "image"
  type    = "string"
  mutable = "true"
  option {
    value = "ericpaulsen/code-server:v2"
    name  = "code-server"
  }
}
```

### 3. rebuild workspace to apply new template version

upon rebuild, the kubernetes pod is shown to have pulled the old image tag `v1`:

```
Normal  Pulled  52s  kubelet  Successfully pulled image "docker.io/ericpaulsen/code-server:v1"
```

### 4. manually edit the workspace parameters in the UI

navigate to **Settings > Parameters** and notice that the image parameters is unset, while all other parmameters (mutable & non-mutable) are set correctly.

<img width="870" alt="Screenshot 2023-05-05 at 4 21 09 PM" src="https://user-images.githubusercontent.com/9683576/236561319-54bcba72-bc1f-4fd5-88e8-abe0f6b1b93a.png">

### 5. set the image value and rebuild workspace

when selecting `ericpaulsen/code-server` and clicking `Submit`, the workspace rebuilds, and correctly inherits the updated value with the new image and tag.

**Comment by ericpaulsen** [comment] 2023-05-05 21:14
update:

i removed the `option` arguments from the parameter, and set the `default` value:

```terraform
data "coder_parameter" "image" {
  name    = "image"
  type    = "string"
  mutable = "true"
  default = "ericpaulsen/code-server:v1"
}
```

i pushed the new template version into Coder and the workspace did not inherit the new default.

**Comment by mtojek** [comment] 2023-05-08 09:05
Thanks for writing down all the repro steps. Well described 👍 

> we have customers who do not overwrite image tags, but instead push new tags to an existing image. when updating an image/tag value via coder parameters, the workspace does not inherit the change.

It works as intended. Let me explain -

Once the owner restarts or rebuilds the workspace, coderd snapshots parameter values from the last workspace build. In this case, values are inherited from the last job. Coderd can't distinguish whether the default was equal to the default or not.
Frankly speaking, we shouldn't change this behavior, as there might be users, who wouldn't like to have parameters being silently changed to different values only because the default parameter value has changed.

**Comment by ericpaulsen** [comment] 2023-05-08 13:42
@mtojek i disagree - the template parameter defaults & options are controlled by admins, and if they make changes to these in the template, they would expect for those changes to be reflected at build time.

as an admin, if i make the decision to remove `option` arguments from a parameter, and set a specific default, that should take effect when workspaces rebuild. cc: @bpmct

**Comment by mtojek** [comment] 2023-05-08 13:48
> @mtojek i disagree - the parameter defaults & options are controlled by admins, and if they make changes to these in the template, they would expect for those changes to be reflected at build time.

I hear you, but it isn't the way it is currently implemented. As I have written above, "default" condition is only checked to determine the value before creating the workspace. If we want to introduce a virtual reference to the parameter's default, then we need to plan for it.

**Comment by bpmct** [comment] 2023-05-10 21:57
Going to move this bug to `p3`. We may move it up, but a workaround we discussed (and will recommend to users) is to use a `local` to interpret the latest value based on a parameter.

**Comment by bpmct** [comment] 2023-08-18 02:05
I realized I never shared the `locals` workaround: here's how you can avoid this scenario:

```hcl
variable "go_image" {
}
variable "java_image" {
}

locals {
  images = {
    "go": var.go_image,
    "java": var.java_image
  }
}

data "coder_parameter" "image" {
  name = "Image"
  default = "go"
  type = "string"
  option {
    name = "Golang"
    value = "go"
  }
  option {
    name = "Java"
    value = "java"
  }
  mutable = "true"
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = local.images[data.coder_parameter.image.value]
  # ...
}
```

Also, if your workspace was initially impacted, you can fix this in the CLI with `coder update <workspace> --always-prompt`

**Comment by bpmct** [comment] 2023-08-18 02:14
Going to close this in favor of #7442. You describe the problem well, I just wanted to share a video of how it works and make a bunch of minor edits so I figured it'd be better to represent in a new issue.

**Closed by bpmct** 2023-08-18 02:14 UTC
Labels: p2, use-case, bug
