### ISSUE TITLE
Memory leak in Coder workspace builds, causing broken Terraform state

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#9364] opened 2023-08-28 02:26 UTC
Creating this as a separate issue to our 2.X woes. 

We've starting seeing this happen to users resulting in admins have to clean up all the resources that it created but never committed to state. It's not user recoverable as these particular workspaces require re-attaching of static resources.

No obvious reason why it thinks there's a timeout after 5 minutes. According to the logs it actually finished...

![Screenshot 2023-08-28 at 12 18 38 pm](https://github.com/coder/coder/assets/2899172/87ea9afe-8fae-4070-8d8e-85a08d212257)

We are spending a lot of time doing recovery busy work since going to 2.X!

**Comment by dcarrion87** [comment] 2023-08-28 02:49
Suspect this is related: 

```
Last Status
terminated
Reason:Reason: OOMKilled - exit code: 137
Started at: 2023-08-27T07:19:22+10:00
Finished at: 2023-08-28T09:05:26+10:00
```

Seems like 2.X has a much bigger RAM requirement than what we had before.

**Comment by mafredri** [comment] 2023-08-28 12:35
Thanks for reporting this, and sorry for the trouble this has caused!

It's possible that #9246 and this issue are intertwined, assuming `coderd` was OOM killed whilst terraform was running. This could potentially allow coderd to schedule work on a provisioner where the cache is still in use by the previous terraform command that's still running.

I also wanted to give you an update that I've been able to reproduce one case of increased memory consumption. This happens when switching template version on a workspace (or updating a workspace). We have not yet looked at why this happens, but we'll dig a bit deeper and continue investigating it.

Do you happen to know if there have been a lot of workspace updates in your deployment?

I saw anywhere from a 20-100MB increase in memory consumption per 1-2 switches. The increase in memory coincided most of the time with the completion of `terraform apply`. After a while, the memory consumption slowly trickles down but does not seem to reach baseline. In a deployment with sufficient activity I can see this causing issues. It did not take me very long to reach 1+GB of memory usage. After 30 minutes coderd was still using ~300MB more than I would've expected.

For now, if you're able, I'd recommend setting your memory limit to `1GB + 80MB * [number of workspaces] + 100MB * [number of provisioners]` as a short-term workaround. This is to account for template updates (main culprit), terraform child processes and workspace restarts (slight increase in memory usage). If you have more than one template update in 30 minutes, and consequently, users updating their workspaces shortly thereafter, consider raising this even higher. Also take into consideration not just active users, but scheduled workspaces as well.

**Comment by dcarrion87** [comment] 2023-08-28 13:09
> Do you happen to know if there have been a lot of workspace updates in your deployment?

Recently there has been more workspace template updates than usual. Not within 30 minutes though. We have never used the rollback faclity and actually wished it just forced users to use the newest template version every time without having to click "update". We've only ever fixed forward when it comes to workspace templates.

Thanks for the recommendations. I've got a scheduled bump of RAM to coder servers tomorrow morning.

**Comment by dcarrion87** [comment] 2023-08-28 13:10
One question. Do stopped workspaces have any impact to resources? Our users have a bad habbit of leaving stopped workspaces hanging around and we have to sweep destroy them 1-2 per month.

**Comment by deansheather** [comment] 2023-08-28 14:34
Stopped workspaces shouldn't have an impact to memory or CPU. Connections to stopped workspace agents (either due to a restart or a stop) may get persisted for a few minutes until they timeout and get removed from memory.

The original issue of the Terraform state not being updated post-build seems to be because coder OOMed between the `terraform apply` finishing and the build being marked as completed in the database. I'm going to rename this issue to be about memory leaks so it's easy for people to find if they have a similar issue.

**Comment by deansheather** [comment] 2023-08-28 14:44
@dcarrion87 could you please provide us with a screenshot of the memory usage of the pod in your screenshot above (from when it started to when it OOMed) and the size of a workspace's TF state for every significantly different template you use?

You can get the TF state size in bytes (as an admin) with `coder state pull username/workspace | wc -c`

**Comment by dcarrion87** [comment] 2023-08-28 22:45
@deansheather I don't have that screenshot but in the other issue where I described problems with install providers I saw it hovering near the 1GB limit. Will get you some numbers on size of state.

**Comment by mafredri** [comment] 2023-08-29 14:09
@dcarrion87 we fixed two leaks in https://github.com/coder/coder/releases/tag/v2.1.4, I can't say for sure if this will fix your use-case fully, but it should help and we would recommend upgrading.

With these two fixes out of the way, I believe I can explain other potential memory usage you may be seeing in your pod:

1. Proxied workspace agent connections and stale connections for 5 minutes after workspace updates (`coderd`)
2. Increased memory usage for each Web UI client (`coderd`)
3. Database cache (`postgres`)
4. Terraform inits and applies (`terraform`)

#### 1. Proxied workspace agent connections and stale connections for 5 minutes after workspace updates (`coderd`)

Here the explanation is that memory usage will vary depending on how coder is being used. We can roughly say there can be 15-35 MB or memory usage per workspace agent. That is, if the coder server needs to talk to an agent over the Tailscale network.

One such request would be `GET /api/v2/workspaceagents/a650d937-c2c5-4f71-94c7-612b821b98f5/listening-ports` which might be requested by the Web UI if port-forwarding is enabled. Or in other scenarios where connections to workspace agents are being proxied by the coder server.

Additionally, updating a workspace that previously had one of these proxied connection cached would temporary increase memory usage by 15-35 MB again if a proxied connection is established with the new agent.

All cached connections time out after 5 minutes, though, so that is how long (at most) it should take for memory usage to recover.

The technical explanation for why this is, is that we have historically used multiple in-memory Tailscale networks, one for each agent. And to speed up communication we cache the connections. We are, however, working towards deprecating this in favor of a single Tailscale network, and that will eliminate this issue entirely. It's currently a hidden experimental feature and, unfortunately, I can't give you a timeline for when it will be enabled by default.

#### 2. Increased memory usage for each Web UI client (`coderd`)

You may se short-lived increases in `coderd` memory usage when the Web UI is being used, especially if workspaces and templates have a lot of history.

Just from loading one of my personal workspaces, I can see memory usage increase by up to 60MB, but this is quite normal for Go programs and will be recovered by the garbage collector. Lots of activity can bring this number up, however, with memory limits I would expect the Go runtime to be more conservative with the memory.

To give you another data point, by quickly hopping between 6 workspaces (5 new ones and the previous one with history), and viewing some build logs, I observed a ~200 MB increase.

If you would like to inspect this behavior yourself, you can enable the pprof endpoint `CODER_PPROF_ENABLE=true` and make a request to `http://coder:6060/debug/pprof/heap?gc=1` to trigger the garbage collector.

#### 3. Database cache (`postgres`)

Assuming you are not using an external PostgreSQL database, the `postgres` process will also use memory inside your pod. I would recommend taking a look at how much memory consumption is attributed to the PostgreSQL process.

Memory usage can also be reduced by changing PostgreSQL settings in `~/.config/coderv2/postgres/data/postgresql.conf`.

The three main knobs I would recommend are `max_connections`, `work_mem` and `shared_buffers`. Their defaults are `100`, `4MB` and `128MB`, respectively. Every connection will use `work_mem` memory unconditionally, and the connections will share `shared_buffers` of memory. So for 50 connections that would be `50 * 4 + 128` MB.

#### 4. Terraform inits and applies (`terraform`)

Finally, terraform processes will use memory and we have no way of knowing how much. I think a fair estimate is 100 MB per provisioner. However, this could largely depend on the complexity of the template and implementation of the providers used.

---

I hope this helps provide some clarity in what may be using memory, and help you find good defaults for your deployment.

**Comment by dcarrion87** [comment] 2023-08-29 22:43
@mafredri huge effort thank you. Will look over and plan a release soon. We are using remote Postgres (RDS) in our case but everything else would apply.

**Comment by dcarrion87** [comment] 2023-09-05 00:57
Since upping the RAM all the discussed issues I raised have gone away. We're planning on releasing new version soon.

**Closed** 2023-11-16 09:46 UTC
Labels: bug, s4
