### ISSUE TITLE
Templetes Dockerfile not visible in Webportal

### ISSUE THREAD

**Issue by docfactory37** [coder/coder#11252] opened 2023-12-18 05:03 UTC
im currently self hosting the latest version on Coder, when i try and Edit a Template, im able to see all the files but the Dockerfile? 

Coder Version: V2.5.1

![Screenshot 2023-12-18 at 4 03 08 pm](https://github.com/coder/coder/assets/20963053/8249454f-9390-4304-b554-73f86d940e59)

**Comment by docfactory37** [comment] 2023-12-18 05:07
i have tried to created a file within the build folder and it does not display to newly created file.

**Comment by matifali** [comment] 2023-12-18 08:52
Duplicate of #11203

**Closed by matifali** 2023-12-18 08:52 UTC
Labels: bug
