### ISSUE TITLE
Managed variables are not being passed into templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6654] opened 2023-03-17 18:10 UTC
I'm noticing that on the latest branch `main` (also dev.coder.com) managed variables are not being passed into templates.

![screenshot_2023-03-17_at_1 05 33_pm](https://user-images.githubusercontent.com/22407953/225984694-a7f5e29e-378e-4e43-9e2b-ee0081a13405.png)
![image](https://user-images.githubusercontent.com/22407953/225984717-b64e0947-a0f0-4e01-a315-3b128785aee4.png)

On my 1.19.2 deployments, it is working works fine. I suspect there was a minor regression into `main`.

![Screenshot 2023-03-17 at 1 09 48 PM](https://user-images.githubusercontent.com/22407953/225984885-997a161a-7148-416f-aaf2-bc747d9d2265.png)

**Comment by mtojek** [comment] 2023-03-17 21:05
I tried to reproduce it locally and failed.

Apparently, the bug appears in the https://dev.coder.com/. Template variable values are stored correctly in the database, workspace build parameters are also fine. For some reason, coder ignores Terraform variable values from the database.

The only difference I spotted is the TF version:

dev.coder.com: 1.1.9
locally: 1.3.4

I will check this bug on Monday, but may need a second pair of eyes.

**Comment by mtojek** [comment] 2023-03-18 08:45
I prepared a new workspace in Pittsburgh with latest main branch, and still it works as expected. I think that what happens here is that something is borked in the dev.coder.com configuration.

**Comment by mtojek** [comment] 2023-03-18 11:05
Status update:

I might have found something. I tried to eavesdrop on PostgreSQL to check what is the exact flow, and here it is:

```
root@coder:/home/marcin# tcpdump -s 0 -i lo -A "port XXXX" | egrep "GetWorkspaceBuildByID|GetTemplateVersionByID|GetTemplateVersionVariables|GetWorkspaceBuildParameters|InsertWorkspaceBuild|GetTemplateByID"

..L...L.P.....-- name: GetTemplateVersionByID :one
..L...L.P...+.-- name: GetTemplateByID :one
..L...L.P...+.-- name: GetTemplateByID :one
..L...L.P...+.-- name: GetTemplateByID :one
..L...L.P.....-- name: GetTemplateVersionByID :one
..L...L.P...+.-- name: GetTemplateByID :one
..L...L.P.....-- name: GetWorkspaceBuildByID :one
..L...L.P.....-- name: GetWorkspaceBuildParameters :many
..L...L.P.....-- name: InsertWorkspaceBuild :one
..L...L.P.....-- name: GetWorkspaceBuildByID :one
..L...L.P.....-- name: InsertWorkspaceBuildParameters :exec

(provisionerdserver.go come in...)
..M...M.P.....-- name: GetWorkspaceBuildByID :one
..M...M.P.....-- name: GetTemplateVersionByID :one
..M...M.P...+.-- name: GetTemplateByID :one
..M...M.P.....-- name: GetTemplateVersionByID :one
..M...M.P...+.-- name: GetTemplateByID :one
..M...M.P...+.-- name: GetTemplateByID :one
..M...M.P...+.-- name: GetTemplateByID :one
..M...M.P.....-- name: GetWorkspaceBuildByID :one
..M...M.P.....-- name: GetWorkspaceBuildParameters :many
...
........P.....-- name: GetWorkspaceBuildByID :one
```

I don't see any db calls to `GetTemplateVersionVariables`, which means that something is wrong in the `GetTemplateVersionVariables`:

```go
func (q *querier) GetTemplateVersionVariables(ctx context.Context, templateVersionID uuid.UUID) ([]database.TemplateVersionVariable, error) {
	tv, err := q.db.GetTemplateVersionByID(ctx, templateVersionID)
	if err != nil {
		return nil, err
	}

	var object rbac.Objecter
	template, err := q.db.GetTemplateByID(ctx, tv.TemplateID.UUID)
	if err != nil {
		if !errors.Is(err, sql.ErrNoRows) {
			return nil, err
		}
		object = rbac.ResourceTemplate.InOrg(tv.OrganizationID)
	} else {
		object = tv.RBACObject(template)
	}

	if err := q.authorizeContext(ctx, rbac.ActionCreate, object); err != nil {
		return nil, err
	}
	return q.db.GetTemplateVersionVariables(ctx, templateVersionID)
}
```

Did we change something in the org configuration in the dogfood instance?

**Comment by mtojek** [comment] 2023-03-20 08:19
Hey @johnstcn! Would you mind taking a look a verifying if the DB auth works as intended in [this case](https://github.com/coder/coder/blob/main/coderd/provisionerdserver/provisionerdserver.go#L157)? Maybe I missed something. It is about the flow that is executed as `provisionerdserver.go`.

**Comment by johnstcn** [comment] 2023-03-20 09:15
Confirmed related to `authz_querier` implementation.

**Comment by johnstcn** [comment] 2023-03-20 10:33
@mtojek can you confirm this is now resolved on dev.coder.com?

**Comment by mtojek** [comment] 2023-03-20 13:18
Yes, it works very well now. Thank you for taking care of this, @johnstcn. Resolving.

**Closed by mtojek** 2023-03-20 13:18 UTC
Labels: bug, bug:p1:high
