### ISSUE TITLE
Retrieve provisioning scripts from version control

### ISSUE THREAD

**Issue by ketang** [coder/coder#2240] opened 2022-06-10 15:04 UTC
In addition to local filesystem upload, some customers will want to retrieve provisioning scripts directly from version control.  I expect they'll want updates to happen in one of three ways:
* automatically immediately (might require a hook)
* automatically eventually (polling)
* only on template owner action

**Comment by tjcran** [comment] 2022-08-09 19:00
Closing as duplicate of #2958

**Closed by tjcran** 2022-08-09 19:00 UTC
Labels: frontend, backend, enterprise
