### ISSUE TITLE
dbauthz: failed to purge old database entries

### ISSUE THREAD

**Issue by mtojek** [coder/coder#7080] opened 2023-04-11 11:11 UTC
I left my coder instance running for the long weekend, and today I found this issue:

```
[API] 2023-04-09 17:41:25.125 [ERROR]      <./coderd/database/dbpurge/dbpurge.go:45>   New.func1    failed to purge old database entries ...
[API] "error": no authorization actor in context:
[API]              github.com/coder/coder/coderd/database/dbauthz.init
[API]                  /Users/mtojek/code/coder/coderd/database/dbauthz/dbauthz.go:22
[API]            - sql: no rows in result set
```

**Comment by johnstcn** [comment] 2023-04-11 11:13
Duplicate of https://github.com/coder/coder/issues/7016

**Closed by johnstcn** 2023-04-11 11:13 UTC
