### ISSUE TITLE
test flake: many e2e test failures

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#9345] opened 2023-08-25 19:41 UTC
E2E kept failing on my branch. Had to rerun multiple times. I am unsure if these failures cascade, or if they are all actually flakes.

Failure videos: https://github.com/coder/coder/suites/15486985981/artifacts/884467794
Failure run: https://github.com/coder/coder/actions/runs/5977909118/job/16219555063

Tests marked as failed:
- createWorkspace-create-workspace-and-overwrite-default-parameters-tests
- createWorkspace-create-workspace-tests
- createWorkspace-create-workspace-with-default-and-required-parameters-tests
- createWorkspace-create-workspace-with-default-immutable-parameters-tests
- createWorkspace-create-workspace-with-default-mutable-parameters-tests
- outdatedAgent-ssh-with-agent-v0-14-0-2f58c4-tests
- startWorkspace-start-workspace-with-ephemeral-parameters-tests

**Comment by BrunoQuaresma** [comment] 2023-08-28 18:23
Fixed by #9392

**Comment by matifali** [comment] 2023-08-30 08:57
@BrunoQuaresma It looks like these flakes need to be resolved.
See 
https://github.com/coder/coder/actions/runs/6015567350/job/16317708669#step:10:3003

**Comment by mtojek** [comment] 2023-08-30 09:32
If you look at failed videos, there are at least 3 different root causes. @matifali Wouldn't it be more convenient to create a new issue for things we spot in logs? Ideas:

1. `coderd: failed to query logs`:

```
2023-08-29T17:31:42.4335743Z [WebServer] 2023-08-29 17:31:42.431 [erro]  coderd: failed to query logs  job_id=063319c7-e61a-422f-a28e-e0178c8bb10c  request_id=a0e41ac8-757a-488b-b51a-d4bc2073ccd6 ...
2023-08-29T17:31:42.4345839Z     error= error writing to websocket:
2023-08-29T17:31:42.4346435Z                github.com/coder/coder/v2/coderd.(*logFollower).query
2023-08-29T17:31:42.4399679Z                    /home/runner/actions-runner/_work/coder/coder/coderd/provisionerjobs.go:459
2023-08-29T17:31:42.4401214Z              - failed to write msg: failed to close writer: failed to write fin frame: failed to write frame: WebSocket closed: failed to acquire lock: context deadline exceeded
2023-08-29T17:31:42.4402712Z [WebServer] 2023-08-29 17:31:42.432 [warn]  coderd: failed to close webscoket  job_id=063319c7-e61a-422f-a28e-e0178c8bb10c  request_id=a0e41ac8-757a-488b-b51a-d4bc2073ccd6  error="failed to close WebSocket: failed to write control frame opClose: WebSocket closed: failed to acquire lock: context deadline exceeded"
```

2. `Error with Permissions-Policy header`

```
2023-08-29T17:31:02.4788739Z ·Console: Error with Permissions-Policy header: Unrecognized feature: 'battery'.
2023-08-29T17:31:02.4789512Z Console: Error with Permissions-Policy header: Unrecognized feature: 'document-domain'.
2023-08-29T17:31:02.4790057Z Console: Error with Permissions-Policy header: Unrecognized feature: 'vr'.
```

3. Split logs per test case.
4. Log backend API calls.

**Comment by matifali** [comment] 2023-08-30 09:35
Closing in favor of individual test flake issues.

**Closed by matifali** 2023-08-30 09:35 UTC
Labels: flake, bug, s4
