### ISSUE TITLE
Feat: coder create STATUS should have a follow up 🟢 green 'connected' message versus 'connecting' 🟡 which insinuates the build hasn't completed.

### ISSUE THREAD

**Issue by mtm20176** [coder/coder#1912] opened 2022-05-31 02:42 UTC
## What is your suggestion?

`coder create` STATUS should have a follow up 🟢 green `connected` message versus just `connecting` with a 🟡 yellow color which insinuates the build hasn't been completed.

## Why do you want this feature?

For clarity and to avoid doubt by the user on the status of the workspace. If you run a `coder  show` after this `create` it shows a nice pretty green `connected`

## Are there any workarounds to get this functionality today?

Run `coder show`

## Are you interested in submitting a PR for this?

Nope
<img width="1115" alt="Screen Shot 2022-05-30 at 9 36 57 PM" src="https://user-images.githubusercontent.com/2022166/171082311-f6ff9cde-75cf-4bc3-bd34-de7690ce2688.png">
<img width="1115" alt="Screen Shot 2022-05-30 at 9 40 27 PM" src="https://user-images.githubusercontent.com/2022166/171082313-64bbbc1d-7143-42a9-ab55-b67a2227b686.png">

**Comment by f0ssel** [comment] 2022-05-31 19:40
duplicate of https://github.com/coder/coder/issues/1036, closing

**Closed by f0ssel** 2022-05-31 19:40 UTC
Labels: new feature :sparkles:, needs grooming :razor:
