### ISSUE TITLE
Coder "app" connections are not recorded as workspace usage for the purposes of detecting idle state

### ISSUE THREAD

**Issue by JoshVee** [coder/coder#11812] opened 2024-01-24 23:58 UTC
We are currently using code-server as a web app, via the `coder_app` resource.

It appears as though connections through this endpoint do not get recorded as workspace usage, therefore the auto-stop behaviour can still occur while in use.

**Comment by johnstcn** [comment] 2024-01-29 11:14
@JoshVee On which version of Coder are you seeing this behaviour?

**Comment by bpmct** [comment] 2024-02-15 15:38
Put in the next sprint:
1. to reproduce
2. to understand whether this was a regression 
3. fix this
4. identify whether there is room for larger improvement in Coder's activity detection

**Comment by johnstcn** [comment] 2024-02-15 16:06
@bpmct is it possible that this was fixed by https://github.com/coder/coder/pull/11603?

**Comment by johnstcn** [comment] 2024-02-19 10:50
I believe this should have been fixed by https://github.com/coder/coder/commit/d583acad001f5b14d992bcd520ef632dbfc9046c, which was included 2.7.0 and later releases. Can anyone confirm if they are still seeing this behaviour?

**Comment by sreya** [comment] 2024-02-22 00:07
Autostop is determined by the [deadline of the workspace build](https://github.com/coder/coder/blob/main/coderd/autobuild/lifecycle_executor.go#L418) so if we're just updating `last_used_at` then probably not?

**Comment by johnstcn** [comment] 2024-02-23 13:36
Given that you can override the agent stats reporting interval, I wonder if setting this to a sufficiently high value could cause this behaviour?

**Comment by Emyrk** [comment] 2024-04-09 17:59
> Given that you can override the agent stats reporting interval, I wonder if setting this to a sufficiently high value could cause this behaviour?

The apps do not report metrics via the agent stats. So the agent stats reporting interval does not change this behavior.

**Comment by Emyrk** [comment] 2024-04-12 15:20
My draft PR _does fix this_, but we should implement a batch sql query to handle this. The looping feels like it could be a performance hit.

**Comment by johnstcn** [comment] 2024-04-15 15:37
I am closing out this issue for now as "cannot reproduce". Please do not hesitate to re-open it if you have more information! 

In any case, we ensure this issue does not resurface when revamping activity detection (see: https://github.com/coder/coder/issues/12965)

**Closed by johnstcn** 2024-04-15 15:37 UTC
Labels: waiting-for-info, s1, must-do, bug
