### ISSUE TITLE
bug: new template version pushed despite no file changes

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12900] opened 2024-04-08 14:55 UTC
our CLI pushes a new template version even if no changes are made. the `coder templates push` command should be `diff` aware, and return `Nothing to do` if a push is run against a template that has not changed.

**Comment by ericpaulsen** [comment] 2024-04-08 14:56
this impacts customers source controlling their templates, with CI pushing new template versions inadvertently.

**Comment by matifali** [comment] 2024-04-08 15:21
This can be achieved in CI by first checking the diff and then conditionally pushing. Why we need to do it within CLI if it's already possible with `git diff`.

**Comment by matifali** [comment] 2024-04-08 15:27
Closing as duplicate of #11642

**Closed by matifali** 2024-04-08 15:27 UTC
Labels: cli, bug
