### ISSUE TITLE
Connection refused on password reset via CLI

### ISSUE THREAD

**Issue by DualState** [coder/coder#6399] opened 2023-03-01 15:17 UTC
**Which version is affected**
`Coder v0.17.4+3f75f6b`

**What happens**
When trying to reset a user's password through the CLI by running `coder reset-password <username>` the following error occurs:

```
ping postgres: dial tcp 127.0.0.1:5432: connect: connection refused
Run 'coder reset-password --help' for usage.
```

**What should happen**
The password for the specified user should be reset, probably after a prompt for the new password. _Interestingly, resetting a user's password through the web interface works fine._

**Additional information**
We run Coder on Ubuntu 22.04. 
It affects all of our three instances of Coder. 
We use the built-in PostgreSQL Database with all instances. 
The issue seems very similiar to the described problem [here](https://pullanswer.com/questions/errors-when-resetting-password).

**Comment by kylecarbs** [comment] 2023-03-01 15:20
We should improve the usage of `reset-password`. That command connects directly to the underlying PostgreSQL database to force the reset of a password, it never connects to the Coder API.

We'll fix this!

**Comment by matifali** [comment] 2023-05-10 05:48
@kylecarbs, @bpmct, do we still have this bug around?

**Comment by matifali** [comment] 2023-05-11 05:39
If this is the expected behavior, as this directly modifies the database, maybe we should close this with a note in the docs explaining the behavior. 

Ideally, a user with an `owner` role should be able to run this from anywhere.

**Comment by matifali** [comment] 2023-05-23 06:10
> Yeah, this command really only works when run on the same machine (or container) as the Coder server

Hi @bpmct, This doesn't work from even the same machine where Coder is deployed. I guess that only the coder users have access to the database.

**Comment by sharkymark** [comment] 2023-06-05 12:33
I kube exec-ed into coderd and this command worked fine for me.

**Comment by matifali** [comment] 2023-07-28 13:42
@bpmct do we want to support password reset from any client?
As @sharkymark solution works fine when used on the coderd host. 
If not then let us close this as resolved.

**Comment by RaineAllDay** [comment] 2023-10-02 02:31
I am running Coder on bare-metal. I am receiving a similar error when using the integrated db. 
```
running command "coder reset-password": ping postgres:
    github.com/coder/coder/v2/cli.(*RootCmd).resetPassword.func1
        /home/runner/action-runner/_work/coder/coder/cli/resetpassword.go:35
  -  dial tcp 127.0.0.1:5432: connect: connection refused
 ```

**Comment by RaineAllDay** [comment] 2023-10-02 02:42
Upon running netstat it looks like postgres is bound to 35501 instead of 5432....

**Comment by RaineAllDay** [comment] 2023-10-04 04:41
Okay. After some research and code digging... I found a workaround.
If you're on the host machine and facing the issue I was, unfortunately using `coder server postgres-builtin-url` did not return a valid connection string for my setup (could be because I attempted to modify the port file, and later removed the password file and let them be regenerated).

If you haven't messed up these files then you should be able to do the following:
```
coder server postgres-builtin-url
> psql "postgres://coder@localhost:[port]/coder?sslmode=disable&password=[password]
export CODER_PG_CONNECTION_URL="postgres://coder:[password]@localhost:[port]/coder?sslmode=disable"
coder reset-password --postgres-url $CODER_PG_CONNECTION_URL [username]
```

If you have messed up these files, and the output is in correct which you can check by either trying above and it failing, or running `netstat -plnt` and seeing the port is wrong compared to the output of `coder server postgres-builtin-url`, then try the following.

```
cd /home/coder/.config/coderv2/postgres
cat password
> [password]
cat port
> [port]
export CODER_PG_CONNECTION_URL="postgres://coder:[password]@localhost:[port]/coder?sslmode=disable"
coder reset-password --postgres-url $CODER_PG_CONNECTION_URL [username]
```

This in the end was the solution to my issue. There may be other ways, but... this ultimately is the long way I found to get it to work. Not sure why Coder does manage to update it's config's enough to have the port change when the `port` or `password` files go missing enough to connect the app. However, it seems like the CLI doesn't update it's references.

**Comment by RaineAllDay** [comment] 2024-01-05 02:37
So. I did some more digging. 

For storing the config information that is referenced by the CLI it uses the LocalConfig method from the configdir package. As found here:
[/cli/config/file.go Line 127-133](https://github.com/coder/coder/blob/138d31621fbb8a8d7f85b9b3da4ca50482f16941/cli/config/file.go#L127C1-L127C1)
```go
func DefaultDir() string {
	configDir := configdir.LocalConfig("coderv2")
	if dir := os.Getenv("CLIDOCGEN_CONFIG_DIRECTORY"); dir != "" {
		configDir = dir
	}
	return configDir
}
```
For the following, this install is on Ubuntu 22.04.

I'm not sure the best way to proceed, as I was looking into contributing a fix for this. This leads to a couple of issues, one of which may be semi-intentional in a production environment vs. a local dev environment. 
1) When coder starts as a service under the "coder" user, the files created/updated are `/home/coder/.config/coderv2/postgres/password` and `/home/coder/.config/coderv2/port`. 
2) When running CLI commands as root, or as the local user, it uses their respective `.config` directories. 

The config package that is being used does have an option for SystemConfig which would allow all users to access the same files. I'm not a huge fan of the connection url being able to be globally accessed by any user. So at the moment it seems like an okay idea for them to be restricted as they are. But it would also be nice to be able to just run the command. So a couple ideas on how to address this, and I'm willing to attempt an update for this as I'm sure it's a lower priority. 

1) We disregard the security implications and save to system config dir. 
2) We add to the documentation a requirement to add the user to the "coder" group, and update [cli/config/file.go ln 109](https://github.com/coder/coder/blob/138d31621fbb8a8d7f85b9b3da4ca50482f16941/cli/config/file.go#L109) to allow group read access. and change the logic for the reads. 

Just wanted to run this by y'all, like I said I can make the changes as it's a lower priority, but given the security concerns wanted your direction on which path would be preferred.

**Comment by matifali** [comment] 2024-01-05 05:40
CC: @kylecarbs

**Comment by spikecurtis** [comment] 2024-01-05 10:50
Coder and the builtin postgres (if needed) are just run under a single user account and don't have to worry about being installed system wide.  I don't think we want to alter that by putting config in a system directory and requiring a "coder" group.

Right now, if 

a) you're running the builtin postgres (and haven't manually modified your config files, I guess) AND
b) you're running `coder reset-password` as the same user on the same system

then it will work without an explicit connection URL. Otherwise, you need to specify the connection URL. In most production setups, a) is not the case, as an externally managed postgres is generally easier to backup, monitor, resize, etc with cloud tools.

Maybe the documentation could be more clear about this, but `coder reset-password` is meant as an emergency maintenance operation if you've lost access to the owner account, not as a tool for routine admin.

I also think our error reporting could be more clear, like "unable to connect to postgres using the connection URL we detected in your environment" or "unable to connect to postgres using a default connection URL postgres://localhost:5432", rather than the error you go.  If you're looking to help, that's where I'd like to see a PR.

**Comment by sreya** [comment] 2024-04-04 18:33
Happy to accept community PRs on this but it's not something we're focused on right now.

**Closed by sreya** 2024-04-04 18:33 UTC
Labels: cli, s3, bug, need-help
