### ISSUE TITLE
front-end hangs when logging out

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6623] opened 2023-03-15 17:51 UTC
currently seeing this on `0.19.2`, Firefox.

<img width="804" alt="Screenshot 2023-03-15 at 1 51 16 PM" src="https://user-images.githubusercontent.com/9683576/225399223-1033c006-ff4e-4dd5-b751-2c7cdab7222d.png">

**Comment by bpmct** [comment] 2023-03-15 18:15
I can reproduce this on 0.18.2, but not dev.coder.com, which leads me to believe it is fixed. However, I can't seem to find the PR that fixed it, perhaps #6550?

@BrunoQuaresma - any ideas? I'm hesitant to close this without understanding why/how this happened or if can still occur in some environments.

**Comment by bpmct** [comment] 2023-03-15 18:16
Perhaps we could also test it on our environments after the next release, just so we can confirm.

**Comment by BrunoQuaresma** [comment] 2023-03-15 19:27
@bpmct where could you reproduce this? It looks like an environment thing 🤔 I was not able to reproduce it from dev.coder.com either.

**Comment by bpmct** [comment] 2023-03-15 20:03
I have a deployment with Coder v0.18.2. You should be able to login: https://coder-primary.apps.openshift.cdr.dev/

**Comment by rodrimaia** [comment] 2023-04-10 13:08
@BrunoQuaresma Fixed!

**Closed by rodrimaia** 2023-04-10 13:08 UTC
Labels: bug, bug:p2:medium
