### ISSUE TITLE
inaccessibility of the Dockerfile in the template editor

### ISSUE THREAD

**Issue by othi08** [coder/coder#11300] opened 2023-12-20 19:31 UTC
Version: [`v2.5.1+e6e65fd`](https://github.com/coder/coder/commit/e6e65fdc64e1c33e5cc02d46d629c6e5d3408931)

![image](https://github.com/coder/coder/assets/74509530/09006859-80a5-44fc-bf09-57349df2b381)

The Dockerfile does not appear in the editor, on the naviagator.

**Comment by matifali** [comment] 2023-12-21 10:31
This is a duplicate of #11203 and has been fixed in #11260.
Will be available in the next release.

**Closed by matifali** 2023-12-21 10:31 UTC
Labels: bug
