### ISSUE TITLE
Allow to sort workspaces by last used

### ISSUE THREAD

**Issue by TheZoker** [coder/coder#12200] opened 2024-02-17 22:57 UTC
For me I'm often using the same workspaces again and again and some rarely. 
The favorite function helps a lot with keeping the most relevant workspaces at the top. 
But still I would prefer if workspaces would be sorted by last used overall. Within the favorite workspaces and also within the other workspaces. Currently some rarely used workspaces are displayed rather high in the list and some workspaces I used yesterday are listed near the bottom.

**Comment by matifali** [comment] 2024-03-28 13:14
duplicate of #9773

**Closed by matifali** 2024-03-28 13:14 UTC
Labels: feature
