### ISSUE TITLE
Create Chrome extension like Gitpod's

### ISSUE THREAD

**Issue by mreadie** [coder/coder#12312] opened 2024-02-26 19:34 UTC
We should have a Coder Chrome extension like Gitpod's Chrome Extension, which adds buttons to GitHub, GitLab, and Bitbucket: https://chromewebstore.google.com/detail/gitpod/dodmmooeoklaejobgleioelladacbeki?pli=1
This improves user experience.

**Comment by matifali** [comment] 2024-02-27 10:04
This will be a good addition, but as Coder is self-hosted this will need some configuration to set the `CODER_ACCESS_URL` and a mapping from repos to templates.

Meanwhile, we have [Open in Coder](https://coder.com/docs/v2/latest/templates/open-in-coder) buttons that can be added to Markdown files.

**Comment by michaelbrewer** [comment] 2024-02-29 05:53
This would be a great feature it there is also first class support for `devcontainers` or something like `.gitpod.yml` then the repo that is being opened gets the write environment. 

As coder is always self hosted your would need to config the extension with your url schema to "Open in Coder"

<img width="449" alt="Screenshot 2024-02-28 at 9 51 56 PM" src="https://github.com/coder/coder/assets/5442469/8ee74fff-f7b9-4245-9dfe-d7371eade1ed">

**Comment by matifali** [comment] 2024-02-29 07:08
Closing this as a duplicate of #8589 to keep the discussion on a single issue.

**Closed by matifali** 2024-02-29 07:08 UTC
Labels: feature
