### ISSUE TITLE
Make OSS(AGPL) version available.

### ISSUE THREAD

**Issue by ninehills** [coder/coder#5127] opened 2022-11-18 02:32 UTC
Now the AGPL version is not available because some APIs is 404, but the Web UI depends on these APIs:

- `GET /api/v2/entitlements`
- `GET /api/v2/workspace-quota/{user}`

It should add a compatibility layer to return the empty response for the enterprise API.

**Comment by coadler** [comment] 2022-11-18 22:51
Duplicate of https://github.com/coder/coder/issues/5118

**Closed by coadler** 2022-11-18 22:51 UTC
