### ISSUE TITLE
healthcheck should fail if there are no configured DERP servers

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#8809] opened 2023-07-31 14:15 UTC
currently, the healthcheck endpoint (`https://coder.example.com/api/v2/debug/health`) only tests if all the configured DERPs work, resulting in a `healthy` response if there are no configured DERPs. since Coder requires >= 1 DERP server(s) to handle workspace connections, the healthcheck should fail if DERPs = 0.

we should return an error akin to:

```
[error] no DERP servers found, please configure 1 or more.
```

**Comment by johnstcn** [comment] 2024-01-09 15:27
Duplicate of https://github.com/coder/coder/issues/7173

Coder no longer starts with an invalid DERP map.
Additionally, `tailscalel/netcheck` will [panic if a region has zero nodes](https://github.com/coder/tailscale/blob/61c97bad8c8b7177e5a983629a88b9bcc47e6801/net/netcheck/netcheck.go#L503), which will cause the [health report to enter the error state](https://github.com/coder/coder/blob/e5b9d63901579b81b15caea4c567386d32210641/coderd/healthcheck/healthcheck.go#L111).

**Closed by johnstcn** 2024-01-09 15:27 UTC
Labels: s2, bug
