### ISSUE TITLE
publish and build buttons disabled in template editor

### ISSUE THREAD

**Issue by matifali** [coder/coder#12545] opened 2024-03-12 10:12 UTC
Can reproduce consistently on dev.coder.com
Coder version: https://github.com/coder/coder/commit/51707446d078fbf1b127dd8ec6d95b2adbb3a9a8
This does not let you update provisioner tags on the template from the dashboard.
![image](https://github.com/coder/coder/assets/10648092/afdb098c-254c-4aa2-a241-8cd525f8f651)

**Comment by johnstcn** [comment] 2024-03-12 10:28
It looks like the `build` button is disabled until you make a change to the template.

**Comment by matifali** [comment] 2024-03-12 10:35
It was a false alarm. The button does work if there is change in the files

**Comment by matifali** [comment] 2024-03-18 18:34
Getting into this again

https://github.com/coder/coder/assets/10648092/d4df77d9-feb2-489f-a749-132d7a0eba2a

**Comment by matifali** [comment] 2024-03-18 18:35
Getting into this again. This happens when I am trying to edit a failed version of a template.

https://github.com/coder/coder/assets/10648092/bc4945e4-a571-4185-88d6-c0718cae261e

**Comment by matifali** [comment] 2024-03-18 18:35
cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment] 2024-03-19 14:20
@matifali sorry, I didn't understand the video very well. What is happening and what is the expected behavior?

**Comment by matifali** [comment] 2024-03-19 14:25
The build button is disabled and is not working. When I make any changes to the template files I should be able to hit build button and it should not be disabled.

**Comment by BrunoQuaresma** [comment] 2024-03-19 14:34
I'm able to build template changes in the `main` version. 

https://github.com/coder/coder/assets/3165839/cfec8a43-9e62-4edf-964f-ab8570157472

**Comment by BrunoQuaresma** [comment] 2024-03-19 17:07
Since this is related to a different cause, I'm closing this in favor of https://github.com/coder/coder/issues/12676

**Closed by BrunoQuaresma** 2024-03-19 17:07 UTC
Labels: site, s2, bug
