### ISSUE TITLE
I have to re-authenticate with GitHub every day in the "create workspace" page

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8895] opened 2023-08-04 03:17 UTC
Our dev.coder.com instance has the device flow git authentication set up. I am noticing that every day, without exception, I have to re-authenticate here in the "Create Workspace" page for our dogfood template:

![Screenshot 2023-08-03 at 10 15 07 PM](https://github.com/coder/coder/assets/22407953/b2ed8966-157b-4a41-8a43-5c4c9982d38d)

I also notice that, after authenticating, I need to refresh the "create workspace" form for it to realize I am authenticated. It doesn't happen automatically.

**Comment by matifali** [comment] 2023-08-04 04:07
I have a long living dogfood workspace and I do not recreate. But whenever I do I also get to reauthenticate with GitHub. And yes it needs refreshing after auth flow.

**Comment by bpmct** [comment] 2023-08-25 03:22
Pretty sure this was fixed? I haven't been seeing this lately

**Comment by bpmct** [comment] 2023-08-25 03:23
However, I'm not sure if the user still has to refresh after they initially link or if its automatic now, so that's probably worth checking before we close out

**Comment by matifali** [comment] 2023-08-30 09:41
Looks like it is still an issue as reported in #9423

**Comment by matifali** [comment] 2023-09-03 23:13
ran into this today. This is really a bad UX and doesn't let you create a workspace without a page refresh.

**Comment by bpmct** [comment] 2023-09-05 14:34
Sadly this isn't super trivial to check since you can't "unlink" a GitHub account. I guess we will need to try on a fresh deployment

**Comment by matifali** [comment] 2023-09-05 14:38
> Sadly this isn't super trivial to check since you can't "unlink" a GitHub account. I guess we will need to try on a fresh deployment

Clearing GitHub cookies or signing out doesn't invalidate the authentication.

**Comment by Emyrk** [comment] 2023-09-05 15:41
Ok, I was a bit confused, but I don't think I actually fixed this bug. I only changed the behavior on `NoRefresh`. dev.coder.com does not use that flag, so the behavior should not have changed.

I will continue to look into this. My PR was mainly improving testing so I can make some changes with a less chance of breaking things.

**Comment by Emyrk** [comment] 2023-09-05 15:46
Just a note, I have not changed the "refresh page" required behavior. That will have to be some FE change to poll or push some update to fix that.

**Comment by Shocktrooper** [comment] 2023-09-06 13:26
One thing to note is that if you use a GitLab instance to replicate this you can delete the authorization inside of GitLab and it resets the coder side back to unauthenticated.  This sounds a bit easier than testing with GitHub from what I can see in this ticket.

**Comment by Emyrk** [comment] 2023-09-06 13:43
I have not hit this personally on my test deployment or dev.coder.com. So I am having a hard time figuring out what is going on.

If you had `NoRefresh=true`, then my PR did make a fix, but dev.coder does not have this set.

The gitauth link should not be expiring, and we never delete them, only update them.

**Comment by sreya** [comment] 2023-09-11 15:32
Going to close this but feel free to reopen is this starts popping up again.

**Comment by Emyrk** [comment] 2023-09-11 15:33
Closing this for lacking reproducing. If it happens again, please reopen with more info,

**Closed by sreya** 2023-09-11 15:32 UTC
Labels: s2, bug
