### ISSUE TITLE
Open a forwarded port to public or how can i authenticate via headers?

### ISSUE THREAD

**Issue by juanbits** [coder/coder#10348] opened 2023-10-19 15:49 UTC
Hi team,

i have a doubt about how can i authenticate via headers to forwarded ports (or open to public), because if I try to send a request to a forwarded port url (GET https://8080--branch--workspace--user.mydomain.com/endpoint ) via an api client (postman, thunder client, etc) i got the next response: 

![image](https://github.com/coder/coder/assets/5168033/59fc259b-54ed-4bcf-b646-42e0339c873b)

thanks in advance by your support

UPDATE. I see in other code-server projects the column/option visibility (but no in coder). In coder looks like all the forwarded ports has the Private visibility by default and cannot be changed. The next image is a proof from other projects
![image](https://github.com/coder/coder/assets/5168033/5fc8013c-0436-4796-9e7d-d0ff4c2885c9)

**Comment by matifali** [comment] 2023-10-19 21:36
Possible duplicate of #8908

**Closed** 2023-10-19 23:12 UTC
Labels: feature
