### ISSUE TITLE
JetBrains Gateway does not work since 2.2.0

### ISSUE THREAD

**Issue by klauserber** [coder/coder#10374] opened 2023-10-21 16:35 UTC
Hello,

the current version of the JetBrains Gateway ist working with Coder 2.1.5:

<img width="819" alt="Bildschirmfoto 2023-10-21 um 18 03 12" src="https://github.com/coder/coder/assets/9998995/62379a1d-14d4-4c79-8cd9-9607c890855e">

The status turns to the word Starting in green, which is a little bit confusing but after choosing the workspace the button 'select IDE and project' gets activated and a connection can be established.

After an upgrade to version 2.2.0 the status never turns to green and it is not possible to select a IDE and project:

<img width="819" alt="Bildschirmfoto 2023-10-21 um 18 08 44" src="https://github.com/coder/coder/assets/9998995/5e62f8a7-5101-4bdc-9aa1-3cb11075967b">

JB Gateway Version:

<img width="431" alt="Bildschirmfoto 2023-10-21 um 18 36 39" src="https://github.com/coder/coder/assets/9998995/79e01362-9677-4ac5-aa7f-e1338676d474">

Same with more recent versions of Coder (2.3.0 & 2.3.2).

**Comment by matifali** [comment] 2023-10-23 08:33
Hi @klauserber, I am unable to reproduce this on the same version.
```text
JetBrains Gateway 2023.2.3
Build #GW-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.coder.gateway (2.6.0)
```
Can you share your Coder plugin version? YOu can get it using the "Copy and Close" button.

**Comment by klauserber** [comment] 2023-10-23 12:41
It is 2.5.2. I have upgraded it to 2.8.0 and will try it later.

```
JetBrains Gateway 2023.2.3
Build #GW-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    com.coder.gateway (2.5.2)
```

**Comment by matifali** [comment] 2023-10-23 18:23
Hi @klauserber, good to know that you have resolved it. Another difference I see is your Coder plugin version for gateway is 2.5.2 while latest is 2.6.0. 
Can you also try updating it and try again with the original template?

**Comment by klauserber** [comment] 2023-10-24 04:32
I have upgraded to Version 2.8.0 and the original template is working well. So I have to fix it in our template. Should be not a big problem since I have a working example.

**Comment by matifali** [comment] 2023-10-24 06:49
Thanks for the update. Closing this as not reproduceable. Feel free to update if you face this again.

**Closed by matifali** 2023-10-24 06:49 UTC
Labels: waiting-for-info, bug
