### ISSUE TITLE
Support bulk edit and delete of users 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#597] opened 2022-03-28 02:09 UTC
As a user with permissions to view and edit users, I want the ability to bulk edit and or delete users from a users list. 

Think bringing in 7k total users but needing to delete 300k. They will not want to have to manually delete these one by one.

**Comment by bpmct** [comment] 2022-07-29 16:11
Closing as duplicate of #2760

**Closed by bpmct** 2022-07-29 16:11 UTC
Labels: frontend, enterprise
