### ISSUE TITLE
Pushing templates with CRLF line endings commonly confuse users

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5917] opened 2023-01-30 14:59 UTC
template files created on a Windows client will follow the CLRF line ending convention. this becomes problematic when the agent start-up script is executed on a Linux-based workspace (which expects the LF line ending convention), resulting in the following errors:

```
/bin/bash: line 1: $'\r': command not found
zsh:2: command not found: ^M
```

@mafredri suggested we could auto-process terraform files from CRLF to LF upon import. from the [terraform docs](https://developer.hashicorp.com/terraform/language/syntax/configuration):

> Terraform accepts configuration files with either Unix-style line endings (LF only) or Windows-style line endings (CR then LF), but the idiomatic style is to use the Unix convention, and so automatic configuration formatting tools may automatically transform CRLF endings to LF.

**Comment by ammario** [comment] 2023-01-30 23:51
It's not totally clear which files are causing problems. We could convert the line endings in all `.tf` files but it doesn't seem like that would affect Terraform's behavior.

Your example suggests the problem is shell scripts with CRLF. But, in that case, we can't reliably determine if the CRLF was intentional, e.g. the script may be designed to run on a Windows agent.

**Comment by ericpaulsen** [comment] 2023-01-31 01:41
> Your example suggests the problem is shell scripts with CRLF. But, in that case, we can't reliably determine if the CRLF was intentional, e.g. the script may be designed to run on a Windows agent.

right - is there a way to identify the line-ending convention of the imported `main.tf` file? if so, then maybe we could transform the line-endings if it does not match the agent OS.

**Comment by ammario** [comment] 2023-01-31 17:17
Yes, we could. But, I think it's unexpected that we would modify the tar between upload and agent extract. It could lead to very difficult bugs. There are cases where mismatched line-endings may be desired, for example if the agent is sending the script to another machine to execute. It is also not clear where Coder's conversion responsibilities end. Do we convert python programs, fish scripts, awk, etc.? 

Can the user workaround this by running the script through `tr -d "\r"` during the agent `startup_script` phase?

**Comment by ericpaulsen** [comment] 2023-01-31 19:40
yes, I can ask them to include `tr -d "\r" in the `startup_script`. i also made them aware of how they can run `dos2unix` against the template files prior to import.

**Comment by ammario** [comment] 2023-01-31 19:41
Okay. I think that is best for now, closing.

**Comment by mafredri** [comment] 2023-02-01 15:23
Considering the problem with transforming the tf file, one option that's left is that we do automatic `dos2unix` transformation on `startup_script` based on what os the agent is running on.

Ideally our users would store the script in a separate file, manage line endings, and import it in the `.tf`, this allows just the relevant portion to be in LR or CRLF format. What we can do is reduce friction when they don't.

**Comment by bpmct** [comment] 2023-04-18 14:34
It seems like the issue I mentioned above doesn't have to do with the startup script, but with uploading the template. Do we understand in which cases both occur?

**Comment by matifali** [comment] 2023-05-05 20:04
Setting VS code to LF on Windows solves this for me.

**Comment by bpmct** [comment] 2023-05-08 14:41
Reworded this issue a bit as a bug. I think the product should do something to assist users to change their line endings.

**Comment by matifali** [comment] 2023-05-31 06:36
Related to #6660
Also, #6357 seems related.

**Comment by mtojek** [comment] 2023-12-14 09:51
@BrunoQuaresma Do you think that you leave here a note justifying whether we can fix it now or we'd rather postpone it for later?

**Comment by mafredri** [comment] 2023-12-14 10:48
@mtojek is this issue properly scoped? For instance I could see this as a CLI/API problem too.

Even if Web UI, say, showed a warning for a template. A CLI user pushing a template and then using create would be sad.

**Comment by mtojek** [comment] 2023-12-14 10:54
Sorry for the noise, I missed the issue. Fixed now.

> Even if Web UI, say, showed a warning for a template. A CLI user pushing a template and then using create would be sad.

I didn't analyze it deeper, but this seems like CLI issue. Do you want to take a stab, @mafredri?

**Comment by mafredri** [comment] 2023-12-14 11:46
Bandwidth wise I think it's unlikely I'd get to this before the new-year, and the solution is still fuzzy for me. I think it would be good to have a clearer definition of done.

For instance, the following edge cases need to be considered/verified:

1. Uploading from the CLI (verified problem)
2. Uploading an archive in the Web UI (`/templates/new`)
3. Editing a template in the Web UI with the template editor (can it introduce/swap LF/CRLF?)

As for the solution, I see two options:

1. Show a warning (requires docs explaining the issue)
2. Auto-fix (requires testing and understanding of edge cases)

As for 1), it's easiest but also a bit annoying since we always have to show it, even after the author has decided they're doing the right thing. Likewise, we can't detect the case where LF was used but CRLF is intended. The only realistic detection I see is detect CRLF and warn.

For 2), I don't really have a clear understanding of the failure scenarios, nor if it's safe to always use LF on Windows (which would make the problem easy, always transform CRLF endings). We know of two failure scenarios:

1. Startup script failing on Linux due to CRLF (fixable in multiple places, e.g. template processor, agent, etc.)
2. Line-ending issue in #122 (but unclear to me why it failed)

But I doubt the CRLF issue only extends to agent scripts. There's also places like this that would be using CRLF (unless handled by the provider/system): https://github.com/coder/coder/blob/82f7b0cef42a591755342a402232d5f2ac138816/examples/templates/gcp-linux/main.tf#L162C3-L162C26

**Comment by matifali** [comment] 2024-01-04 07:25
A user ran into this issue today. We should probably improve error handling and give a clear message that they need to fix line endings to LF.

**Closed** 2024-04-04 18:26 UTC
Labels: s2, bug
