### ISSUE TITLE
Application error: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by DJIronic** [coder/coder#14053] opened 2024-07-30 08:25 UTC
One of my workspaces shows an error when I try to open its page from the list insice coder.

The error is:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at https://artdev.space/assets/WorkspaceBuildData-e78a221d.js:3:7661
    at Fm (https://domain.tld/assets/index-1aa73b9d.js:47:24296)
    at $c (https://domain.tld/assets/index-1aa73b9d.js:47:42443)
    at zee (https://domain.tld/assets/index-1aa73b9d.js:47:41265)
    at vs (https://domain.tld/assets/index-1aa73b9d.js:47:40307)
    at vL (https://domain.tld/assets/index-1aa73b9d.js:47:36911)
    at rs (https://domain.tld/assets/index-1aa73b9d.js:45:3287)
    at https://domain.tld/assets/index-1aa73b9d.js:47:34285
```

I run the latest version of Coder on a Debian machine using docker for the workspaces

Here is a video of the issue on my server: https://ctrlv.tv/ZoxL

**Comment by matifali** [comment] 2024-07-30 08:50
@DJIronic, please also share your Coder version. It looks like a duplicate of #13919, which is under investigation.
Please comment if you think it is different.

**Closed by matifali** 2024-07-30 08:50 UTC
Labels: site, waiting-for-info, bug
