### ISSUE TITLE
Renaming template redirects to old URL when you save

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10873] opened 2023-11-27 01:20 UTC
## Steps to reproduce

- Edit a template setting
- Change its name, not slug
- Hit save
- Notice a 404

**Comment by matifali** [comment] 2023-11-27 05:20
#duplicate of 10634

**Comment by mtojek** [comment] 2024-03-11 10:36
Duplicate is resolved

**Closed by mtojek** 2024-03-11 10:36 UTC
Labels: bug
