### ISSUE TITLE
"Promote" button is confusing when the version is already promoted.

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10002] opened 2023-10-02 22:06 UTC
Can we hide the promote button for the promoted version entirely? It seems like it is greyed out, but I think that's still a bit confusing

![image](https://github.com/coder/coder/assets/22407953/fed45494-931a-425e-92fa-5295fe2d51b1)

**Comment by matifali** [comment] 2023-11-06 14:17
@BrunoQuaresma @10504 could be related

**Comment by aslilac** [comment] 2023-11-06 16:56
we display this intentionally, because it looks bad for it to not be there when there are multiple versions. we can tweak the styling if it would help tho.

**Comment by BrunoQuaresma** [comment] 2024-02-29 14:42
I can confirm it is fixed by https://github.com/coder/coder/pull/10555! 👍

**Closed by BrunoQuaresma** 2024-02-29 14:42 UTC
Labels: site, s3, bug
