### ISSUE TITLE
coder_app shared as `authenticated` or `public` are returning 404s

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#9276] opened 2023-08-23 15:17 UTC
a customer reported this behavior, and I reproduced on `2.1.1`. using the TF provider versions 0.7.0 & 0.11.1. is this expected? I'm logged in as an `Owner` and am still seeing this 404: 

<img width="943" alt="Screenshot 2023-08-23 at 11 16 26 AM" src="https://github.com/coder/coder/assets/9683576/f35b0aa3-a9f3-4367-842d-7341e87e6d54">

**Comment by matifali** [comment] 2023-08-23 15:24
@ericpaulsen I think it is a duplicate of #9016

**Closed** 2023-08-23 19:38 UTC
Labels: bug
