### ISSUE TITLE
bug: default aws linux vm template stuck in `connecting` status when username is admin

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3611] opened 2022-08-20 12:48 UTC
This does not appear to be related to #3511 but even so, that looks like it is one of Coder's dogfood instances with `metadata` which is no what I am using.

As a new Coder OSS user, where my organization uses AWS only, I would like to experiment with Coder. I have no interest in trying any of the Docker templates, which may be easy.

The docs lead me down a rabbit hole of do I need to use the AWS provider since you reference all the cloud providers.
https://coder.com/docs/coder-oss/latest/templates/authentication

Then I run `coder templates init` and see an AWS Linux VM example so create that. I see the AWS provider down the main.tf versus at the top.

I figured out that I need to install the `aws` CLI on my host running Coder, and then run `aws configure`. Again, this is not documented.  At this point, fingers crossed, I can guess Coder can provision workspaces.

Then I `coder templates create` the template into Coder, and create a workspace, at which:
1. Joy, 🥳 I see a VM in my AWS console
2. Boo, 💩 the Coder workspace UI is stuck in `connecting` status and the `code-server` `coder_app` that I added does not come up.

Coder provider: 0.4.8
Coder version: 0.8.5

There is no documentation on how to troubleshoot things like this. My VM doesn't let me SSH in, so I'm basically in a pickle until an expert helps me out.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/2022166/185746814-91780210-afd6-4d4a-8922-4121ad9e4a3b.png">

**Comment by sharkymark** [comment] 2022-08-20 17:00
@bpmct helped me. For now, remove the `user_data_start` steps that create the workspace owner, and use ubuntu as the user (since that is the AMI being used)

@bpmct will troubleshoot to see if workspace owner can be created and used

```console
  user_data_start = <<EOT
Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config.txt"

#cloud-config
cloud_final_modules:
- [scripts-user, always]
hostname: ${lower(data.coder_workspace.me.name)}

--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="userdata.txt"

#!/bin/bash
sudo -u ubuntu sh -c '${coder_agent.main.init_script}'
--//--
EOT
```

**Comment by ericpaulsen** [comment] 2022-08-20 19:39
@sharkymark can you provide your full `locals {}` object? I am still able to reproduce the original issue. Here's mine:

```
locals {

  # User data is used to stop/start AWS instances. See:
  # https://github.com/hashicorp/terraform-provider-aws/issues/22

    user_data_start = <<EOT
Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config.txt"

#cloud-config
cloud_final_modules:
- [scripts-user, always]
hostname: ${lower(data.coder_workspace.me.name)}

--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="userdata.txt"

#!/bin/bash
sudo -u ubuntu sh -c '${coder_agent.coder.init_script}'
--//--
EOT

  user_data_end = <<EOT
Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0
--//
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config.txt"
#cloud-config
cloud_final_modules:
- [scripts-user, always]
--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="userdata.txt"
#!/bin/bash
sudo shutdown -h now
--//--
EOT
}

**Comment by sharkymark** [comment] 2022-08-21 12:11
Something similar appears to happen with the `azure-linux` template. I hard-coded `ubuntu` into the `username` property and it worked i.e., moved beyond `connecting` status

@bpmct @spikecurtis

**Comment by spikecurtis** [comment] 2022-08-22 18:13
Ok, we've chased this down.  The issue is when the Coder user is named `admin`, the cloud-init fails because it tries to create user=admin group=admin, but admin is the name of a builtin group.

We could just hardcode the username "coder" in our templates, or possibly hardcode just the group "coder" (rather than the default of creating a group with the same name as the user).

**Comment by bpmct** [comment] 2022-08-22 19:15
I assigned this, tried hardcoding the `coder` user in cloud-init, then gave up when it didn't work in templates. I might try it again later but feel free to pick this up!

**Comment by bpmct** [comment] 2022-08-22 19:40
Edit: nvm, this was because I lost my `bin/` folder in my deployment after upgrading.

**Closed** 2022-08-22 22:19 UTC
