### ISSUE TITLE
Easier cancellation of auto start

### ISSUE THREAD

**Issue by ketang** [coder/coder#2060] opened 2022-06-05 07:57 UTC
## What is your suggestion?
AFAICT the only way to cancel a schedule is to go into the edit form and zero out the inputs.  I'd like a single button or action to delete a schedule.

## Why do you want this feature?
Clarity and simplicity.

## Are there any workarounds to get this functionality today?
Not that I know of.

## Are you interested in submitting a PR for this?
No

**Comment by misskniss** [comment] 2022-06-14 05:09
duplicate of #1956

**Closed by misskniss** 2022-06-14 05:09 UTC
Labels: duplicate
