### ISSUE TITLE
Admin status bar not always responsive

### ISSUE THREAD

**Issue by ammario** [coder/coder#7741] opened 2023-05-31 17:13 UTC
See how it can get scrunched in certain viewports:

<img width="639" alt="image" src="https://github.com/coder/coder/assets/7416144/64c68cde-82dd-4a6b-ba10-cddef52c453d">

cc @kylecarbs

**Comment by BrunoQuaresma** [comment] 2023-08-09 14:25
Duplicate of https://github.com/coder/coder/issues/8681

**Closed by BrunoQuaresma** 2023-08-09 14:25 UTC
Labels: site, p2, bug
