### ISSUE TITLE
The impact of Terraform Business Source License

### ISSUE THREAD

**Issue by chulucninh09** [coder/coder#9211] opened 2023-08-20 08:01 UTC
Hi, Hashicorp recently revised their Terraform license to Business Source License. I want to understand more about the situation in Coder project:
1. How will it impact the project, since it use Terraform in its part and also use those in Coder Cloud offering?
2. If there is any mitigation needed, what is the plan and how will it impact OSS users and Cloud users?

**Comment by sharkymark** [comment] 2023-08-20 12:10
Hi @chulucninh09 here is our [blog post](https://coder.com/blog/hashicorp-license) on this topic

**Comment by matifali** [comment] 2023-08-21 05:46
Closing as duplicate of #9053

**Closed by matifali** 2023-08-21 05:46 UTC
