### ISSUE TITLE
Deprecated workspaces that are still running not visible to users.

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#13504] opened 2024-06-07 17:48 UTC
Users with running workspaces can not see them if they are deprecated.

You would expect that users can be given time to finish up work and stop and delete these workspaces.

# As an admin

As an admin user you can still see who has running workspaces

<img width="1419" alt="Screenshot 2024-06-07 at 10 50 35 AM" src="https://github.com/coder/coder/assets/5442469/83d792c2-069b-4190-bd98-0c601f403c45">

## For a user

List of templates don't include the deprecated templates

![image](https://github.com/coder/coder/assets/5442469/94c31d49-f2e0-4b75-9fd0-50d3f2806bd3)

List of running workspaces says 1 of 4

![image](https://github.com/coder/coder/assets/5442469/95c7765f-5ebc-441f-99e5-4cf46407a73f)

**Comment by coadler** [comment] 2024-06-07 19:25
Thanks for reporting, we'll definitely fix this :+1:

**Comment by BrunoQuaresma** [comment] 2024-07-22 17:29
I see we have two fixes to do:
- Display deprecated templates in the template menu
- Display workspaces that use a deprecated template
Is this correct?

**Comment by stirby** [comment] 2024-07-26 14:42
Deprecated templates are already visible to admins:

![Screenshot 2024-07-26 at 9 40 59 AM](https://github.com/user-attachments/assets/b19641d6-1cc2-49bc-b9b0-51f5cde3d6e6)


We will need to show workspaces that use a deprecated template. Ideally, with some visual distinction like a badge. We shouldn't call the workspace "deprecated" though.

**Comment by BrunoQuaresma** [comment] 2024-07-29 13:41
> Deprecated templates are already visible to admins:

@stirby should we do that for users too? I see @michaelbrewer left the following comment in the description:

> List of templates don't include the deprecated templates

**Comment by michaelbrewer** [comment] 2024-07-29 15:14
The problematic case is when a user has a running workspace that is deprecated. As it will be filtered out and they can't finish their work before deleting the workspace.

**Comment by stirby** [comment] 2024-07-29 18:46
@michaelbrewer, I am unable to reproduce this on our internal deployment. Which version are you running?

**Comment by michaelbrewer** [comment] 2024-07-29 19:16
This was from 2 months ago. I will have to see if this is still an issue with the latest build.

**Comment by BrunoQuaresma** [comment] 2024-07-30 12:08
Ok, @michaelbrewer, please let us know if you are still experiencing this issue. Closing it for now.

**Closed by BrunoQuaresma** 2024-07-30 12:08 UTC
Labels: site, s1, bug
