### ISSUE TITLE
remove additional pop-up appear when i press `-` or `+` in schedule

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11644] opened 2024-01-16 15:24 UTC
Curious why we need an extra pop-up here

https://github.com/coder/coder/assets/22407953/10cb5ec8-94de-49d3-9f0d-491283902c9e

**Comment by MrPeacockNLB** [comment] 2024-01-16 17:50
may be a duplicate of #11383

**Comment by matifali** [comment] 2024-01-16 19:46
Closing in favor of #11383

**Closed by matifali** 2024-01-16 19:46 UTC
Labels: bug
