### ISSUE TITLE
Feature Request: add data source resource for the user, and what groups they are part of

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#11807] opened 2024-01-24 18:20 UTC
**Use Case: I want to attach different IAM policies based on what groups the user is.** 

**Workaround:**

Create a new template for each group X each use case. The downside is that this means i have to have dozens of templates, just to handle the different permutations of groups.

**My ideal:**

```
data "coder_user" "current" {
}

locals {
  group_to_iam_policy_map = {
    "intern"                   = "arn:aws:iam::aws:policy/InternPolicy"
    "fulltime"                = "arn:aws:iam::aws:policy/FulltimePolicy"
    "SRE"                      = "arn:aws:iam::aws:policy/SREPolicy"
    "DataEngineering" = "arn:aws:iam::aws:policy/DataEngineeringPolicy"
  }
}

resource "aws_iam_role" "workspace_role" { }

resource "aws_iam_role_policy_attachment" "group_policy_attachments" {
  for_each = { for group in data.coder_user.current.user_groups : group => local.group_to_iam_policy_map[group] if group in keys(local.group_to_iam_policy_map) }

  role       = aws_iam_role.workspace_role.name
  policy_arn = each.value
}
```

Using this, each individual gets IAM roles that are customized per user.

**Comment by matifali** [comment] 2024-01-24 19:16
We have [`owner`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#owner), [`owner_name`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#owner_name) and [`owner_email`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#owner_email) already in data [`coder_workspace`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace). We can extend it to have `owner_groups` too.

**Comment by elliot-graebert-skydio** [comment] 2024-01-24 22:43
@matifali absolutely, that works just as well!

**Comment by matifali** [comment] 2024-01-26 12:58
closing as duplicate of #8560

**Closed by matifali** 2024-01-26 12:58 UTC
Labels: feature
