### ISSUE TITLE
Flake: `test-go-race` `coderd/provisionerdserver` leaked goroutine

### ISSUE THREAD

**Issue by coadler** [coder/coder#13855] opened 2024-07-09 17:12 UTC
https://github.com/coder/coder/actions/runs/9860944020/job/27228286676?pr=13837

```
=== FAIL: coderd/provisionerdserver  (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 6 in state chan send, with github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat.func1 on top of the stack:
github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat.func1({0x2d7fcc8, 0xc000405b20})
	/home/runner/work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:108 +0xb3
github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeat(0xc0002b2780, {0x2d7fcc8, 0xc000405b20})
	/home/runner/work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:275 +0x89
github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeatLoop(0xc0002b2780)
	/home/runner/work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:253 +0x309
created by github.com/coder/coder/v2/coderd/provisionerdserver.NewServer in goroutine 52
	/home/runner/work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:224 +0x13b4
]
FAIL	github.com/coder/coder/v2/coderd/provisionerdserver	20.577s
```

**Comment by ethanndickson** [comment] 2024-07-10 04:11
Duplicate of #13816.

**Closed by ethanndickson** 2024-07-10 04:11 UTC
Labels: flake, s4
