### ISSUE TITLE
agent logs don't stream on web when writing from a second log source - 2.13 regression

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#14257] opened 2024-08-13 10:58 UTC
The Agent is coming up and sending logs to Coderd, and then in addition, you have a second program that is also sending logs to Coderd, using the same Agent token.

The logs the Agent sends (e.g. logs from startup scripts) are appearing in the Web Dashboard, and stream in while the workspace is starting.

The logs the second program sends do not appear initially, but then if you refresh your browser, they appear as well, along side the logs the Agent sends. This happens regardless of whether you use the LogsSender (HTTP PATCH API) or the NewLogsSender (dRPC over websocket API) to send the logs.

Also, on Coder server version 2.12.1, the logs from the second program streamed correctly.

**Comment by bpmct** [comment] 2024-08-29 14:34
This happens to me with envbuilder as well!

**Comment by bpmct** [comment] 2024-08-29 14:35
@mtojek @BrunoQuaresma can you investigate for 🥥 this sprint?

**Comment by mtojek** [comment] 2024-08-29 14:40
@BrunoQuaresma I assigned this one to you at first to reproduce it on the frontend side first and verify if it is a site problem.

**Closed** 2024-09-03 18:01 UTC
Labels: site, s2, must-do, bug, customer-reported, regression

**Comment by aaronlehmann** [comment] 2024-10-06 23:51
It looks like this regressed in 2.15.1. Looking at the code, the fix does not seem to be included in that release.
