### ISSUE TITLE
`helm upgrade` results in "You have multiple replicas but high availability is an Enterprise feature. You will be unable to connect to workspaces."

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9041] opened 2023-08-11 05:34 UTC
Every time I upgrade my release, I see this message at the top of the application. If I delete the pod and let it be recreated, the message goes away.

**Comment by ericpaulsen** [comment] 2023-08-11 16:00
possibly related: https://github.com/coder/coder/issues/8927

**Comment by ryansburgoyne** [comment] 2023-08-11 16:53
Yes sounds like exactly the same issue.

**Comment by Emyrk** [comment] 2023-08-18 17:00
Duplicate of: https://github.com/coder/coder/issues/8665

**Closed by Emyrk** 2023-08-18 17:00 UTC
Labels: p2, bug
