### ISSUE TITLE
buildtime shows wrong value

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#15413] opened 2024-11-06 18:57 UTC
# description

I just restarted my Workspace and wonder about the buildtime.

![Image](https://github.com/user-attachments/assets/e7a56344-5ae7-4a4e-8ee1-4688e045c1da)

As one could see the uptime is 13 minutes, but buildtime shows something else. Maybe the buildtime start does not get reset on restarting?

**Comment by BrunoQuaresma** [comment] 2024-11-06 21:32
@MrPeacockNLB could you please share with us, here or in private, the JSON response for the /timings endpoint? You can find it in the network tab in the development console.

**Comment by MrPeacockNLB** [comment] 2024-11-07 06:44
I think I can share a sample which shows nicely what is going on here:

```json
"agent_script_timings": [
        {
            "started_at": "2024-11-05T07:29:20.941125Z",
            "ended_at": "2024-11-05T07:29:22.644473Z",
            "exit_code": 0,
            "stage": "start",
            "status": "ok",
            "display_name": "XXX"
        },
        {
            "started_at": "2024-11-06T18:39:47.12748Z",
            "ended_at": "2024-11-06T18:39:48.806912Z",
            "exit_code": 0,
            "stage": "start",
            "status": "ok",
            "display_name": "XXX"
        },
```

It seems each **coder script** for each restart (in my case just two) gets send back as a response to the frontend. If you substract the timestamps then makes it sense to display 35h

**Comment by MrPeacockNLB** [comment] 2024-11-07 06:49
to clarify what **Uptime** mean. As soon the agent startup script runs we write a timestamp file. In the metadata we show now-starttime.

**Comment by MrPeacockNLB** [comment] 2024-11-07 10:44
I'e restarted again and now it shows the time between the last start/restart and is much lower.

**Comment by BrunoQuaresma** [comment] 2024-11-07 13:39
@MrPeacockNLB, you helped us a lot. I think I know what the issue is now—thank you!

**Comment by BrunoQuaresma** [comment] 2024-11-14 19:26
@MrPeacockNLB I see the issue, but I can't reproduce that 🤔 does it happen with any workspace you create and restart?

**Comment by MrPeacockNLB** [comment] 2024-11-16 16:11
hmn... I've also problems in reproduce this failure. I tend to close this issue and open a new one if this occurrs again.

**Comment by BrunoQuaresma** [comment] 2024-11-22 12:36
Let's leave it open for now but let me summarize the issue for posterity. 

**Issue:**
Sometimes, the BE sends multiple timings for the same script when it should only return one since a script only runs once during the build.

**Cause:**
It is unclear what can cause the API to return multiple timings for the same script. I reviewed SQL queries and checked the tests for the endpoint and they all look good. 

**Workaround:**
Make the FE more defensive and always use the last timing available instead of assuming the BE is always returning a single result.

**Comment by BrunoQuaresma** [comment] 2024-11-22 17:30
@MrPeacockNLB I'm closing it for now.

**Closed by BrunoQuaresma** 2024-11-22 17:30 UTC
Labels: observability
