### ISSUE TITLE
Add capability to search, sort and filter users 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#593] opened 2022-03-28 01:56 UTC
As a user with a role that allows me to see other users in the product, I want the ability to search for, sort and filter users in the users list so I can more quickly find and organize my view of the users based on my needs. 

Note: this may mean we need to implement a general model for the ability to to do these actions for other things like orgs and workspaces.

**Comment by tjcran** [comment] 2022-06-03 15:59
closing as a duplicate of #595

**Closed by tjcran** 2022-06-03 15:59 UTC
Labels: frontend :art:, Enterprise MVP :checkered_flag:
