### ISSUE TITLE
`coder templates create` using the template `docker-image-builds` and derivatives fails to build

### ISSUE THREAD

**Issue by wale** [coder/coder#2815] opened 2022-07-04 00:12 UTC
## Problem
The images folder is seemingly not pushed to the host when running `coder templates create` on Windows clients. The second validation rule in the below template snippet seemingly always fails regardless of the availability of the relevant images folder:
```hcl
variable "docker_image" {
  description = "What Docker image would you like to use for your workspace?"
  default     = "alpine"

  # List of images available for the user to choose from.
  # Delete this condition to give users free text input.
  validation {
    condition = contains([
      "alpine",
      "ubuntu"
    ], var.docker_image)
    error_message = "Invalid Docker image!"
  }

  # Prevents admin errors when the image is not found
  validation {
    condition     = fileexists("images/${var.docker_image}.Dockerfile")
    error_message = "Invalid Docker image. The file does not exist in the images directory."
  }
}
```

Logs: 
![Logs](https://btw.i-use-ar.ch/i/aphjn.png)
Directory tree: 
![Tree](https://btw.i-use-ar.ch/i/02ghm.png)

This is also reproducible with the default `docker-image-builds` template without any changes.

Coder version (on both host and client): [Coder v0.7.6+a494489](https://github.com/coder/coder/commit/a494489ffac76d977c2733c8d33112bf95235ea3)

**Comment by wale** [comment] 2022-07-06 04:38
Apparently this is a bug that doesn't import Dockerfiles in a given directory, but importing them from the template root works fine?

**Comment by phorcys420** [comment] 2022-07-20 15:28
> Apparently this is a bug that doesn't import Dockerfiles in a given directory, but importing them from the template root works fine?

Can confirm, the same error is occuring in a template of mine.
Maybe this issue should be re-named to something more generic ? Also, the weird part is that it doesn't seem to come from the docker provider itself, since even ``fileexists`` fails.

**Comment by bpmct** [comment] 2022-07-25 21:29
@wale @phorcys420 Are you on Windows clients? I was only able to reproduce this when trying the `docker-image-builds` using `coder` on Windows. This appears to be a Coder bug as it's not recursively uploading the folder and subfolders to Coder.t

I also confirmed moving the `images/` to root on WIndows fixed it.

**Comment by phorcys420** [comment] 2022-07-25 21:31
> Are you on Windows clients?
Yeah.

> This appears to be a Coder bug as it's not recursively uploading the folder and subfolders to Coder
Maybe, but doing ``coder templates pull`` still contains my subfolders.

**Comment by bpmct** [comment] 2022-07-25 21:57
@phorcys420 You're able to make it through `coder templates create` and pull the template? Mine is failing at the create step.

**Comment by phorcys420** [comment] 2022-07-25 21:58
> @phorcys420 You're able to make it through `coder templates create` and pull the template? Mine is failing at the create step because of the validation rule. 

No, I had to remove that one, and it still didn't work afterwards. I'm just pointing out that it does upload them because I can pull the subfolders afterwards.

**Comment by phorcys420** [comment] 2022-08-01 18:42
![image](https://user-images.githubusercontent.com/57866459/182220819-a0e793b9-e9d9-4057-ad86-8b96a7a1c833.png)
Stumbled across this today while pulling my template ([v0.8.2+00c5116](https://github.com/coder/coder/commit/00c5116a2e9c18f489cd876f7cd965686cbd759a)), maybe this has something to do with this issue?

**Comment by misskniss** [comment] 2022-08-09 15:05
@dwahler will look into this one.

**Comment by phorcys420** [comment] 2022-10-02 15:31
any news ?

**Comment by matifali** [comment] 2022-10-08 21:42
I also faced this when trying to add files in my `Dockerfile`. Somehow docker provider doesn't see other files in the `images` subdirectory

**Comment by phorcys420** [comment] 2022-10-11 15:01
> I also faced this when trying to add files in my `Dockerfile`. Somehow docker provider doesn't see other files in the `images` subdirectory

apparently it doesn't even see other files at all, I tried to ``ADD`` files from the same directory and it didn't see the file.

**Comment by matifali** [comment] 2022-10-11 15:03
Is it a  coder issue or the docker provide issue?

**Comment by jsjoeio** [comment] 2022-10-11 18:11
I was able to reproduce this using `Coder v0.9.8+b50bb99 Mon Oct 10 18:45:03 UTC 2022`.

Logs:
```shell
PS C:\repro\coder_0.9.8_windows_amd64\docker-build-images> ..\coder.exe templates create      
> Create and upload "C:\\repro\\coder_0.9.8_windows_amd64\\docker-build-images"? (yes/no) yes
✔ Queued [261ms]
✔ Setting up [66ms]
✔ Adding README.md... [65ms]
✔ Parsing template parameters [144ms]
⧗  Detecting persistent resources
  Terraform 1.1.9

  Error: Invalid value for variable
  Invalid Docker image. The file does not exist in the images directory.

This was checked by the validation rule at main.tf:62,3-13.
✔ Detecting persistent resources [2130ms]
✘ Cleaning Up [111ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates create --help' for usage.
```

I'm going to dig in and see if I can find the root cause.

**Comment by jsjoeio** [comment] 2022-10-11 19:55
I'm currently getting a Windows workspace fully setup then my plan is to see if this is on the Coder side or Terraform side by:
1. removing validation lines in `main.tf`
2. running `coder templates create`
3. after success `coder templates pull`
4. verify subdirectory `images` is there

If so, then it reproduces what @phorcys420 shared and would lead me to believe this is on the provider side. Stay tuned for more info.

**Comment by jsjoeio** [comment] 2022-10-11 21:07
I was able to do the above + `coder templates pull <template name> file.tar.gz` and then extract it to see that the `coder` CLI does indeed upload the subdirectories.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3806031/195198084-73f18c98-473b-49bc-963a-9cf301ea3771.png">

Therefore, I believe this issue is in the docker provider we're using. @bpmct did share this issue he found which may be related: https://github.com/kreuzwerker/terraform-provider-docker/issues/325

Workarounds:
- remove validation steps 
- move `images/` to root as suggested by @bpmct [here](https://github.com/coder/coder/issues/2815#issuecomment-1194653357)

@bpmct how would you like to proceed from here?

**Comment by phorcys420** [comment] 2022-10-12 06:26
> move ``images/`` to root

please be aware that even if you did that you couldn't add files to the CT at all

**Comment by matifali** [comment] 2022-10-12 06:58
> > move `images/` to root
> 
> please be aware that even if you did that you couldn't add files to the CT at all

yes, I face this issue while using `ADD` in my docker file. It does not see any files in the `images/` directory. 
PS. I am using a Linux client and server.

**Comment by jsjoeio** [comment] 2022-10-13 20:22
Thank you both for the additional context. I chatted a bit offline with @bpmct. He was surprised removing the validation steps allows to template to be uploaded.

> Variable validation has nothing to do with the Docker provider.

Maybe it's an issue with Terraform on Windows? We'd have to dig in.

> Also, the provisioning itself happens using the Linux/Mac version of the Terraform provider on the server but I guess it’s uploaded by the Windows coder client?

Additional notes shared by Ben.

I'm going to ping a couple other team members and see if they have insight. Thanks all for your patience!

**Comment by jsjoeio** [comment] 2022-10-13 21:39
> yes, I face this issue while using ADD in my docker file. It does not see any files in the images/ directory.

Thank you! I wonder if that's a separate issue.

**Comment by jsjoeio** [comment] 2022-10-13 21:49
I'm digging into this more to make sure we can identify what the actual problem is. 

My first thought is, "Can I create workspace using the [`docker` template](https://github.com/coder/coder/tree/main/examples/templates/docker) on a Windows client?"

**Steps to reproduce**
1. `coder template init` -> select "docker"
2. `cd .\docker\ && coder template create` 
3. `coder create --template="docker" test-docker`

**Expected**
It builds the workspace fine and I can ssh into it.

**Actual**
Fails with error:
```shell
✔ Starting workspace [1258ms]
✘ Cleaning Up [119ms]
send job update: insert job logs: pq: invalid byte sequence for encoding "UTF8": 0x00
Run 'coder create --help' for usage.
```

Workspace Logs from UI:
```shell
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform 1.3.0
data.coder_workspace.me: Refreshing...
data.coder_provisioner.me: Refreshing...
data.coder_provisioner.me: Refresh complete after 0s [id=eface01e-4cae-47b5-8b70-71db4f0c2f9b]
data.coder_workspace.me: Refresh complete after 0s [id=27cf56ec-2fc7-4b32-bba2-dd8fef127d74]
coder_agent.main: Plan to create
coder_app.code-server: Plan to create
docker_volume.home_volume: Plan to create
docker_image.main: Plan to create
docker_container.workspace[0]: Plan to create
Plan: 5 to add, 0 to change, 0 to destroy.
coder_agent.main: Creating...
coder_agent.main: Creation complete after 0s [id=dd7195be-2ed7-4b87-81a8-51d52cf4fd12]
docker_volume.home_volume: Creating...
coder_app.code-server: Creating...
docker_image.main: Creating...
coder_app.code-server: Creation complete after 0s [id=3fa2a7de-3f02-44c8-a922-aa3c39b476fc]
docker_volume.home_volume: Creation complete after 0s [id=coder-jp-test-docker-home]
docker_image.main: Creation errored after 0s
```

"What is `docker_image.main`?"
[Here is the code](https://github.com/coder/coder/blob/main/examples/templates/docker/main.tf#L63-L71):
```tf
resource "docker_image" "main" {
  name = "coder-${data.coder_workspace.me.id}"
  build {
    path = "./build"
  }
  triggers = {
    dir_sha1 = sha1(join("", [for f in fileset(path.module, "build/*") : filesha1(f)]))
  }
}
```

As you can see, this is relying on a subdirectory `./build` in the template. That's one common denominator between this and the `docker-image-builds` failure.

**Comment by jsjoeio** [comment] 2022-10-13 21:54
"Now let's try the [`docker-code-server` template](https://github.com/coder/coder/tree/main/examples/templates/docker-code-server) which doesn't rely on any subdirectories"

**Steps to reproduce**
1. `coder template init` -> select "docker-code-server"
2. `cd .\docker\ && coder template create` 
3. `coder create --template="docker-code-server" test-cs`

**Expected**
It builds the workspace fine and I can ssh into it.

**Actual**
It builds the workspace fine and I can ssh into it.

So here, not using subdirectories, everything works as expected.

**Comment by jsjoeio** [comment] 2022-10-13 21:57
Thus far, we have two factors that _may_ be related to this:
- Windows client
- subdirectories in the template

Let's see if we can eliminate the first one. 

"Can I create workspace using the [docker template](https://github.com/coder/coder/tree/main/examples/templates/docker) on a macOS client?"

WIP

**Comment by mafredri** [comment] 2022-10-14 09:21
The issue seems to have been that we were saving Windows-based paths (backslash) vs Unix-based (slash) in the tar archives, fix in #4548.

@jsjoeio I'm unsure if this helps with the other issues you discovered?

**Comment by matifali** [comment] 2022-10-14 09:28
What about `Dockerfile` unable to use any `ADD` commands because it can not see the external files?

**Comment by mafredri** [comment] 2022-10-14 09:31
@matifali that should also be fixed by this since the files will now be in the correct folder.

**Comment by matifali** [comment] 2022-10-14 09:38
> @matifali that should also be fixed by this since the files will now be in the correct folder.

but I faced that on Linux client. so a path fix. I will test again after you merge.

**Comment by mafredri** [comment] 2022-10-14 09:50
@matifali if the archive was created on Windows, then it would affect a Linux client as well. But if the flow was Linux -> Linux then this change would have no effect. If that's still a problem for you we should perhaps move it to a new separate issue?

**Comment by bpmct** [comment] 2022-10-14 12:44
I originally thought this was a Windows-only issue but I may have missed something!

**Comment by jsjoeio** [comment] 2022-10-14 16:14
Nice find @mafredri 🙌🏼

Once it's merged and a new release is cut, I'll re-test and verify the fix.

**Closed** 2022-10-14 16:28 UTC
Labels: bug, severe

**Comment by jsjoeio** [comment] 2022-10-17 21:20
This is out now: https://github.com/coder/coder/releases/tag/v0.10.0

**Comment by phorcys420** [comment] 2022-10-18 08:24
Work for me on Windows with v0.10.1 !

**Comment by jsjoeio** [comment] 2022-10-18 15:18
Woohoo! Thanks for confirming!
