### ISSUE TITLE
https://coder.com/docs/code-server/latest/ios ERROR

### ISSUE THREAD

**Issue by dude2040** [coder/coder#13143] opened 2024-05-03 13:18 UTC
Following installation instructions in title url results..

+ curl -#fL -o ~/.cache/coder/coder_2.10.2_linux_i686.apk.incomplete -C - https://github.com/coder/coder/releases/download/v2.10.2/coder_2.10.2_linux_i686.apk
+ '[' '!'  ]
+ sh -c 'curl -#fL -o /root/.cache/coder/coder_2.10.2_linux_i686.apk.incomplete -C - https://github.com/coder/coder/releases/download/v2.10.2/coder_2.10.2_linux_i686.apk'
#=#=#                                           ##O#-#                                          ##O=#  #                                        curl: (22) The requested URL returned error: 404

**Comment by matifali** [comment] 2024-05-03 17:29
Coder is not supported on iOS. Duplicate of #7947
Please follow the docs here: https://coder.com/docs/v2/latest/install to install on macOS, Linux or Windows

**Closed by matifali** 2024-05-03 17:29 UTC
