### ISSUE TITLE
Feat: provide autocomplete + selection menu for timezone on workspaces schedule page

### ISSUE THREAD

**Issue by ketang** [coder/coder#2025] opened 2022-06-03 14:47 UTC
## What is your suggestion?
Provide autocomplete + selection menu for timezone on workspaces schedule page.

Copy `zone.tab` from `/usr/share/zoneinfo/` at build-time and use that as the source of truth.

## Why do you want this feature?
It's easy to type the timezone name wrong.  Sometimes confusing to look up also.  The link about the timezone database takes you to an image, so you can't copy and paste either.

## Are there any workarounds to get this functionality today?
No.

**Comment by ketang** [comment] 2022-06-03 14:47
Example from a Mac OS X system.

[zone.tab.txt](https://github.com/coder/coder/files/8833127/zone.tab.txt)

**Comment by vapurrmaid** [comment] 2022-06-03 15:31
This is a dupe of #1959

**Closed by vapurrmaid** 2022-06-03 15:31 UTC
Labels: new feature :sparkles:, needs grooming :razor:
