### ISSUE TITLE
Quiet error when attempting to resolve "legacy parameters" warning.

### ISSUE THREAD

**Issue by indoben** [coder/coder#7668] opened 2023-05-24 16:01 UTC
After the most recent update, I started getting the `This template uses legacy parameters which will be deprecated in the next Coder release. Learn how to migrate in [our documentation](https://coder.com/docs/v2/latest/templates/parameters#migration).` warning. I replaced the _variable_ blocks with _coder_parameter_ blocks. The update to the template appears to have gone through:

![image](https://github.com/coder/coder/assets/4695186/19596df6-7b62-451f-959d-55b924fcd477)

However when attempting to use the new template, I notice a couple of things. First the new version is not automatically enabled like it typically is:

![image](https://github.com/coder/coder/assets/4695186/87809a3c-142d-4511-9f90-ea4d6e4f354d)

Second, when I attempt to use a new version (after manually enabling it), I get this error: `Template version job hasn't completed!`

Checking the logs, I see this: 

> 2023-05-24 15:54:16.682 [info]  coderd.provisionerd-sharp_hertz1: inserting template import job parameter  job_id=e343b3ae-
> c683-4f11-9343-641b1fa77395  parameter_name="Use kubeconfig"
> 2023-05-24 15:54:16.685 [info]  coderd.provisionerd-sharp_hertz1: inserting template import job parameter  job_id=e343b3ae-c683-4f11-9343-641b1fa77395  parameter_name=namespace
> 2023-05-24 15:54:16.687 [info]  coderd.provisionerd-sharp_hertz1: inserting template import job parameter  job_id=e343b3ae-c683-4f11-9343-641b1fa77395  parameter_name=namespace
> 2023-05-24 15:54:16.690 [erro]  send CompletedJob  job_id=e343b3ae-c683-4f11-9343-641b1fa77395 ...
>     error= insert parameter: pq: duplicate key value violates unique constraint "template_version_parameters_template_version_id_name_key"
>                 storj.io/drpc/drpcwire.UnmarshalError:26
>                 storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
>                 storj.io/drpc/drpcmanager.(*Manager).manageReader:247

**Comment by sharkymark** [comment] 2023-05-24 16:41
@indoben did you push the new template using the CLI or in the UI? In the UI, you have to click the checkbox to promote it.

It's off by default (to limit the blast radius)

<img width="1079" alt="image" src="https://github.com/coder/coder/assets/2022166/34b6ec17-e7dc-4ea5-9dcc-931ce75a30a9">

I was able to not make it default, then promote it later, and it worked for me.

Do you have parameter name used twice?

**Comment by indoben** [comment] 2023-05-24 18:25
@sharkymark It was pushed via the CLI

**Comment by indoben** [comment] 2023-06-06 17:21
Also, same error when attempting to create a brand new template without any previous template versions to conflict with.

**Comment by mtojek** [comment] 2023-06-12 09:22
Based on logs you provided:

```
2023-05-24 15:54:16.690 [erro] send CompletedJob job_id=e343b3ae-c683-4f11-9343-641b1fa77395 ...
error= insert parameter: pq: duplicate key value violates unique constraint "template_version_parameters_template_version_id_name_key"
storj.io/drpc/drpcwire.UnmarshalError:26
storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
storj.io/drpc/drpcmanager.(*Manager).manageReader:
```

Please double-check if you don't have 2 parameters with the same name.

**Comment by indoben** [comment] 2023-06-12 14:46
@mtojek This ended up being the issue, I had a typo which led to two parameters being named the same. The "template_portion_id" portion of that error is what really threw me off.

**Comment by matifali** [comment] 2023-06-12 14:50
@indoben seems like you found the root cause. Should we close this issue?

**Closed** 2023-06-12 14:54 UTC
Labels: waiting-for-info, bug
