### ISSUE TITLE
Name missing from OIDC created users

### ISSUE THREAD

**Issue by jamestoyer** [coder/coder#11838] opened 2024-01-26 14:28 UTC
In https://github.com/coder/coder/pull/11639 the `Name` field was added, which allows `owner_name` to be referenced, however it appears this field is not populated when doing an OIDC login on Coder v2. As member can't (and probably should't) update the name field in the UI it means we can't use it in places like automatically configuring the git config.

I've compared this to Coder v1, which we also run, and it's OIDC implementation does appear to pull in an equivalent to the name. Is it possible this was just an oversight in the PR implementation or is there some other limitation here?

**Comment by bpmct** [comment] 2024-01-29 02:30
related https://github.com/coder/coder/issues/11704

**Comment by matifali** [comment] 2024-01-29 10:16
Closing as duplicate of #11704

**Closed by matifali** 2024-01-29 10:16 UTC
Labels: bug
