### ISSUE TITLE
Required User Admin Permission to Change Their Own Account Info

### ISSUE THREAD

**Issue by Jacky97s** [coder/coder#13727] opened 2024-06-29 05:37 UTC
## Description:
Users are currently required to have User Admin permissions to change their own account information. This issue affects user experience and workflow efficiency, as users without these permissions are unable to make necessary updates to their profiles. Additionally, my template's Git author name is based on the coder user's name, which makes it essential for users to update their account information when needed.

## Steps to Reproduce:

Log in to the system with a user account that does not have User Admin permissions.
Attempt to change account information (e.g., name, email, password).

## Expected Behavior:
Users should be able to change their own account information without requiring User Admin permissions.

## Actual Behavior:
Users are unable to change their own account information

### Owner or User Admin permission:

![image](https://github.com/coder/coder/assets/25542146/8ed44e49-fe09-49cd-8d0e-925d70061a34)

### Non User Admin permission:

![image](https://github.com/coder/coder/assets/25542146/e150dafa-3dc7-4344-9a83-ac2e8f0c6dd1)

**Comment by matifali** [comment] 2024-06-29 19:09
Duplicate of #13454. Have already been resolved and should be available in v2.13.0. 

cc: @stirby

**Closed by matifali** 2024-06-29 19:09 UTC
Labels: site, s3, bug
