### ISSUE TITLE
No Such Container when updating workspace

### ISSUE THREAD

**Issue by djarbz** [coder/coder#10077] opened 2023-10-05 13:51 UTC
When I update a workspace, it will fail with the following error.
```
Error: Error waiting for container removal '967ce9906d7312088fa7df0018a5a666bfb9859cf4686466c7b99ad8f8c898e2': Error response from daemon: no such container
```
I can then Start the updated workspace just fine.  
I don't believe that in this case, where the container is being removed, that an error of `no such container` should be a fatal error, perhaps just a warning.

Full log in case it is helpful.
```
Terraform 1.5.6
module.code-server.coder_app.code-server: Plan to create
module.code-server.coder_script.code-server: Plan to create
module.coder-login.coder_script.coder-login: Plan to replace
module.personalize.coder_script.personalize: Plan to replace
docker_container.workspace[0]: Plan to replace
coder_metadata.container_info[0]: Plan to replace
module.coder-login.coder_script.coder-login: Destroying... [id=1ac0999e-9fea-4c2a-ae8a-6942d72024c1]
module.personalize.coder_script.personalize: Destroying... [id=b2d242b5-d7a3-4aa5-9176-71d6c4500137]
coder_metadata.container_info[0]: Destroying... [id=af94f20d-c382-406a-9146-82efc9cba555]
module.coder-login.coder_script.coder-login: Destruction complete after 0s
module.personalize.coder_script.personalize: Destruction complete after 0s
module.code-server.coder_script.code-server: Creating...
module.code-server.coder_app.code-server: Creating...
coder_metadata.container_info[0]: Destruction complete after 0s
module.code-server.coder_script.code-server: Creation complete after 0s [id=d5fa68ee-bee4-457c-9c09-5b72a472d561]
module.coder-login.coder_script.coder-login: Creating...
module.personalize.coder_script.personalize: Creating...
module.code-server.coder_app.code-server: Creation complete after 0s [id=16428cee-6ec2-42ec-b5e1-b75672b92136]
module.personalize.coder_script.personalize: Creation complete after 0s [id=15c65956-8c0a-4f6f-bcbe-24801d769d46]
module.coder-login.coder_script.coder-login: Creation complete after 0s [id=82d69aba-e84b-44bf-884d-8fc0213761d4]
docker_container.workspace[0]: Destroying... [id=967ce9906d7312088fa7df0018a5a666bfb9859cf4686466c7b99ad8f8c898e2]
docker_container.workspace[0]: Destruction errored after 1s
Error: Error waiting for container removal '967ce9906d7312088fa7df0018a5a666bfb9859cf4686466c7b99ad8f8c898e2': Error response from daemon: no such container
```

My environment is Rootless Podman on Fedora.  
I have the Podman docker socket mounted into the Coder container.  
I have included my Quadlet containerfile for reference.

```ini
[Unit]
Description=Coder Workspace Server
Documentation=https://coder.com/docs/v2/latest
RequiresMountsFor=%t/containers

## Acitvate a unit when this service fails
#OnFailure=
## Activate a unit when this service enters the "inactive" state
#OnSuccess

## Dependancy Options
# Wants will start the called service, but will not care about state.
# Requires will start the called service and will stop or restart this service in accordance to the called service.
# PartOf will stop/restart this service in accordance with the called service. This is useful for a pod member container to specify the pod infra service.
# After will only allow this service to start after the called service.
# Before will ensure that this service is started prior to the called service.
#Wants=network-online.service
Requires=network-online.service
After=network-online.service

#Wants=postgres.service
Requires=postgres.service
After=postgres.service

[Container]
ContainerName=%N
Image=ghcr.io/coder/coder:latest

PodmanArgs=--log-driver=journald
PodmanArgs=--hostname %N

Network=slirp4netns:allow_host_loopback=true
PublishPort=80:80/tcp
PublishPort=443:443/tcp

Environment=TZ=America/Chicago

EnvironmentFile=./%N.env
Environment=CODER_PG_CONNECTION_URL="postgresql://%N:%m@10.0.2.2/%N?sslmode=disable"

#SELinux: Uppercase 'Z' is for private mounts, lowercase 'z' is for shared mounts.
Volume=/etc/localtime:/etc/localtime:ro
Volume=%E/%N:/etc/coder.d:rw,Z
Volume=%t/docker.sock:/var/run/docker.sock

Label="io.containers.autoupdate=registry"

NoNewPrivileges=true
DropCapability=All
AddCapability=net_bind_service

PodmanArgs=--userns=keep-id:uid=${container_uid},gid=${container_gid}
PodmanArgs=--security-opt label=disable

[Service]
Restart=on-failure
# Restart Delay
RestartSec=30
# Restart Delay Increment
RestartSteps=30
# Max Restart Delay
RestartMaxDelaySec=300
# Allowed time for the service to start.
TimeoutStartSec=90
# Allowed time for the service to stop.
TimeoutStopSec=90

Environment=container_uid=1000
Environment=container_gid=1000

ExecStartPre=mkdir -p %E/%N
ExecStartPre=/bin/sh -c '%E/postgres_init.sh %N %N %m'
ExecStartPre=echo "Setup Complete"

[Install]
WantedBy=default.target
```

**Comment by matifali** [comment] 2023-10-06 13:58
Hi @djarbz, this error is actually coming from the docker terraform provider. As `docker_container.workspace` is an ephemeral resource, it gets destroyed and created on workspace restart. In this case, due to some reason, the docker terraform provider was not able to find the container. It could be a bug with the provider or another process on your podman host may have deleted that container

**Comment by djarbz** [comment] 2023-10-06 14:31
Ok, do you have recommendations for things that I can check to help narrow down the culprit? Or should I reach out to the developer of the Docker provider?

**Comment by djarbz** [comment] 2023-10-11 11:59
Looks like this is being tracked here: https://github.com/kreuzwerker/terraform-provider-docker/issues/542

**Comment by kylecarbs** [comment] 2024-04-26 14:42
Since this is an issue with the upstream, I'm going to close this out.

**Closed by kylecarbs** 2024-04-26 14:42 UTC
Labels: bug, s4

**Comment by djarbz** [comment] 2024-04-26 14:51
For anyone that stumbles upon this in the future, this has been working for me.
```hcl
terraform {
  required_providers {
    coder = {
      source = "coder/coder"
    }
    # docker = {
    #   source = "kreuzwerker/docker"
    # }
    docker = {
      source = "bamhm182/docker"
    }
  }
}
```

PR here: https://github.com/kreuzwerker/terraform-provider-docker/pull/583

**Comment by bamhm182** [comment] 2024-04-26 17:48
FWIW, I recommend trying to avoid using mine if possible because I don't really plan on focusing on it. It was a quick workaround until it would eventually be fixed upstream. It looks like the PR finally got accepted, so hopefully that day is soon.

That said, I have been using my fork for a few months and can report that everything has been working as intended. Super glad you found it useful too!

**Comment by djarbz** [comment] 2024-04-26 18:21
I was hoping my PR would have been approved months ago and had planned on using your fork until such a time.
I'm a bit concerned about the inactivity of the Kreuzerker repo.

**Comment by kylecarbs** [comment] 2024-04-29 14:33
@djarbz we've pinged them. They're either going to keep maintaining it or we're going to fork and maintain an active version.

**Comment by djarbz** [comment] 2024-04-29 15:18
You guys rock!

**Comment by matifali** [comment] 2024-04-29 15:25
Looks like they recently got active and have approved your PR. Also saw a PR to bump go version. 🤞
