### ISSUE TITLE
bug: when doing bulk actions from all workspaces, it reverts to the my workspaces UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#12106] opened 2024-02-12 14:30 UTC
I expect if I am in the all workspaces dashboard, that I remain there when doing bulk actions.

I deleted a bunch of other people's workspaces, and after requesting this bulk action, it reverts to my workspaces dashboard.

**Comment by aslilac** [comment] 2024-02-26 22:17
Struggling to reproduce this one. Did any of the deletions fail or anything? If you see it again could you share some of the logs from the browser console?

**Comment by sreya** [comment] 2024-03-04 16:38
Closing since we can't reproduce it

**Closed by sreya** 2024-03-04 16:38 UTC
Labels: site, s3, bug
