### ISSUE TITLE
Workspace build is pending banner shown after start

### ISSUE THREAD

**Issue by mafredri** [coder/coder#8542] opened 2023-07-17 10:04 UTC
I just noticed the pending banner stuck around after start (opening a new window didn't show the banner). Eventually, once started and waiting for agent, the banner disappeared, though.

<img width="1372" alt="image" src="https://github.com/coder/coder/assets/147409/49b5e68c-4f65-43c1-abd9-7a09c8224ff3">

**Comment by sharkymark** [comment] 2023-07-17 11:48
I noticed this behavior once as well, but not sure what caused that.

**Comment by BrunoQuaresma** [comment] 2023-08-09 14:07
@mafredri I saw this banner before but I've been not able to reproduce this rn

**Comment by mtojek** [comment] 2023-09-05 08:00
@BrunoQuaresma this should be fixed now, right?

**Comment by BrunoQuaresma** [comment] 2023-09-05 12:33
Yes!

**Closed by BrunoQuaresma** 2023-09-05 12:33 UTC
Labels: site, s2, bug
