### ISSUE TITLE
DB schema-hardcoding in migration prevents updating to >2.9.0

### ISSUE THREAD

**Issue by ns-mkusper** [coder/coder#12631] opened 2024-03-18 10:25 UTC
Version: [`v2.8.5+630ed64`](https://github.com/coder/coder/commit/630ed643cb6aef971750d0b36d2b135b717b5d24)

The `000196_external_auth_providers_jsonb.up.sql` DB migration, ran when upgrading to Coder 2.9.0, hardcodes the `public` schema, causing the migration to fail for anyone with the coder metastore provisioned with a different schema. This (and the downgrade migration) should be updated to avoid hardcoding the schema name.

**Comment by matifali** [comment] 2024-03-18 10:41
Duplicate of #12619 and recently fixed in #12620.

We will release a patch for this.

cc: @bpmct

**Comment by kylecarbs** [comment] 2024-03-18 12:56
@matifali we should make tests preventing this from happening in the future.

**Comment by matifali** [comment] 2024-03-19 14:05
fixed in [`v2.9.1`](https://github.com/coder/coder/releases/tag/v2.9.1)

**Closed** 2024-03-19 14:05 UTC
Labels: s1, bug
