### ISSUE TITLE
Bricked: when using an invalid container image and `coder create`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2545] opened 2022-06-21 12:39 UTC
I mistakenly had an invalid container image name in the `kubernetes_pod` resource of a template.

When I attempted to create a workspace based on that template i.e., `coder create`, the pod ended up in an `ImagePullBackOff` then `ErrImagePull`  STATUS loop in the Kubernetes cluster's namespace.

If I deleted the workspace from the Coder deployment, and tried to recreate it using the same workspace name, it fails in the `coder create` with:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/2022166/174799969-030e306a-dcbd-4f22-a490-ee9f4a192502.png">

*manual workaround*

1. With cluster-admin rights, `kubectl delete pod <full pod name> -n <my namespace>`
2. Update the template with a correct container image
3. Re-run `coder create` and it works

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2022166/174800902-44fb43d6-dc10-4f3b-aa60-9984db85f55d.png">

**Comment by ketang** [comment] 2022-06-29 01:07
We should fix this pretty soon; it seems like a situation someone could easily fall into.

**Comment by bpmct** [comment] 2022-07-22 14:09
I'm confused why Kubernetes didn't delete the pod but agreed it is something we should look into.

**Comment by kylecarbs** [comment] 2022-08-24 15:38
This is a duplicate of #2256

**Closed by kylecarbs** 2022-08-24 15:38 UTC
