### ISSUE TITLE
Workspace server crash when not completing connection using VSCode

### ISSUE THREAD

**Issue by charsleysa** [coder/coder#9119] opened 2023-08-15 23:20 UTC
Looks like the agent crashed causing the whole server to crash.

Using VSCode I had started to connect to the workspace but then cancelled and closed VSCode.
When I tried to connect again I noticed that it had crashed.

I have attached the relevant logs. Here's the error message snippet:

```
2023-08-16T10:19:15+12:00	2023-08-15 22:19:15.863 [erro]  close workspace agent coordinate websocket  error="failed to close WebSocket: already wrote close"
2023-08-16T10:19:15+12:00	2023-08-15 22:19:15.863 [erro]  close workspace agent derp map websocket  error="failed to close WebSocket: already wrote close"
2023-08-16T10:19:15+12:00	2023-08-15 22:19:15.863 [debu]  coordinate pinger exited
2023-08-16T10:19:15+12:00	2023-08-15 22:19:15.863 [debu]  derp map pinger exited
2023-08-16T10:19:16+12:00	2023-08-15 22:19:16.009 [debu]  net.tailnet.net.wgengine: [unexpected] magicsock: derp-999 does not know about peer [gSehK], removing route
2023-08-16T10:19:16+12:00	2023-08-15 22:19:16.009 [debu]  net.tailnet.net.wgengine: [unexpected] magicsock: derp-999 does not know about peer [h0c8n], removing route
2023-08-16T10:19:16+12:00	2023-08-15 22:19:16.009 [debu]  net.tailnet.net.wgengine: [unexpected] magicsock: derp-999 does not know about peer [gSehK], removing route
2023-08-16T10:19:16+12:00	2023-08-15 22:19:16.009 [warn]  run exited with error ...
2023-08-16T10:19:16+12:00	    error= run derp map subscriber:
2023-08-16T10:19:16+12:00	               github.com/coder/coder/agent.(*agent).run.func4
2023-08-16T10:19:16+12:00	                   /home/runner/actions-runner/_work/coder/coder/agent/agent.go:727
2023-08-16T10:19:16+12:00	             - context canceled
2023-08-16T10:19:16+12:00	2023/08/15 22:19:16 wgengine watchdog stacks:
2023-08-16T10:19:16+12:00	goroutine profile: total 179
2023-08-16T10:19:16+12:00	16 @ 0x43bf16 0x406fbd 0x406af8 0xf40ff9 0x470581
2023-08-16T10:19:16+12:00	#	0xf40ff8	github.com/tailscale/wireguard-go/device.(*Device).RoutineDecryption+0x198	/home/runner/go/pkg/mod/github.com/coder/wireguard-go@v0.0.0-20230807234434-d825b45ccbf5/device/receive.go:245
```

[Explore-logs-2023-08-16 11_13_39.txt](https://github.com/coder/coder/files/12353683/Explore-logs-2023-08-16.11_13_39.txt)

**Comment by coadler** [comment] 2023-08-15 23:47
Thanks for reporting this @charsleysa! Would you be able to provide logs from at least `2023-08-15T22:16:00Z`? It seems like `UpdateStatus` is hanging, but the logs don't go back far enough to see what might have happened. Just FYI they may contain public IPs if you would like to scrub those first, or you can email them to me `colin at coder dot com`.

**Comment by charsleysa** [comment] 2023-08-16 00:04
I've sent the requested logs by email.

**Comment by spikecurtis** [comment] 2023-08-16 05:45
Also @charsleysa this is similar to some stuff I've been fixing lately, so it'll be helpful to know the exact version of Coder you are running.

**Comment by charsleysa** [comment] 2023-08-16 05:49
Sorry, forgot to mention version! I'm running coder 2.0.2. I restarted the workspace after updating coder.

**Comment by spikecurtis** [comment] 2023-08-16 07:03
So, as @coadler mentioned, the crash happened because the tailscale engine `UpdateStatus` took too long to complete.

What's interesting about the stack trace is that I don't see the real call to `UpdateStatus` in the running goroutines.

```
2023-08-16T10:19:16+12:00	1 @ 0x43bf16 0x4061ae 0x405d5d 0x10e0185 0x470581
2023-08-16T10:19:16+12:00	#	0x10e0184	tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func2+0x44	/home/runner/go/pkg/mod/github.com/coder/tailscale@v1.1.1-0.20230809183309-7a9c6c71e16c/wgengine/watchdog.go:83
```

This is the watchdog function that calls into the real engine for UpdateStatus, and since that goroutine _doesn't_ have any stack frames for UpdateStatus, it means that the real UpdateStatus has completed, so it can't have been a hard deadlock. Also, the watchdog timeout is 45s, but the watchdog is reporting that it's 53s since it started the real UpdateStatus function.  So, somehow UpdateStatus took over 45s, but then it took at least 8 more seconds for the watchdog to notice and collect the stack traces, by which time UpdateStatus was done.  8 seconds to gather stack traces is a really long time!

Can you tell us more about your workspace and what was running in it?  How much CPU and memory did it have, and were there any resource intensive processes running at the time?

I'm also noticing that pings for the websockets back to Coderd were timing out.  That alone shouldn't bring down the agent, but I can't help but wonder if the timeouts there were also secondary to a resource squeeze on the agent.

**Comment by charsleysa** [comment] 2023-08-16 07:17
The workspace is a VM running on fly.io using the code-server docker image. The VM has 16 cores and 128GB RAM with a 1TB drive. Resource consumption was pretty high. 

I was running an Open Street Maps import as part of the OSMNames process (with a few configuration tweaks which can be found in this repo https://github.com/mymahi/OSMNames/tree/generating).

**Comment by spikecurtis** [comment] 2023-08-16 09:27
I'm going to close this issue in favor of #8517 since I believe that being resource constrained is the root cause of this issue.  Feel free to reopen if you think my analysis is wrong, or e.g. you still experience the issue while running your import job `nice 15`

**Closed by spikecurtis** 2023-08-16 09:27 UTC
Labels: bug
