### ISSUE TITLE
Use workspace status instead of deriving it

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1720] opened 2022-05-24 17:53 UTC
When the API is updated to have a `status` field on a WorkspaceBuild, the frontend can stop deriving workspace status with `getWorkspaceStatus` and just use the returned value. It will still need to transform the bare status (such as "started") into display copy (such as "Running"), so that code can remain in place.

**Comment by Kira-Pilot** [comment] 2022-07-22 15:09
Note: would love to have the enum for `workspaceStatus`. Right now, we are rolling our own in `site/src/components/WorkspaceActions/constants.ts`

**Comment by Kira-Pilot** [comment] 2022-07-22 18:48
@presleyp is this a duplicate of #2772

**Comment by presleyp** [comment] 2022-07-22 18:57
@Kira-Pilot I think so. I wrote this when @f0ssel, IIRC, decided to add the workspace status to the API. Looks like #2772 is a ticket to do that and update the frontend. @AbhineetJain sound right?

**Comment by Kira-Pilot** [comment] 2022-07-25 16:44
Closing in favor of #2772!

**Closed by Kira-Pilot** 2022-07-25 16:44 UTC
Labels: frontend, needs grooming
