### ISSUE TITLE
referencing `coder_agent` via `terraform_data` in the `coder_metadata` resource hides all connection buttons

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10336] opened 2023-10-18 23:00 UTC
a customer is using the `terraform_data` resource. this can't be hidden properly, because whenever `hide = true`, the coder_agent resource also got hidden which is undesirable, since it contains all the main actions like Connect via Terminal/SSH/VSCode. 

```hcl
resource "coder_metadata" "terraform_coder_agent_token" {
  resource_id = terraform_data.coder_agent_token.id
  hide        = true # doesn't work
}
```

**Comment by sreya** [comment] 2023-10-30 18:13
@ericpaulsen can you post a screenshot please?

**Comment by ericpaulsen** [comment] 2023-10-31 13:22
@sreya they didn't provide a screenshot. here's the thread: https://codercom.slack.com/archives/C0530DKPE58/p1697669308321619

**Comment by aslilac** [comment] 2023-11-07 17:25
they're no longer running into this issue, and I couldn't reproduce it, so I'm just gonna close this

**Closed by aslilac** 2023-11-07 17:25 UTC
Labels: bug
