### ISSUE TITLE
flake: WorkspacePage › requests a delete job when the user presses Delete and confirms

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#12018] opened 2024-02-05 12:23 UTC
Seen here:

https://github.com/coder/coder/actions/runs/7782668393/job/21219588406

```
Unable to find an element with the text: Test-Workspace. 
```

**Comment by johnstcn** [comment] 2024-03-12 11:02
Also cropped up here: https://github.com/coder/coder/actions/runs/8247510911/job/22555817923?pr=12547

**Comment by Parkreiner** [comment] 2024-03-12 12:10
Yeah, I have been looking into this on-and-off, but I did a bad job of communicating that my focus was a bit split
Once we have Backstage launch happens Friday, this is the first thing I'm planning to get to (even if I have to do this work on Sunday)

I've been dropping the ball, but this is going to get done

**Comment by stirby** [comment] 2024-05-31 14:35
@Parkreiner just want to bump in your notifs. No worries on the delay, feel free to unassign if you're backlog is too full.

**Comment by Parkreiner** [comment] 2024-05-31 15:02
Yeah, I'll go ahead and un-assign myself for now

From the error messages, it looks like we are using the right selectors for checking whether something is on screen. We're using the version that waits a little bit for something to load in, and is generally more fault-tolerant

But the fact that it's _still_ timing out makes me think that either we have some bad UI rendering performance, or there's something wonky in the logic that is causing things to load in inconsistently. It's probably going to require a good bit of digging to find the root cause, though

**Comment by sreya** [comment] 2024-08-05 16:12
Closing this since the logs are no longer available. We'll reopen when we see it, doesn't seem anyone's looking at it anyway.

**Closed by sreya** 2024-08-05 16:12 UTC
Labels: chore, flake, s4
