### ISSUE TITLE
Couple suggestions for the coder deployment issues banner

### ISSUE THREAD

**Issue by smolinari** [coder/coder#9692] opened 2023-09-15 07:31 UTC
Hi,

![image](https://github.com/coder/coder/assets/3314957/b111565b-473c-4680-b2c5-c4545b3ab8b0)

I have my k8s cluster in an el-cheapo VPS setup and sometimes it isn't the "smoothest" experience. It's all just POC stuff mainly anyway, so because of the low performance, I get the "coder deployment issues" banner here and there and it is...well..... annoying. I get the banner mainly due to the database connection latency, I think. I don't know, because I am given no information as to why there is a test failure and according to the image above, latency isn't all that bad. 

Here are my suggestions. 

1. Make the banner dismissable (or do it differently altogether - see point 4). 

2. Offer a button to be able to retest the condition. 

3. Offer better feedback as to why the failure is noted. `"healthy": false,` says nothing to the condition needing rectification for the database, which again, is the issue I run into most. 

4. Offer a less "in your face" error warning. Like maybe a red dot with a white exclamation mark icon on the user's avatar and when clicking on the avatar, have a menu item leading to the health issue or the health page. Or put the exclamation icon on the "Deployment" tab and on the "Health" menu item under "Deployment". That will lead the admin (hopefully the admin only sees this) to the issue report. 

That's all. Thanks for considering these suggestions in advance. 

Scott

**Comment by matifali** [comment] 2023-09-15 09:03
@smolinari This is marked as healthy when latency is greater than 15 ms. I agree that it should be reflected and marked as a warning.
We have this on our roadmap. See #8971, #8970, and #9381

**Comment by matifali** [comment] 2023-09-15 09:04
@aslilac I would appreciate your thoughts in the context of #8971 for improving the UX.

**Comment by aslilac** [comment] 2023-09-15 18:48
My test license expires in like 20 days, so I've had a similarly frustrating banner while working, and am definitely interested in seeing improvements here :p

I like the idea of having it just be a little badge on something that you can expand into a more lengthy explanation of what is happening. Also that it should really only be shown to admins/people who we expect can actually take action on whatever the issue is.

**Comment by matifali** [comment] 2023-09-17 10:06
Railway.app does not support derp, and the Coder's health check keeps showing a constant red banner that something is wrong.

**Closed** 2023-10-13 16:39 UTC
Labels: feature, site
