### ISSUE TITLE
Some metadata disappears from the UI for a long time, repeatedly

### ISSUE THREAD

**Issue by mafredri** [coder/coder#8577] opened 2023-07-18 14:18 UTC
I don't know what's the cause, but using the Coder on Coder template on dev.coder.com, I'm seeing metadata appears for a short while, only to disappear again. This happens repeatedly.

Meanwhile, the VSCode extension is showing the values correctly.

Video:

https://github.com/coder/coder/assets/147409/a5eba872-9822-4883-bc2b-84aca59d89e7

Metadata appear at 0:58 and 3:58, so it seems to be on some interval. There might've been a redeploy/reconnect of dev.coder.com too somewhere around the 3-minute mark.

**Comment by matifali** [comment] 2023-07-18 14:22
I am seeing the same behavior too. 
In a different country, and on iPad. So it's not a device or network issue. 
But we both do use the Europe region.

**Comment by BrunoQuaresma** [comment] 2023-07-19 12:55
One thing to look for is what data the web socket is sending. Sometimes I have seen the server sending null values making the loading state to be visible. I also noticed this happens during Coder deployments and when we have some instability(in the last two weeks I have been facing some timeouts when using yarn dev pointing to dev.coder.com, I thought it would be because of Coder deployments but they are very frequent).

We could make the FE just ignore null values but I wold rather do the fix on the BE so other clients would not have to workaround this.

**Comment by matifali** [comment] 2023-07-19 13:14
I have reproduced the issue on a deployment that follows the dev.coder.com version.
version: [v0.26.1-devel+4232a2eb9](https://github.com/coder/coder/commit/4232a2eb96a44ab4308193094ff7b8d30397049b)

**Comment by matifali** [comment] 2023-08-04 14:56
fixed by #8614

**Closed by matifali** 2023-08-04 14:56 UTC
Labels: site, p1, bug
