### ISSUE TITLE
Move `--private` from `templates edit` to `templates push`

### ISSUE THREAD

**Issue by sreya** [coder/coder#11565] opened 2024-01-11 01:26 UTC
This was added as part of the refactor to maintain parity between `templates create` and `templates edit` however the flag was only intended to be used for initial template creation. We should move it to `templates push` and only allow it to be used in conjunction with `--create`.

**Comment by matifali** [comment] 2024-01-11 08:26
I think we should do it now before the release to later prevent a breaking change.

**Comment by f0ssel** [comment] 2024-01-11 14:30
This isn't so much of a bug but more of a "Where does this flag go now?". The `--create` flag doesn't exist anymore, and I didn't want flags on `push` that only conditionally and silently apply. But considering the issues you've identified I'm fine with moving it back to create with the DX being slightly confusing.

**Comment by matifali** [comment] 2024-01-11 14:40
@f0ssel We should not put it back to `create` as that is deprecated and will be removed soon. How about having this in 'push' but limiting usage if a template is created for the first time? Just fail with an error that you can not use `coder template push --private` while updating an existing template.

**Comment by f0ssel** [comment] 2024-01-11 15:46
@matifali The issue with that is that the value of `template push` is that it "always works" even if the template is not created. By adding these behaviors users are better off just explicitly using create. I think we need to clarify what use cases we'd like to cover with these set of commands and make sure we are providing a good UX for those cases.

**Comment by matifali** [comment] 2024-01-11 16:33
I will wait for @sreya and @ammario comments before we make a decision here.

**Comment by ammario** [comment] 2024-01-11 19:44
I'm a little bit confused about the issue with putting it on `template push`. `--private` would be a no-op if the template is already private, right?

**Comment by ammario** [comment] 2024-01-11 19:47
There was a customer issue a while back about putting access controls in `template edit` alone. IIRC the issue is that there's a race condition between when the template is created and when the template is edited because there's a period of time where its available for the entire deployment. Also, edit can fail and now a potentially sensitive template is public.

Thus, if `push` is handling our creates, `push` must also handle access controls.

**Comment by sreya** [comment] 2024-01-12 00:48
Yeah I'm in agreement with @ammario, I think we move `--private` to `template push` and print a warning if used against an existing template, for which it will be a no-op.

**Comment by ammario** [comment] 2024-01-12 16:50
🤔 shouldn't we brand `template push` as idempotent and declarative? If we go with the approach of giving a warning and making it a no-op on subsequent pushes, we would have to create some other command for modifying access after a template is created?

**Comment by f0ssel** [comment] 2024-01-12 17:47
We can, but I believe that means we need to support the private flag via the edit API, which is currently being removed in the active PR for this issue. Sounds like we need a quick sync.

**Comment by sreya** [comment] 2024-01-16 21:21
The `edit` command should support adding arbitrary users and groups the same way the `coder groups edit` command does. It doesn't really make sense to have the `--private` flag exist on `edit`. The sole intent of `--private` from what I understand is to eliminate the window between a template being created and it being updated to remove the `Everyone` group so supporting it beyond template creation feels a little weird. It's not a huge deal either way to me.

**Comment by ammario** [comment] 2024-01-17 22:08
Understood. I'm good with forcing it to be used in conjunction with `--create` as a special rule.

**Closed** 2024-08-30 14:42 UTC
Labels: s3, bug
