### ISSUE TITLE
Issue bumping workspace schedule

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10905] opened 2023-11-27 20:31 UTC
Any idea what is going on here?

https://github.com/coder/coder/assets/22407953/4ce23116-247c-4d96-a46c-b35f7e74e4e3

**Comment by BrunoQuaresma** [comment] 2024-02-02 11:36
Much of this component has been changed in the past months and I was not able to reproduce this error. Closing it for now.

**Closed by BrunoQuaresma** 2024-02-02 11:36 UTC
Labels: bug
